# -*- coding: utf-8 -*-
"""Loops (40)."""

LOOPS = [
    ("code_generation", "beginner",
     "Write a for loop that prints the numbers 1 through 5 separated by spaces.",
     '<?php\nfor ($i = 1; $i <= 5; $i++) {\n    echo $i, " ";\n}',
     "1 2 3 4 5",
     "The for loop initializes $i=1, continues while $i<=5, and increments after each iteration.",
     "Using $i < 5 which stops at 4 instead of 5.",
     None,
     "assertEquals('1 2 3 4 5 ', $out);"),
    ("code_generation", "beginner",
     "Write a while loop that prints a countdown from 3 to 1.",
     "<?php\n$i = 3;\nwhile ($i >= 1) {\n    echo $i;\n    $i--;\n}",
     "321",
     "The while loop runs while the condition holds and decrements $i each iteration until it drops below 1.",
     "Forgetting to decrement $i, which creates an infinite loop.",
     None,
     "assertEquals('321', $out);"),
    ("predict_output", "beginner",
     "What is printed by this do-while loop?",
     "<?php\n$i = 10;\ndo {\n    echo $i;\n    $i++;\n} while ($i < 5);",
     "10",
     "A do-while executes the body at least once before checking the condition, so it prints 10 then stops.",
     "Expecting the loop to not run at all because 10 is not less than 5.",
     None,
     "assertEquals('10', $out);"),
    ("code_generation", "intermediate",
     "Write a foreach loop that prints each value of an associative array as key => value.",
     "<?php\n$ages = ['Ada' => 36, 'Bob' => 40];\nforeach ($ages as $name => $age) {\n    echo \"$name: $age\\n\";\n}",
     "Ada: 36\nBob: 40",
     "foreach can capture both the key ($name) and the value ($age) when iterating associative arrays.",
     "Swapping the order to ($age => $name) and confusing keys with values.",
     None,
     "assertStringContainsString('Ada: 36', $out);"),
    ("find_bug", "intermediate",
     "This loop should sum the array but prints 0. Find the bug.",
     "<?php\n$sum = 0;\nforeach ([1, 2, 3] as $n) {\n    $sum = $n;\n}\necho $sum;",
     "3",
     "The line $sum = $n overwrites the accumulator each time instead of adding, so it ends with the last value 3.",
     "Using = instead of += inside an accumulator loop.",
     "<?php\n$sum = 0;\nforeach ([1, 2, 3] as $n) {\n    $sum += $n;\n}\necho $sum;",
     "assertEquals(6, $sum);"),
    ("code_explanation", "intermediate",
     "Explain what continue does in this loop.",
     "<?php\nforeach ([1, 2, 3, 4] as $n) {\n    if ($n === 2) {\n        continue;\n    }\n    echo $n;\n}",
     "134",
     "continue skips the rest of the current iteration and moves to the next one, so 2 is not printed.",
     "Confusing continue (skip this iteration) with break (stop the loop).",
     None,
     "assertEquals('134', $out);"),
    ("code_generation", "intermediate",
     "Write a loop that uses break to stop when a target value is found.",
     "<?php\n$target = 3;\nforeach ([1, 2, 3, 4, 5] as $n) {\n    if ($n === $target) {\n        echo \"found $n\";\n        break;\n    }\n}",
     "found 3",
     "break exits the loop entirely once the value is found, avoiding unnecessary iterations.",
     "Using continue instead of break, which keeps looping after the match.",
     None,
     "assertEquals('found 3', $out);"),
    ("code_generation", "advanced",
     "Write a loop that modifies array elements by reference to double each value.",
     "<?php\n$nums = [1, 2, 3];\nforeach ($nums as &$n) {\n    $n *= 2;\n}\nunset($n);\nprint_r($nums);",
     "[2,4,6]",
     "Iterating by reference lets the loop write back into the array; unset($n) afterwards prevents the last reference from lingering.",
     "Forgetting unset($n), which leaves a dangling reference that can corrupt later code.",
     None,
     "assertEquals([2,4,6], $nums);"),
    ("predict_output", "advanced",
     "What is printed? Watch for reference leakage between the two foreach loops.",
     "<?php\n$nums = [1, 2, 3];\nforeach ($nums as &$n) {}\nforeach ($nums as $n) {}\nprint_r($nums);",
     "Array ( [0] => 1 [1] => 2 [2] => 2 )",
     "Because the reference from the first loop is not unset, the second loop overwrites the last element on each pass.",
     "Reusing the same variable name for a reference loop and then a value loop, causing reference leakage.",
     "<?php\n$nums = [1, 2, 3];\nforeach ($nums as &$n) {}\nunset($n);\nforeach ($nums as $n) {}\nprint_r($nums);",
     "assertEquals([1,2,3], $nums);"),
    ("code_generation", "beginner",
     "Write a foreach loop that prints each element of a list on its own line.",
     "<?php\nforeach (['a', 'b', 'c'] as $letter) {\n    echo $letter, PHP_EOL;\n}",
     "a\nb\nc",
     "foreach visits each element without needing an index counter.",
     "Manually managing an index when foreach is simpler and less error-prone.",
     None,
     "assertEquals(\"a\nb\nc\n\", $out);"),
    ("find_bug", "beginner",
     "This loop should print 5 through 1 but prints nothing. Find the bug.",
     "<?php\nfor ($i = 5; $i > 0; $i--) {\n    echo $i;\n}",
     "54321",
     "There is no bug; the loop counts down correctly. A likely real error would be a wrong condition such as $i < 0.",
     "Writing a condition that is false from the start, such as $i < 0, so the body never runs.",
     None,
     "assertEquals('54321', $out);"),
    ("code_generation", "intermediate",
     "Write a nested loop that prints a 3x3 multiplication table row by row.",
     "<?php\nfor ($i = 1; $i <= 3; $i++) {\n    for ($j = 1; $j <= 3; $j++) {\n        echo $i * $j, \" \";\n    }\n    echo PHP_EOL;\n}",
     "1 2 3\n2 4 6\n3 6 9",
     "The outer loop controls rows, the inner loop controls columns, and the newline is emitted per row.",
     "Printing the newline inside the inner loop, which breaks the rows apart.",
     None,
     "assertStringContainsString('2 4 6', $out);"),
    ("code_generation", "intermediate",
     "Write a loop that iterates over an array and unset the even values in place.",
     "<?php\n$d = [1, 2, 3, 4];\nforeach ($d as $k => $v) {\n    if ($v % 2 === 0) {\n        unset($d[$k]);\n    }\n}\nprint_r($d);",
     "Array ( [0] => 1 [2] => 3 )",
     "Iterating over keys lets you unset elements by key; the remaining keys keep their original values.",
     "Using unset on $v, which only removes the local loop variable and not the array element.",
     None,
     "assertEquals([0=>1, 2=>3], $d);"),
    ("predict_output", "intermediate",
     "What does this nested loop print?",
     "<?php\nforeach ([1, 2] as $a) {\n    foreach ([10, 20] as $b) {\n        echo $a + $b, \" \";\n    }\n}",
     "11 21 12 22",
     "The outer value 1 pairs with 10 and 20, then the outer value 2 pairs with 10 and 20, in order.",
     "Mixing up which loop runs fastest; the inner loop completes before the outer advances.",
     None,
     "assertEquals('11 21 12 22 ', $out);"),
    ("code_generation", "advanced",
     "Write a loop that uses the continue statement with a numeric argument to skip two levels.",
     "<?php\nforeach ([1, 2] as $a) {\n    foreach ([1, 2] as $b) {\n        if ($b === 2) {\n            continue 2;\n        }\n        echo \"$a$b \";\n    }\n}",
     "11 21",
     "continue 2 skips to the next iteration of the outer loop, bypassing the inner loop's remaining work.",
     "Using continue without the level argument, which only skips the inner iteration.",
     None,
     "assertEquals('11 21 ', $out);"),
    ("code_review", "intermediate",
     "Review this loop that recomputes count() on every iteration.",
     "<?php\n$items = [1,2,3,4];\nfor ($i = 0; $i < count($items); $i++) {\n    echo $items[$i];\n}",
     "1234",
     "Calling count() each iteration is wasteful for large arrays; store it in a variable or use foreach.",
     "Recomputing an invariant inside the loop condition instead of hoisting it.",
     "<?php\n$items = [1,2,3,4];\n$n = count($items);\nfor ($i = 0; $i < $n; $i++) {\n    echo $items[$i];\n}",
     "assertEquals('1234', $out);"),
    ("code_generation", "beginner",
     "Write a loop that iterates a range using the range() function.",
     "<?php\nforeach (range(1, 4) as $n) {\n    echo $n;\n}",
     "1234",
     "range(1, 4) produces [1,2,3,4], which foreach then walks in order.",
     "Using range(1, 4, 1) and expecting different behavior; the third argument is the step.",
     None,
     "assertEquals([1,2,3,4], range(1,4));"),
    ("predict_output", "advanced",
     "What is printed? Explain how continue affects this for loop.",
     "<?php\nfor ($i = 0; $i < 3; $i++) {\n    if ($i === 1) {\n        continue;\n    }\n    echo $i;\n}",
     "02",
     "When $i is 1 the loop skips printing; otherwise it prints 0 and 2.",
     "Thinking continue also skips the increment step of the for loop; it does not.",
     None,
     "assertEquals('02', $out);"),
    ("code_generation", "intermediate",
     "Write a loop that builds an associative array mapping numbers to their squares.",
     "<?php\n$sq = [];\nfor ($i = 1; $i <= 3; $i++) {\n    $sq[$i] = $i * $i;\n}\nprint_r($sq);",
     "Array ( [1] => 1 [2] => 4 [3] => 9 )",
     "Assigning to $sq[$i] builds the key/value pairs as the loop progresses.",
     "Overwriting the whole array with $sq = [...] inside the loop instead of appending.",
     None,
     "assertEquals([1=>1,2=>4,3=>9], $sq);"),
    ("find_bug", "intermediate",
     "This should print 'done' after the loop but prints it many times. Find the bug.",
     "<?php\nforeach ([1,2,3] as $n) {\n    if ($n > 0) {\n        echo 'done';\n    }\n}",
     "donedonedone",
     "The echo is inside the loop, so it prints once per matching element instead of once after the loop.",
     "Placing a summary statement inside the loop body instead of after it.",
     "<?php\nforeach ([1,2,3] as $n) {\n    if ($n > 0) {\n        $any = true;\n    }\n}\nif ($any ?? false) {\n    echo 'done';\n}",
     "assertEquals('done', $out);"),
    ("code_explanation", "advanced",
     "Explain how a foreach by reference and a following foreach by value can leak.",
     "<?php\n$a = [1,2,3];\nforeach ($a as &$v) {}\nunset($v);\nforeach ($a as $v) { echo $v; }",
     "123",
     "The unset($v) clears the reference, so the second loop safely iterates by value and prints 1,2,3.",
     "Skipping unset($v) after a reference loop, which corrupts the array in a following value loop.",
     None,
     "assertEquals('123', $out);"),
    ("code_generation", "intermediate",
     "Write a loop that prints the index and value of an indexed array.",
     "<?php\n$fruits = ['apple', 'banana'];\nforeach ($fruits as $i => $f) {\n    echo \"$i:$f \";\n}",
     "0:apple 1:banana",
     "For a list, the foreach key is the integer index, so you can print both position and value.",
     "Expecting the key to be 1-based; it is 0-based for lists.",
     None,
     "assertEquals('0:apple 1:banana ', $out);"),
    ("code_generation", "advanced",
     "Write a loop that uses a labeled break to exit two nested loops at once.",
     "<?php\nforeach ([[1,2],[3,4]] as $row) {\n    foreach ($row as $cell) {\n        if ($cell === 3) {\n            break 2;\n        }\n        echo $cell;\n    }\n}",
     "12",
     "break 2 exits both the inner and the outer loop when 3 is found, so only 1 and 2 are printed.",
     "Using break without a level, which only exits the inner loop.",
     None,
     "assertEquals('12', $out);"),
    ("predict_output", "beginner",
     "What is printed by this loop that increments twice?",
     "<?php\nfor ($i = 0; $i < 5; $i += 2) {\n    echo $i;\n}",
     "024",
     "The step is 2, so $i takes the values 0, 2, 4 before reaching 5.",
     "Expecting every integer to be printed when the step is 2.",
     None,
     "assertEquals('024', $out);"),
    ("code_review", "beginner",
     "Review this infinite loop and suggest a fix.",
     "<?php\n$i = 0;\nwhile ($i < 3) {\n    echo $i;\n}",
     "infinite 0s then timeout",
     "The loop never increments $i, so the condition never becomes false; add $i++ inside the body.",
     "Forgetting to update the loop control variable inside a while loop.",
     "<?php\n$i = 0;\nwhile ($i < 3) {\n    echo $i;\n    $i++;\n}",
     "assertEquals('012', $out);"),
    ("code_generation", "intermediate",
     "Write a loop that skips null values while iterating.",
     "<?php\nforeach ([1, null, 2, null, 3] as $v) {\n    if ($v === null) {\n        continue;\n    }\n    echo $v;\n}",
     "123",
     "The null check with continue filters out nulls before printing.",
     "Using empty() which also skips 0, changing the intended result.",
     None,
     "assertEquals('123', $out);"),
    ("code_generation", "advanced",
     "Write a loop that uses a generator function to iterate lazily.",
     "<?php\nfunction gen() {\n    for ($i = 1; $i <= 3; $i++) {\n        yield $i;\n    }\n}\n$total = 0;\nforeach (gen() as $v) {\n    $total += $v;\n}\necho $total;",
     "6",
     "The generator produces values on demand, and the loop accumulates them without materializing the whole sequence.",
     "Calling count() on the generator result, which is not an array.",
     None,
     "assertEquals(6, $total);"),
    ("find_bug", "advanced",
     "This loop should collect unique values but has duplicates. Find the bug.",
     "<?php\n$seen = [];\nforeach (['a','a','b'] as $v) {\n    $seen[] = $v;\n}\nprint_r(array_unique($seen));",
     "Array ( [0] => a [1] => a [2] => b )",
     "array_unique is called to deduplicate but its result is not assigned, so the original with duplicates is printed.",
     "Calling array_unique without assigning or outputting its return value.",
     "<?php\n$seen = [];\nforeach (['a','a','b'] as $v) {\n    $seen[] = $v;\n}\nprint_r(array_values(array_unique($seen)));",
     "assertEquals(['a','b'], array_values(array_unique($seen)));"),
    ("code_explanation", "beginner",
     "Explain the order in which this loop executes its three parts.",
     "<?php\nfor ($i = 1; $i <= 2; $i++) {\n    echo $i;\n}",
     "12",
     "The initializer runs once, then the condition is checked, the body runs, and the increment runs, repeating until the condition fails.",
     "Thinking the increment runs before the body on the first iteration; it runs after.",
     None,
     "assertEquals('12', $out);"),
    ("code_generation", "intermediate",
     "Write a loop that prints the keys of an associative array only.",
     "<?php\n$cfg = ['host' => 'h', 'port' => 1];\nforeach (array_keys($cfg) as $k) {\n    echo $k, \" \";\n}",
     "host port",
     "array_keys() returns the keys, which the loop then prints.",
     "Iterating the array directly and printing the values instead of the keys.",
     None,
     "assertEquals('host port ', $out);"),
    ("predict_output", "intermediate",
     "What is printed? Compute the running total of the loop.",
     "<?php\n$sum = 0;\nfor ($i = 1; $i <= 4; $i++) {\n    $sum += $i;\n}\necho $sum;",
     "10",
     "The sum accumulates 1+2+3+4 which equals 10.",
     "Starting the loop at 0 or including 5, which changes the total.",
     None,
     "assertEquals(10, $sum);"),
    ("code_generation", "beginner",
     "Write a loop that prints each character of a string.",
     "<?php\nforeach (str_split('abc') as $ch) {\n    echo $ch;\n}",
     "abc",
     "str_split() converts the string into an array of characters that foreach can walk.",
     "Using foreach directly on a string, which is not iterable in PHP.",
     None,
     "assertEquals('abc', $out);"),
    ("code_generation", "advanced",
     "Write a loop that uses array_map with a closure instead of an explicit loop.",
     "<?php\n$nums = [1, 2, 3];\n$doubled = array_map(fn($n) => $n * 2, $nums);\nprint_r($doubled);",
     "[2,4,6]",
     "array_map applies the callback to each element and returns a new array without an explicit loop.",
     "Forgetting that array_map returns a new array and does not modify in place.",
     None,
     "assertEquals([2,4,6], $doubled);"),
    ("code_review", "advanced",
     "Review this loop for array modification during iteration.",
     "<?php\n$list = [1, 2, 3];\nforeach ($list as $k => $v) {\n    if ($v === 2) {\n        unset($list[$k + 1]);\n    }\n}",
     "removes element after 2",
     "Modifying an array while foreach iterates a copy causes surprising results; prefer building a new array or collecting keys to remove.",
     "Mutating the array being iterated, which leads to skipped or unexpected elements.",
     "<?php\n$list = [1, 2, 3];\n$out = [];\nforeach ($list as $k => $v) {\n    if ($v !== 3) {\n        $out[] = $v;\n    }\n}\n$list = $out;",
     "assertEquals([1,2], $list);"),
    ("code_generation", "intermediate",
     "Write a loop that sums only the even numbers of an array.",
     "<?php\n$total = 0;\nforeach ([1,2,3,4,5,6] as $n) {\n    if ($n % 2 === 0) {\n        $total += $n;\n    }\n}\necho $total;",
     "12",
     "Only even numbers pass the modulo check and are added: 2+4+6 equals 12.",
     "Adding odd numbers because the condition is inverted.",
     None,
     "assertEquals(12, $total);"),
    ("find_bug", "intermediate",
     "This loop should print 1 to 3 but prints 1 to 4. Find the bug.",
     "<?php\nfor ($i = 1; $i <= 3; $i++) {\n    echo $i;\n}",
     "123",
     "There is no bug; the output is 123. A real off-by-one arises with < instead of <= for the same bounds.",
     "Using <= when you intend to exclude the upper bound, causing an off-by-one.",
     None,
     "assertEquals('123', $out);"),
    ("code_generation", "advanced",
     "Write a loop that uses array_reduce to compute a product.",
     "<?php\n$product = array_reduce([2,3,4], fn($carry, $n) => $carry * $n, 1);\necho $product;",
     "24",
     "array_reduce folds the array into one value using the callback, starting from the initial carry of 1.",
     "Using an initial carry of 0 for multiplication, which makes the product always 0.",
     None,
     "assertEquals(24, $product);"),
    ("predict_output", "beginner",
     "What is the output of this while countdown loop?",
     "<?php\n$i = 3;\nwhile ($i > 0) {\n    echo $i--;\n}",
     "321",
     "The while loop decrements $i after printing it, so it prints 3, 2, 1 and stops when $i reaches 0.",
     "Expecting 0 to be printed when the condition is > 0.",
     None,
     "assertEquals('321', $out);"),
    ("code_explanation", "intermediate",
     "Explain why this loop prints nothing.",
     "<?php\nforeach ([] as $x) {\n    echo $x;\n}",
     "",
     "foreach over an empty array has no elements to iterate, so the body never executes.",
     "Expecting an error from iterating an empty array; there is none.",
     None,
     "assertEquals(0, count([]));"),
    ("code_generation", "intermediate",
     "Write a loop that prints the first ten Fibonacci numbers using an array.",
     "<?php\n$fib = [0, 1];\nfor ($i = 2; $i < 10; $i++) {\n    $fib[$i] = $fib[$i-1] + $fib[$i-2];\n}\necho implode(',', $fib);",
     "0,1,1,2,3,5,8,13,21,34",
     "Each new value is the sum of the two previous entries, building the sequence iteratively.",
     "Reading $fib[$i-1] before it exists on the first iterations causes undefined-index warnings if indices are wrong.",
     None,
     "assertEquals(10, count($fib));"),
    ("code_review", "intermediate",
     "Review this loop that uses a magic number as a bound.",
     "<?php\nfor ($i = 0; $i < 7; $i++) {\n    process($i);\n}",
     "runs process 7 times",
     "A bare 7 hides intent; extract it into a named constant or count($items) for clarity.",
     "Hard-coding loop bounds instead of deriving them from data size.",
     "<?php\n$days = 7;\nfor ($i = 0; $i < $days; $i++) {\n    process($i);\n}",
     "assertEquals(7, 7);"),
    ("code_generation", "beginner",
     "Write a loop that repeats a block exactly three times using while.",
     "<?php\n$count = 0;\nwhile ($count < 3) {\n    echo 'x';\n    $count++;\n}",
     "xxx",
     "The loop runs while count is below 3 and increments each time, printing x three times.",
     "Decrementing instead of incrementing the counter in a while loop.",
     None,
     "assertEquals('xxx', $out);"),
    ("code_generation", "advanced",
     "Write a loop that uses a for loop with multiple expressions in the header.",
     "<?php\nfor ($i = 0, $j = 10; $i < $j; $i++, $j--) {\n    echo \"$i-$j \";\n}",
     "0-10 1-9 2-8 3-7 4-6 ",
     "The for header supports comma-separated initializers and incrementors, so two counters move toward each other.",
     "Forgetting the comma in the increment part, which breaks the syntax.",
     None,
     "assertStringContainsString('0-10', $out);"),
]

LOOPS = LOOPS[:40]