# -*- coding: utf-8 -*-
"""Arrays & Strings (50)."""

ARRAYS_STRINGS = [
    ("code_generation", "beginner",
     "Write code that creates an indexed array of three colors and prints the second one.",
     "<?php\n$colors = ['red', 'green', 'blue'];\necho $colors[1];",
     "green",
     "Indexed arrays are zero-based, so index 1 is the second element.",
     "Using index 1 expecting the first element; the first is index 0.",
     None,
     "assertEquals('green', $colors[1]);"),
    ("code_generation", "beginner",
     "Write code that appends an element to an array and prints its count.",
     "<?php\n$nums = [1, 2];\n$nums[] = 3;\necho count($nums);",
     "3",
     "The empty bracket syntax appends to the end of the array, increasing its length.",
     "Using $nums[count($nums)+1] which creates a gap at the index.",
     None,
     "assertEquals(3, count($nums));"),
    ("predict_output", "intermediate",
     "What is printed? Show the keys of an associative array after implode.",
     "<?php\n$a = ['x' => 1, 'y' => 2];\necho implode(',', array_keys($a));",
     "x,y",
     "array_keys() returns the keys as an array, and implode() joins them with commas.",
     "Expecting the values (1,2) instead of the keys.",
     None,
     "assertEquals('x,y', implode(',', array_keys($a)));"),
    ("code_generation", "intermediate",
     "Write code that merges two arrays and removes duplicates.",
     "<?php\n$a = [1, 2, 3];\n$b = [3, 4, 5];\n$m = array_values(array_unique(array_merge($a, $b)));\nprint_r($m);",
     "[1,2,3,4,5]",
     "array_merge concatenates, array_unique removes duplicate values, and array_values reindexes.",
     "Forgetting array_values, which leaves holes in the numeric keys after deduplication.",
     None,
     "assertEquals([1,2,3,4,5], $m);"),
    ("code_explanation", "beginner",
     "Explain the difference between these two array declarations.",
     "<?php\n$a = ['x']; $b = ['x' => null];\nvar_dump(isset($a[0]), isset($b['x']));",
     "bool(true)\nbool(false)",
     "A list element with value 'x' is set; a key explicitly assigned null is treated as unset by isset().",
     "Assuming isset() is true whenever a key exists, even if its value is null.",
     None,
     "assertFalse(isset($b['x']));"),
    ("code_generation", "intermediate",
     "Write code that sorts an associative array by value while preserving keys.",
     "<?php\n$a = ['b' => 2, 'a' => 1];\nasort($a);\nprint_r($a);",
     "Array ( [a] => 1 [b] => 2 )",
     "asort() sorts by value ascending and keeps the key association.",
     "Using sort(), which discards the keys and reindexes numerically.",
     None,
     "assertEquals(['a'=>1,'b'=>2], $a);"),
    ("predict_output", "intermediate",
     "What is printed by this string function chain?",
     "<?php\n$s = '  Hello  ';\necho strlen(trim($s));",
     "5",
     "trim() removes surrounding whitespace, leaving 'Hello' which has length 5.",
     "Counting the spaces before trimming, which would give 9.",
     None,
     "assertEquals(5, strlen(trim('  Hello  ')));"),
    ("code_generation", "intermediate",
     "Write code that replaces all occurrences of a substring in a string.",
     "<?php\necho str_replace('a', 'o', 'banana');",
     "bonono",
     "str_replace() replaces every occurrence of the search string with the replacement.",
     "Using strstr() which only searches rather than replacing.",
     None,
     "assertEquals('bonono', str_replace('a', 'o', 'banana'));"),
    ("find_bug", "intermediate",
     "This should find 'World' in the string but reports not found. Find the bug.",
     "<?php\n$pos = strpos('Hello World', 'World');\nif ($pos) {\n    echo 'found';\n} else {\n    echo 'not found';\n}",
     "found (by luck)",
     "The real bug appears when the needle is at position 0: strpos returns 0 which is falsy, so the check fails. Compare with !== false.",
     "Using a truthy check on strpos() instead of comparing with !== false.",
     "<?php\n$pos = strpos('Hello World', 'World');\nif ($pos !== false) {\n    echo 'found';\n}",
     "assertNotFalse(strpos('Hello World', 'World'));"),
    ("code_generation", "advanced",
     "Write code that uses array_map and array_filter together to double only the even numbers.",
     "<?php\n$nums = [1,2,3,4];\n$even = array_filter($nums, fn($n) => $n % 2 === 0);\n$doubled = array_map(fn($n) => $n * 2, $even);\nprint_r(array_values($doubled));",
     "[4,8]",
     "array_filter keeps the evens and array_map doubles them; array_values reindexes the filtered result.",
     "Forgetting that array_filter preserves original keys, so the output is not a clean list.",
     None,
     "assertEquals([4,8], array_values($doubled));"),
    ("code_generation", "beginner",
     "Write code that uppercases a string and prints it.",
     "<?php\necho strtoupper('hello');",
     "HELLO",
     "strtoupper() returns the string with all ASCII letters converted to uppercase.",
     "Using ucfirst() which only capitalizes the first character.",
     None,
     "assertEquals('HELLO', strtoupper('hello'));"),
    ("predict_output", "advanced",
     "What is printed by array_slice here? Note the resulting keys.",
     "<?php\nprint_r(array_slice([1,2,3,4,5], 1, 2));",
     "Array ( [0] => 2 [1] => 3 )",
     "array_slice() returns a portion starting at offset 1 with length 2, reindexing the result by default.",
     "Expecting the keys [1,2] to be preserved; numeric slice keys are reset unless preserve_keys is true.",
     None,
     "assertEquals([2,3], array_slice([1,2,3,4,5], 1, 2));"),
    ("code_generation", "intermediate",
     "Write code that splits a comma-separated string into an array.",
     "<?php\n$parts = explode(',', 'a,b,c');\nprint_r($parts);",
     "[a,b,c]",
     "explode() breaks the string on the given delimiter and returns an array.",
     "Swapping arguments and using implode() by mistake.",
     None,
     "assertEquals(['a','b','c'], explode(',', 'a,b,c'));"),
    ("code_generation", "intermediate",
     "Write code that joins array elements with a separator.",
     "<?php\necho implode(' | ', ['a', 'b', 'c']);",
     "a | b | c",
     "implode() concatenates the array elements inserting the glue string between them.",
     "Using explode() (the inverse) when joining is needed.",
     None,
     "assertEquals('a | b | c', implode(' | ', ['a','b','c']));"),
    ("find_bug", "advanced",
     "This should remove a key from an array but leaves a hole. Find the bug.",
     "<?php\n$user = ['id' => 1, 'name' => 'Ada'];\nunset($user['name']);\necho json_encode($user);",
     "{\"id\":1}",
     "There is actually no visible bug here; unset removes the key cleanly. Holes appear only for numeric lists, where array_values is needed to reindex.",
     "Unsetting a numeric-list element without reindexing, leaving a non-sequential list.",
     "<?php\n$list = [1,2,3];\nunset($list[1]);\n$list = array_values($list);\nprint_r($list);",
     "assertEquals([1,3], array_values([0=>1, 2=>3]));"),
    ("code_explanation", "intermediate",
     "Explain what array_column does here.",
     "<?php\n$rows = [['id'=>1,'n'=>'a'], ['id'=>2,'n'=>'b']];\nprint_r(array_column($rows, 'n'));",
     "Array ( [0] => a [1] => b )",
     "array_column() extracts the values of a single column from a list of rows.",
     "Using array_map manually when array_column is a direct fit.",
     None,
     "assertEquals(['a','b'], array_column($rows, 'n'));"),
    ("code_generation", "advanced",
     "Write code that uses array_combine to build a map from two arrays.",
     "<?php\n$keys = ['a','b'];\n$vals = [1,2];\nprint_r(array_combine($keys, $vals));",
     "Array ( [a] => 1 [b] => 2 )",
     "array_combine pairs the first array as keys with the second as values.",
     "Passing arrays of different lengths, which throws a ValueError in PHP 8.",
     None,
     "assertEquals(['a'=>1,'b'=>2], array_combine($keys, $vals));"),
    ("predict_output", "beginner",
     "What is printed when a string is reversed?",
     "<?php\necho strrev('abc');",
     "cba",
     "strrev() reverses the order of characters in the string.",
     "Expecting strrev on an array; it works on strings only.",
     None,
     "assertEquals('cba', strrev('abc'));"),
    ("code_generation", "intermediate",
     "Write code that pads a string to a fixed length on the left.",
     "<?php\necho str_pad('5', 3, '0', STR_PAD_LEFT);",
     "005",
     "str_pad() adds the pad string on the specified side until the total length is reached.",
     "Using STR_PAD_RIGHT when left padding is required.",
     None,
     "assertEquals('005', str_pad('5', 3, '0', STR_PAD_LEFT));"),
    ("code_generation", "intermediate",
     "Write code that finds the first array element matching a condition with a loop and break.",
     "<?php\n$users = [['age'=>15], ['age'=>22]];\nforeach ($users as $u) {\n    if ($u['age'] >= 18) {\n        echo $u['age'];\n        break;\n    }\n}",
     "22",
     "The loop scans until the predicate holds, then breaks with the first match.",
     "Iterating the whole array and printing all matches instead of the first.",
     None,
     "assertEquals(22, $out);"),
    ("code_generation", "advanced",
     "Write code that uses array_search to find the key of a value.",
     "<?php\n$k = array_search('b', ['a', 'b', 'c']);\nvar_dump($k);",
     "int(1)",
     "array_search() returns the key of the first matching value or false when not found.",
     "Using the result in a truthy check, which fails when the key is 0.",
     None,
     "assertEquals(1, array_search('b', ['a','b','c']));"),
    ("find_bug", "intermediate",
     "This should sum the values of a nested array but fails. Find the bug.",
     "<?php\n$data = [[1,2],[3,4]];\necho array_sum($data);",
     "0 with a warning",
     "array_sum() expects a flat array of numbers; nested arrays are not summed and cause a warning, so you must flatten first.",
     "Assuming array_sum() recurses into nested arrays.",
     "<?php\n$data = [[1,2],[3,4]];\necho array_sum(array_merge(...$data));",
     "assertEquals(10, array_sum(array_merge(...$data)));"),
    ("code_generation", "beginner",
     "Write code that checks if a key exists in an array using array_key_exists.",
     "<?php\n$a = ['x' => null];\nvar_dump(array_key_exists('x', $a));",
     "bool(true)",
     "array_key_exists() returns true even when the value is null, unlike isset().",
     "Using isset() when a null value must still count as existing.",
     None,
     "assertTrue(array_key_exists('x', ['x'=>null]));"),
    ("code_explanation", "advanced",
     "Explain the difference between array_map and array_walk here.",
     "<?php\n$a = [1,2];\n$b = array_map(fn($n)=>$n*2, $a);\narray_walk($a, function(&$n){ $n*=2; });\nprint_r([$a, $b]);",
     "[[2,4],[2,4]]",
     "array_map returns a new array without touching the original; array_walk mutates the original in place when the callback takes a reference.",
     "Expecting array_map to modify the original array.",
     None,
     "assertEquals([2,4], array_map(fn($n)=>$n*2, [1,2]));"),
    ("code_generation", "intermediate",
     "Write code that trims and lowercases user input in one chain.",
     "<?php\n$raw = '  HeLLo ';\necho strtolower(trim($raw));",
     "hello",
     "Chaining trim() then strtolower() normalizes whitespace and case.",
     "Applying strtolower before trimming, which is harmless but the canonical order is trim first.",
     None,
     "assertEquals('hello', strtolower(trim('  HeLLo ')));"),
    ("predict_output", "intermediate",
     "What does this print?",
     "<?php\n$x = [1, 2, 3];\necho array_sum($x), ':', count($x);",
     "6:3",
     "array_sum gives 6 and count gives 3, joined by a colon.",
     "Mixing up sum and count in the output order.",
     None,
     "assertEquals('6:3', $out);"),
    ("code_generation", "advanced",
     "Write code that groups array items by a computed key.",
     "<?php\n$nums = [1,2,3,4];\n$g = [];\nforeach ($nums as $n) {\n    $g[$n % 2 === 0 ? 'even' : 'odd'][] = $n;\n}\nprint_r($g['even']);",
     "Array ( [0] => 2 [1] => 4 )",
     "The loop appends each element to a bucket chosen by the parity key.",
     "Overwriting the bucket with = instead of appending with []=, losing earlier items.",
     None,
     "assertEquals([2,4], $g['even']);"),
    ("code_generation", "beginner",
     "Write code that converts a string to an array of words.",
     "<?php\nprint_r(explode(' ', 'the quick brown'));",
     "Array ( [0] => the [1] => quick [2] => brown )",
     "explode() with a space delimiter splits the sentence into words.",
     "Using str_split, which splits into individual characters.",
     None,
     "assertEquals(['the','quick','brown'], explode(' ', 'the quick brown'));"),
    ("code_generation", "intermediate",
     "Write code that checks whether an array contains a given value.",
     "<?php\n$has = in_array('b', ['a','b'], true);\nvar_dump($has);",
     "bool(true)",
     "in_array() with the third argument true uses strict comparison, avoiding type-juggling surprises.",
     "Omitting the strict flag, so '0' and 0 match unexpectedly.",
     None,
     "assertTrue(in_array('b', ['a','b'], true));"),
    ("find_bug", "advanced",
     "This should sort numbers ascending but gives the wrong order. Find the bug.",
     "<?php\n$a = [10, 2, 33];\nsort($a);\nprint_r($a);",
     "[2,10,33]",
     "There is no bug for integers; pure numeric sort is correct. The classic bug is sorting numeric strings, where sort() compares them lexicographically.",
     "Sorting numeric strings without a numeric comparison flag.",
     "<?php\n$a = ['10','2','33'];\nsort($a, SORT_NUMERIC);\nprint_r($a);",
     "assertEquals([10,2,33], [10,2,33]);"),
    ("code_generation", "intermediate",
     "Write code that removes the last element of an array and returns it.",
     "<?php\n$a = [1,2,3];\n$last = array_pop($a);\necho $last, '/', count($a);",
     "3/2",
     "array_pop() removes and returns the last element, reducing the array size by one.",
     "Using array_shift() which removes the first element instead.",
     None,
     "assertEquals('3/2', $out);"),
    ("predict_output", "advanced",
     "What is printed by this array comparison of string and int keys?",
     "<?php\n$a = [1 => 'x'];\n$b = ['1' => 'x'];\nvar_dump($a == $b);",
     "bool(true)",
     "PHP normalizes integer-like string keys to integers, so '1' and 1 are the same key.",
     "Assuming '1' and 1 remain distinct keys; PHP casts numeric string keys to int.",
     None,
     "assertTrue([1=>'x'] == ['1'=>'x']);"),
    ("code_generation", "advanced",
     "Write code that sorts an array of arrays by a nested key.",
     "<?php\n$rows = [['n'=>3], ['n'=>1], ['n'=>2]];\nusort($rows, fn($a,$b) => $a['n'] <=> $b['n']);\nprint_r(array_column($rows, 'n'));",
     "[1,2,3]",
     "usort() with a spaceship comparator orders the rows by the nested field.",
     "Comparing entire arrays instead of the specific nested key.",
     None,
     "assertEquals([1,2,3], array_column($rows, 'n'));"),
    ("code_explanation", "beginner",
     "Explain what these string functions return.",
     "<?php\nvar_dump(strlen('hi'));\nvar_dump(str_word_count('hi there'));",
     "int(2)\nint(2)",
     "strlen counts characters, str_word_count counts words; both return 2 here coincidentally.",
     "Confusing character count with word count.",
     None,
     "assertEquals(2, str_word_count('hi there'));"),
    ("code_generation", "intermediate",
     "Write code that flattens a two-dimensional array into one level.",
     "<?php\n$m = [[1,2],[3],[4,5]];\nprint_r(array_merge(...$m));",
     "[1,2,3,4,5]",
     "The spread operator unpacks the sub-arrays as separate arguments to array_merge, concatenating them.",
     "Passing the array directly to array_merge without spreading, which merges keys instead of flattening.",
     None,
     "assertEquals([1,2,3,4,5], array_merge(...$m));"),
    ("code_generation", "beginner",
     "Write code that gets the first and last elements of an array.",
     "<?php\n$a = [10,20,30];\necho $a[0], '/', $a[count($a)-1];",
     "10/30",
     "Index 0 is the first element and count()-1 is the last for a list.",
     "Using count($a) as the last index, which is out of bounds.",
     None,
     "assertEquals('10/30', $out);"),
    ("find_bug", "intermediate",
     "This should compare two strings case-insensitively but fails. Find the bug.",
     "<?php\nvar_dump('Hello' == 'hello');",
     "bool(false)",
     "The == operator on strings is case-sensitive; use strcasecmp for case-insensitive comparison.",
     "Assuming == ignores case for strings.",
     "<?php\nvar_dump(strcasecmp('Hello', 'hello') === 0);",
     "assertEquals(0, strcasecmp('Hello', 'hello'));"),
    ("code_generation", "advanced",
     "Write code that uses array_reduce to count word frequencies.",
     "<?php\n$freq = array_reduce(explode(' ', 'a b a'), function($c, $w) {\n    $c[$w] = ($c[$w] ?? 0) + 1;\n    return $c;\n}, []);\nprint_r($freq);",
     "Array ( [a] => 2 [b] => 1 )",
     "array_reduce folds the words into a frequency map, initializing missing counts with the null coalescing operator.",
     "Forgetting the initial carry value [], which makes the first iteration undefined.",
     None,
     "assertEquals(['a'=>2,'b'=>1], $freq);"),
    ("predict_output", "intermediate",
     "What is printed after list destructuring assigns both variables?",
     "<?php\n$a = ['x','y'];\n[$first, $second] = $a;\necho $second;",
     "y",
     "List destructuring assigns the array elements to $first and $second in order.",
     "Expecting $second to be the first element.",
     None,
     "assertEquals('y', $second);"),
    ("code_generation", "intermediate",
     "Write code that reverses an array without using array_reverse.",
     "<?php\n$a = [1,2,3];\n$r = [];\nfor ($i = count($a)-1; $i >= 0; $i--) {\n    $r[] = $a[$i];\n}\nprint_r($r);",
     "[3,2,1]",
     "Iterating from the last index down to 0 and appending builds the reversed list.",
     "Off-by-one when starting at count($a) instead of count($a)-1.",
     None,
     "assertEquals([3,2,1], $r);"),
    ("code_generation", "beginner",
     "Write code that extracts a substring from the middle of a string.",
     "<?php\necho substr('abcdef', 2, 3);",
     "cde",
     "substr() starts at offset 2 (c) and returns 3 characters: c, d, e.",
     "Confusing the second argument as the end index; it is the length.",
     None,
     "assertEquals('cde', substr('abcdef', 2, 3));"),
    ("code_explanation", "intermediate",
     "Explain how array_fill works here.",
     "<?php\nprint_r(array_fill(0, 3, 'x'));",
     "Array ( [0] => x [1] => x [2] => x )",
     "array_fill() creates an array with a start index, a count, and the value to repeat.",
     "Passing the count first and the start index second, reversing the arguments.",
     None,
     "assertEquals(['x','x','x'], array_fill(0,3,'x'));"),
    ("code_generation", "advanced",
     "Write code that checks if all elements of an array pass a predicate.",
     "<?php\n$nums = [2,4,6];\n$allEven = !in_array(false, array_map(fn($n)=>$n%2===0, $nums), true);\nvar_dump($allEven);",
     "bool(true)",
     "Mapping each element to a boolean and checking for any false determines if all passed.",
     "Using array_sum on booleans and misreading the result.",
     None,
     "assertTrue($allEven);"),
    ("predict_output", "advanced",
     "What is printed? Explain the key assigned after appending to an array with an explicit key.",
     "<?php\n$a = [3 => 'x'];\n$a[] = 'y';\necho implode(',', array_keys($a));",
     "3,4",
     "Appending after an explicit key continues from the highest numeric key, so the new element gets key 4.",
     "Expecting the new element to get key 0; PHP continues from the largest integer key.",
     None,
     "assertEquals('3,4', implode(',', array_keys($a)));"),
    ("code_generation", "intermediate",
     "Write code that finds the longest word in a sentence.",
     "<?php\n$words = explode(' ', 'a bb ccc');\nusort($words, fn($a,$b) => strlen($b) <=> strlen($a));\necho $words[0];",
     "ccc",
     "Sorting by descending length puts the longest word first; the spaceship of negated lengths gives that order.",
     "Sorting ascending and then taking the first element, which yields the shortest.",
     None,
     "assertEquals('ccc', $words[0]);"),
    ("code_generation", "beginner",
     "Write code that checks if a string starts with a given prefix.",
     "<?php\nvar_dump(str_starts_with('http://x', 'http'));",
     "bool(true)",
     "str_starts_with() (PHP 8) returns whether the string begins with the prefix.",
     "Using strpos with a truthy check, which fails when the prefix is at position 0.",
     None,
     "assertTrue(str_starts_with('http://x', 'http'));"),
    ("find_bug", "advanced",
     "This should merge two arrays without overwriting keys but does. Find the bug.",
     "<?php\n$a = ['k' => 1];\n$b = ['k' => 2];\nprint_r(array_merge($a, $b));",
     "Array ( [k] => 2 )",
     "array_merge overwrites string keys with later values; to keep both, use array_merge_recursive or the + operator depending on intent.",
     "Expecting array_merge to preserve both string-keyed values.",
     "<?php\n$a = ['k' => 1];\n$b = ['k' => 2];\nprint_r(array_merge_recursive($a, $b));",
     "assertEquals(['k'=>[1,2]], array_merge_recursive($a, $b));"),
    ("code_explanation", "advanced",
     "Explain the union operator on arrays.",
     "<?php\n$a = ['x' => 1];\n$b = ['x' => 2, 'y' => 3];\nprint_r($a + $b);",
     "Array ( [x] => 1 [y] => 3 )",
     "The + operator keeps the left operand's keys and adds only keys not already present from the right.",
     "Expecting + to overwrite with the right-hand value for duplicate keys.",
     None,
     "assertEquals(['x'=>1,'y'=>3], $a + $b);"),
    ("code_generation", "intermediate",
     "Write code that counts occurrences of a value in an array.",
     "<?php\n$c = count(array_keys([1,2,1,1], 1));\necho $c;",
     "3",
     "array_keys with a search value returns the keys of matching elements, and count tallies them.",
     "Using array_count_values which returns a map rather than a single count.",
     None,
     "assertEquals(3, count(array_keys([1,2,1,1], 1)));"),
    ("predict_output", "beginner",
     "What is printed when iterating an associative array with key and value?",
     "<?php\n$a = ['k' => 'v'];\nforeach ($a as $k => $v) {\n    echo \"$k=$v\";\n}",
     "k=v",
     "Iterating an associative array yields the single key/value pair, printed as k=v.",
     "Expecting the loop to print numeric indices instead of the string key.",
     None,
     "assertEquals('k=v', $out);"),
    ("code_generation", "advanced",
     "Write code that chunks an array into groups of two.",
     "<?php\nprint_r(array_chunk([1,2,3,4,5], 2));",
     "[[1,2],[3,4],[5]]",
     "array_chunk() splits the array into sub-arrays of the given size, with a smaller final chunk when needed.",
     "Expecting all chunks to have equal size when the length is not a multiple.",
     None,
     "assertEquals([[1,2],[3,4],[5]], array_chunk([1,2,3,4,5], 2));"),
    ("code_generation", "intermediate",
     "Write code that removes empty strings from an array.",
     "<?php\n$in = ['a', '', 'b'];\n$out = array_values(array_filter($in, fn($s) => $s !== ''));\nprint_r($out);",
     "[a,b]",
     "array_filter removes the empty strings and array_values reindexes the result.",
     "Using array_filter alone, which preserves the original keys and leaves a gap.",
     None,
     "assertEquals(['a','b'], $out);"),
    ("code_explanation", "beginner",
     "Explain what nl2br does.",
     "<?php\necho nl2br(\"a\\nb\");",
     "a<br />b (plus a newline)",
     "nl2br() inserts HTML line breaks before newlines so text displays with breaks in HTML.",
     "Using nl2br for non-HTML output where it would introduce literal <br> tags.",
     None,
     "assertStringContainsString('<br', nl2br(\"a\\nb\"));"),
]

ARRAYS_STRINGS = ARRAYS_STRINGS[:50]