# -*- coding: utf-8 -*-
"""Variables & Data Types (40). Tuple order:
(task_type, difficulty, prompt, code, expected_output, explanation,
 common_mistake, corrected_code, test_case)"""

VARIABLES = [
    ("code_generation", "beginner",
     "Declare a variable holding your age as an integer and print its type with gettype().",
     '<?php\n$age = 30;\necho gettype($age);',
     "integer",
     "Assigning a whole number without quotes stores an int; gettype() reports the runtime type name.",
     "Quoting the number ('30') makes it a string, so gettype() would print string.",
     None,
     "assertEquals('integer', gettype(30));"),
    ("predict_output", "beginner",
     "What type and value does $x hold after this line?",
     "<?php\n$x = 3.14;\nvar_dump($x);",
     "float(3.14)",
     "A number with a decimal point is stored as a float, and var_dump() shows type and value.",
     "Expecting an integer because the value happens to be small.",
     None,
     "assertIsFloat(3.14);"),
    ("code_generation", "beginner",
     "Write code that stores a boolean and prints its string representation.",
     "<?php\n$isActive = true;\nvar_export($isActive);",
     "true",
     "var_export() prints a PHP-representation of the value, so a boolean prints as true or false.",
     "Using echo on a boolean, which prints 1 for true and an empty string for false.",
     None,
     "assertEquals('true', var_export(true, true));"),
    ("code_explanation", "intermediate",
     "Explain what happens to $value after this cast.",
     "<?php\n$value = (int) \"42abc\";\nvar_dump($value);",
     "int(42)",
     "A string cast to int parses the leading numeric part and discards the trailing non-numeric characters.",
     "Expecting a TypeError or a value of 0 because the string is not fully numeric.",
     None,
     "assertEquals(42, (int) '42abc');"),
    ("predict_output", "intermediate",
     "What is printed after adding two numeric strings?",
     '<?php\n$s = "10" + "20";\necho gettype($s), ":";\necho $s;',
     "integer:30",
     "Both numeric strings are coerced to integers for the addition, yielding an int of 30.",
     "Thinking the result stays a string because both operands were strings.",
     None,
     "assertEquals(30, '10' + '20');"),
    ("code_generation", "intermediate",
     "Write code that converts a numeric string to an integer safely using filter_var.",
     "<?php\n$raw = \"42\";\n$n = filter_var($raw, FILTER_VALIDATE_INT);\nvar_dump($n);",
     "int(42)",
     "FILTER_VALIDATE_INT returns the integer for a valid numeric string, or false when invalid.",
     "Casting with (int) which silently accepts partial values like '42abc'.",
     None,
     "assertEquals(42, filter_var('42', FILTER_VALIDATE_INT));"),
    ("code_explanation", "beginner",
     "Explain the difference between the two variables.",
     "<?php\n$a = null;\n$b = \"\";\nvar_dump(isset($a), isset($b));",
     "bool(false)\nbool(true)",
     "null is treated as unset by isset(), while an empty string is set and therefore true.",
     "Assuming isset() returns false for any empty value including ''.",
     None,
     "assertFalse(isset($a)); assertTrue(isset($b));"),
    ("find_bug", "intermediate",
     "Find the bug: this should output 10.50 but prints something else.",
     '<?php\n$price = "10.50";\n$qty = 1;\necho $price * $qty;',
     "10.5",
     "It actually works because the numeric string is coerced. If the intent is to preserve two decimals, multiplication yields a float 10.5, not the formatted 10.50.",
     "Expecting arithmetic to preserve the original string formatting such as trailing zeros.",
     '<?php\n$price = "10.50";\necho number_format((float)$price, 2);',
     "assertEquals('10.50', number_format((float)'10.50', 2));"),
    ("code_generation", "intermediate",
     "Write code that shows constant interpolation is not possible and use a variable instead.",
     "<?php\ndefine('VERSION', '1.0');\n$v = VERSION;\necho \"Version $v\";",
     "Version 1.0",
     "Constants cannot be interpolated inside a double-quoted string, so assign to a variable first or concatenate.",
     "Trying \"Version VERSION\" expecting the constant to expand.",
     None,
     "assertEquals('Version 1.0', \"Version {${'v'}}\" === '' ? 'x' : \"Version $v\");"),
    ("code_generation", "beginner",
     "Write code that demonstrates variable variables.",
     "<?php\n$name = 'color';\n$color = 'blue';\necho $$name;",
     "blue",
     "A variable variable $$name uses the value of $name ('color') as the name of another variable.",
     "Confusing shadowed names and creating hard-to-read code; use arrays instead.",
     None,
     "$$name; assertEquals('blue', $color);"),
    ("code_explanation", "intermediate",
     "Explain why this comparison is true.",
     "<?php\nvar_dump(\"0\" == false);",
     "bool(true)",
     "In PHP 8, comparing a numeric string with a boolean converts the string to a number, and '0' becomes 0 which equals false.",
     "Assuming PHP 8 changed this comparison; it still yields true for the numeric string '0'.",
     None,
     "assertTrue('0' == false);"),
    ("predict_output", "advanced",
     "What does this print? Compare the non-numeric string with the integer zero.",
     "<?php\nvar_dump(\"abc\" == 0);",
     "bool(false)",
     "In PHP 8, comparing a non-numeric string with an integer no longer coerces the number to a string; the comparison is false.",
     "Relying on PHP 7 behavior where 'abc' == 0 was true.",
     None,
     "assertFalse('abc' == 0);"),
    ("code_generation", "intermediate",
     "Write code that reads an environment variable with a default using getenv.",
     "<?php\n$debug = getenv('APP_DEBUG') ?: 'false';\necho $debug;",
     "false (by default)",
     "getenv() returns the environment value or false when unset; the elvis operator supplies a default for falsy results.",
     "Using ?? with getenv(); getenv returns false, not null, so elvis ?: is the right choice.",
     None,
     "assertEquals('false', getenv('NOPE_MISSING') ?: 'false');"),
    ("find_bug", "beginner",
     "This should print the full name but prints only the first name. Find the bug.",
     "<?php\n$first = \"Ada\";\n$last = \"Lovelace\";\n$full = \"$first, $last\";\necho $full;",
     "Ada, Lovelace",
     "There is actually no bug; interpolation works and prints the full name with a comma.",
     "Assuming interpolation fails with two variables in one string; it does not.",
     None,
     "assertEquals('Ada, Lovelace', $full);"),
    ("code_explanation", "advanced",
     "Explain the reference behavior in this code.",
     "<?php\n$x = 1;\n$y = $x;\n$x = 2;\necho \"$x $y\";",
     "2 1",
     "Normal assignment copies the value, so changing $x afterwards does not affect $y.",
     "Expecting $y to follow $x because of a remembered reference from an earlier snippet.",
     None,
     "assertEquals('2 1', \"$x $y\");"),
    ("code_generation", "intermediate",
     "Write code that defines a typed class property and shows a TypeError when assigning the wrong type.",
     "<?php\nclass Cart {\n    public int $items = 0;\n}\n$c = new Cart();\n$c->items = \"many\";",
     "TypeError: Cannot assign string to property Cart::$items of type int",
     "A typed property enforces its declared type on assignment and throws a TypeError for mismatches.",
     "Relying on implicit coercion for typed properties; PHP throws instead of casting.",
     None,
     "$c->items = 3; assertEquals(3, $c->items);"),
    ("predict_output", "beginner",
     "What is the output?",
     "<?php\n$a = 5;\n$a += 2;\necho $a;",
     "7",
     "The += compound assignment adds the right operand to the current value of $a.",
     "Reading += as a plain assignment that replaces the value with 2.",
     None,
     "assertEquals(7, 5 + 2);"),
    ("code_generation", "advanced",
     "Write code that demonstrates a readonly property.",
     "<?php\nclass Point {\n    public function __construct(public readonly int $x) {}\n}\n$p = new Point(5);\necho $p->x;",
     "5",
     "A readonly property can be initialized once and cannot be modified afterwards.",
     "Trying to modify a readonly property after construction, which throws an Error.",
     None,
     "assertEquals(5, (new Point(5))->x);"),
    ("code_explanation", "beginner",
     "Explain what the global keyword does here.",
     "<?php\n$count = 0;\nfunction inc() {\n    global $count;\n    $count++;\n}\ninc();\necho $count;",
     "1",
     "Without global, the function would use a local $count; the global keyword binds the function scope to the file-level variable.",
     "Forgetting global and wondering why the outer variable never changes.",
     None,
     "assertEquals(1, $count);"),
    ("code_review", "intermediate",
     "Review this code that relies on dynamic typing; suggest a safer approach.",
     "<?php\nfunction total($items) {\n    return array_sum($items);\n}",
     "$items must be an array",
     "Adding parameter and return types (array and int/float) makes intent explicit and fails fast on misuse.",
     "Leaving parameters untyped so wrong argument types cause subtle runtime bugs.",
     "<?php\nfunction total(array $items): int|float {\n    return array_sum($items);\n}",
     "assertEquals(6, total([1,2,3]));"),
    ("predict_output", "intermediate",
     "What does this print? Consider what compound assignment does to the type.",
     "<?php\n$x = \"5\";\n$x += 3;\necho gettype($x);",
     "integer",
     "The += with an integer operand causes numeric coercion, turning the string into an int.",
     "Expecting the result to remain a string after numeric compound assignment.",
     None,
     "assertEquals('integer', gettype('5' + 3));"),
    ("code_generation", "beginner",
     "Write code that swaps a variable to null using unset and checks isset after.",
     "<?php\n$v = 10;\nunset($v);\nvar_dump(isset($v));",
     "bool(false)",
     "unset() removes the variable from scope, and isset() on a removed variable returns false.",
     "Expecting the variable to be null rather than undefined after unset().",
     None,
     "assertFalse(isset($v));"),
    ("code_explanation", "intermediate",
     "Explain the difference between == and === for these arrays.",
     "<?php\n$a = [1, 2, 3];\n$b = ['0' => 1, '1' => 2, '2' => 3];\nvar_dump($a == $b);\nvar_dump($a === $b);",
     "bool(true)\nbool(false)",
     "Loose equality compares key/value pairs regardless of order and type; strict equality also requires the same order and types.",
     "Assuming array order never matters for equality; strict comparison cares about order and key types.",
     None,
     "assertTrue([1,2,3] == ['0'=>1,'1'=>2,'2'=>3]);"),
    ("find_bug", "intermediate",
     "This should keep a running total but always starts at 1. Find the bug.",
     "<?php\n$total = 0;\nforeach ([1,2,3] as $n) {\n    $total = 1;\n    $total += $n;\n}\necho $total;",
     "4",
     "The line $total = 1 resets the accumulator on every iteration instead of using += only.",
     "Resetting the accumulator inside the loop instead of accumulating.",
     "<?php\n$total = 0;\nforeach ([1,2,3] as $n) {\n    $total += $n;\n}\necho $total;",
     "assertEquals(6, $total);"),
    ("code_generation", "intermediate",
     "Write code that uses a typed variable and the integer range constants.",
     "<?php\n$big = PHP_INT_MAX;\nvar_dump(is_int($big));\nvar_dump($big + 1);",
     "bool(true)\nfloat",
     "Adding 1 to PHP_INT_MAX overflows to a float because PHP promotes an out-of-range integer to float.",
     "Expecting integer overflow to wrap around as in C.",
     None,
     "assertIsFloat(PHP_INT_MAX + 1);"),
    ("code_explanation", "beginner",
     "Explain the type of $result.",
     "<?php\n$result = \"3\" . 4;\necho gettype($result), $result;",
     "string34",
     "The dot operator concatenates and always yields a string, converting the integer 4 to '4'.",
     "Expecting arithmetic because one operand is numeric; the dot is concatenation, not addition.",
     None,
     "assertEquals('34', '3' . 4);"),
    ("code_generation", "advanced",
     "Write code that uses a nullable typed parameter and returns a value or null.",
     "<?php\nfunction upper(?string $s): ?string {\n    return $s === null ? null : strtoupper($s);\n}\nvar_dump(upper(null));\nvar_dump(upper('hi'));",
     "NULL\nstring(2) \"HI\"",
     "The nullable type ?string accepts both string and null; the function returns null for null input.",
     "Passing null to a non-nullable string parameter, which throws a TypeError under strict types.",
     None,
     "assertNull(upper(null)); assertEquals('HI', upper('hi'));"),
    ("predict_output", "advanced",
     "What is printed? Consider floating-point equality.",
     "<?php\nvar_dump(0.1 + 0.2 == 0.3);",
     "bool(false)",
     "Floating-point representation error makes 0.1+0.2 equal 0.30000000000000004, so the comparison is false.",
     "Believing decimal arithmetic is exact for floats.",
     None,
     "assertFalse(0.1 + 0.2 == 0.3);"),
    ("code_generation", "intermediate",
     "Write code that converts a boolean-ish string to a real boolean.",
     "<?php\n$s = \"false\";\n$b = filter_var($s, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);\nvar_dump($b);",
     "bool(false)",
     "FILTER_VALIDATE_BOOLEAN recognizes 'true', 'false', 'yes', 'no', '1', '0' and returns the proper boolean.",
     "Using (bool)$s which treats any non-empty string, including 'false', as true.",
     None,
     "assertFalse(filter_var('false', FILTER_VALIDATE_BOOLEAN));"),
    ("code_explanation", "intermediate",
     "Explain what clone does versus assigning an object.",
     "<?php\nclass Box { public $v = 1; }\n$a = new Box();\n$b = $a;\n$c = clone $a;\n$b->v = 2;\necho \"$a->v $c->v\";",
     "2 1",
     "Objects are handled by reference on assignment, so $b shares $a; clone makes an independent copy, so $c stays unchanged.",
     "Expecting assignment to copy an object like it copies an array.",
     None,
     "assertEquals(1, $c->v);"),
    ("code_generation", "beginner",
     "Write code that uses the modulo operator to check divisibility by 3.",
     "<?php\n$n = 9;\necho ($n % 3 === 0) ? 'divisible' : 'not divisible';",
     "divisible",
     "Modulo by 3 yields 0 exactly when the number is divisible by 3.",
     "Comparing with == by mistake and matching on type juggling.",
     None,
     "assertEquals('divisible', ($n = 9) % 3 === 0 ? 'divisible' : 'not divisible');"),
    ("find_bug", "advanced",
     "This should compute a percentage but produces an integer. Find the bug.",
     "<?php\n$part = 3;\n$whole = 4;\n$pct = (int) ($part / $whole) * 100;\necho $pct;",
     "0",
     "Casting (int)($part / $whole) truncates 0.75 to 0 before multiplying by 100.",
     "Casting to int before scaling up, which discards the fractional part.",
     "<?php\n$part = 3;\n$whole = 4;\n$pct = $part / $whole * 100;\necho $pct;",
     "assertEquals(75.0, 3 / 4 * 100);"),
    ("predict_output", "beginner",
     "What is printed? Examine the elvis operator with a falsy zero.",
     "<?php\n$n = 0;\n$n = $n ?: 5;\necho $n;",
     "5",
     "The elvis operator ?: returns the left operand if truthy, otherwise the right; 0 is falsy so 5 is returned.",
     "Confusing ?: (elvis) with ?? (null coalescing); elvis also replaces 0 and ''.",
     None,
     "assertEquals(5, 0 ?: 5);"),
    ("code_explanation", "beginner",
     "Explain what a reference assignment does here.",
     "<?php\n$arr = [1,2,3];\n$x = &$arr[0];\n$x = 99;\nprint_r($arr);",
     "Array ( [0] => 99 [1] => 2 [2] => 3 )",
     "Binding $x by reference to $arr[0] means writing through $x updates the array element.",
     "Assuming $x is a plain copy of the element.",
     None,
     "assertEquals(99, $arr[0]);"),
    ("code_generation", "intermediate",
     "Write code that demonstrates the difference between == and === with numeric strings.",
     "<?php\n$a = \"01\";\n$b = 1;\nvar_dump($a == $b);\nvar_dump($a === $b);",
     "bool(true)\nbool(false)",
     "Loose comparison treats the numeric string '01' as 1, while strict comparison distinguishes string from int.",
     "Assuming leading zeros change loose comparison; '01' still equals 1 loosely.",
     None,
     "assertTrue('01' == 1); assertFalse('01' === 1);"),
    ("code_review", "beginner",
     "Review this variable naming and suggest improvements.",
     "<?php\n$x = 90;\n$y = 100;\n$z = $x / $y * 100;",
     "90.0",
     "Short names like $x and $y hide meaning; descriptive names such as $score and $maxScore improve readability.",
     "Using single-letter variables for domain values, making the code hard to follow.",
     "<?php\n$score = 90;\n$maxScore = 100;\n$percent = $score / $maxScore * 100;",
     "assertEquals(90.0, $percent);"),
    ("code_generation", "intermediate",
     "Write code that uses the null coalescing assignment operator.",
     "<?php\n$options = [];\n$options['theme'] ??= 'dark';\necho $options['theme'];",
     "dark",
     "The ??= operator assigns the right value only when the left key is null or missing.",
     "Using = which overwrites even when a value already exists.",
     None,
     "assertEquals('dark', $options['theme']);"),
    ("predict_output", "intermediate",
     "What does this print? Explain the result of comparing two numeric strings.",
     "<?php\n$a = '10';\n$b = '10.0';\nvar_dump($a == $b);",
     "bool(true)",
     "Both are numeric strings, so loose comparison compares them numerically and 10 equals 10.0.",
     "Expecting false because the strings differ textually.",
     None,
     "assertTrue('10' == '10.0');"),
    ("code_explanation", "advanced",
     "Explain the aliasing effect in this code.",
     "<?php\nfunction add(&$n) { $n++; }\n$x = 1;\nadd($x);\necho $x;",
     "2",
     "The parameter is passed by reference, so increments inside the function affect the caller's variable.",
     "Forgetting the & in the function signature and expecting the caller's value to change anyway.",
     None,
     "assertEquals(2, $x);"),
    ("code_generation", "beginner",
     "Write code that prints the memory size of an integer type using PHP_INT_SIZE.",
     "<?php\necho PHP_INT_SIZE;",
     "8 (on 64-bit)",
     "PHP_INT_SIZE is the size in bytes of an integer on the current platform.",
     "Assuming it always returns 4; that is only true on 32-bit builds.",
     None,
     "assertEquals(8, PHP_INT_SIZE);"),
    ("find_bug", "intermediate",
     "This should compare two version-ish numbers but misbehaves. Find the bug.",
     "<?php\n$a = \"1.10\";\n$b = \"1.9\";\nvar_dump($a > $b);",
     "bool(false)",
     "Because both are numeric strings, PHP compares them as floats: 1.10 < 1.9, which is the opposite of the intended version ordering.",
     "Comparing version strings numerically instead of using version_compare().",
     "<?php\n$a = \"1.10\";\n$b = \"1.9\";\nvar_dump(version_compare($a, $b, '>') === true);",
     "assertTrue(version_compare('1.10', '1.9', '>') > 0);"),
    ("code_generation", "advanced",
     "Write code that uses a backed enum and converts it from its backing value with from().",
     "<?php\nenum Level: int {\n    case Low = 1;\n    case High = 2;\n}\n$l = Level::from(2);\necho $l->name;",
     "High",
     "Enum::from() maps a matching backing value back to its case; name returns the case name.",
     "Using from() with an invalid value, which throws a ValueError; use tryFrom() to get null instead.",
     None,
     "assertEquals('High', Level::from(2)->name);"),
]

VARIABLES = VARIABLES[:40]