# -*- coding: utf-8 -*-
"""Forms & User Input (35)."""

FORMS_INPUT = [
    ("code_generation", "beginner",
     "Write code that reads a GET parameter 'name' safely with a default.",
     "<?php\n$name = $_GET['name'] ?? 'guest';\necho \"Hello, \" . htmlspecialchars($name, ENT_QUOTES);",
     "Hello, guest (or the provided name, escaped)",
     "The null coalescing operator supplies a default for a missing parameter, and htmlspecialchars escapes the value for output.",
     "Echoing $_GET['name'] directly, which enables reflected XSS.",
     None,
     "assertEquals('Hello, guest', 'Hello, ' . htmlspecialchars('guest'));"),
    ("code_generation", "beginner",
     "Write code that reads a POST field and trims it.",
     "<?php\n$email = trim($_POST['email'] ?? '');\necho $email;",
     "the trimmed email",
     "trim() removes surrounding whitespace from user input, and the default avoids an undefined-index warning.",
     "Using $_POST['email'] directly without a default or trimming.",
     None,
     "assertEquals('a@b.com', trim('  a@b.com '));"),
    ("code_explanation", "intermediate",
     "Explain why this validation is insufficient.",
     "<?php\nif (!empty($_POST['email'])) {\n    // assume valid\n}",
     "the code runs for any non-empty value",
     "empty() only checks presence, not format; an invalid string like 'not-an-email' passes.",
     "Treating a non-empty check as validation of correctness.",
     "<?php\nif (filter_var($_POST['email'] ?? '', FILTER_VALIDATE_EMAIL) !== false) {\n    // valid email\n}",
     "assertNotFalse(filter_var('a@b.com', FILTER_VALIDATE_EMAIL));"),
    ("find_bug", "intermediate",
     "This form handler always reports missing input. Find the bug.",
     "<?php\nif (isset($_GET['q'])) {\n    echo 'missing';\n}",
     "missing when q is absent; but wrong logic",
     "The logic is inverted: it prints 'missing' when the parameter IS set. The branches should be swapped.",
     "Inverting the meaning of isset() in the conditional.",
     "<?php\nif (!isset($_GET['q'])) {\n    echo 'missing';\n} else {\n    echo htmlspecialchars($_GET['q']);\n}",
     "assertTrue(isset(['q'=>'x']['q']));"),
    ("code_generation", "intermediate",
     "Write code that validates an integer from a form field and rejects non-integers.",
     "<?php\n$raw = $_POST['age'] ?? '';\n$age = filter_var($raw, FILTER_VALIDATE_INT);\nif ($age === false) {\n    echo 'invalid';\n} else {\n    echo $age;\n}",
     "the integer or 'invalid'",
     "FILTER_VALIDATE_INT returns the integer or false, distinguishing valid input from invalid without silent coercion.",
     "Using (int) which turns 'abc' into 0 instead of rejecting it.",
     None,
     "assertFalse(filter_var('abc', FILTER_VALIDATE_INT));"),
    ("code_generation", "beginner",
     "Write code that checks the request method before processing a form.",
     "<?php\nif ($_SERVER['REQUEST_METHOD'] === 'POST') {\n    echo 'handling post';\n} else {\n    echo 'show form';\n}",
     "handling post or show form",
     "Checking REQUEST_METHOD ensures the handler only runs for POST submissions, not direct GET access.",
     "Processing the form without checking the method, which allows unintended GET access.",
     None,
     "assertEquals('show form', ($_SERVER['REQUEST_METHOD'] ?? 'CLI') === 'POST' ? 'handling post' : 'show form');"),
    ("code_explanation", "intermediate",
     "Explain the risk of using the raw value in an SQL context.",
     "<?php\n$id = $_GET['id'];\n$sql = \"SELECT * FROM users WHERE id = $id\";",
     "SQL injection risk",
     "Concatenating user input into SQL allows injection; parameterized queries with PDO remove the risk.",
     "Believing that quotes around the value make the query safe.",
     "<?php\n$stmt = $pdo->prepare('SELECT * FROM users WHERE id = :id');\n$stmt->execute([':id' => $_GET['id']]);",
     "assertStringContainsString(':id', 'SELECT * FROM users WHERE id = :id');"),
    ("find_bug", "advanced",
     "This validation should reject empty names but accepts whitespace. Find the bug.",
     "<?php\n$name = $_POST['name'] ?? '';\nif ($name === '') {\n    echo 'required';\n}",
     "accepts '   '",
     "A string of spaces is not empty, so the check passes; trim before comparing to reject whitespace-only input.",
     "Comparing the raw value to '' without trimming whitespace first.",
     "<?php\n$name = trim($_POST['name'] ?? '');\nif ($name === '') {\n    echo 'required';\n}",
     "assertEquals('', trim('   '));"),
    ("code_generation", "intermediate",
     "Write code that outputs a text input value safely inside HTML.",
     "<?php\n$value = $_GET['q'] ?? '';\necho '<input value=\"' . htmlspecialchars($value, ENT_QUOTES) . '\">';",
     "<input value=\"...escaped...\">",
     "htmlspecialchars with ENT_QUOTES escapes both single and double quotes so the value cannot break out of the attribute.",
     "Using ENT_NOQUOTES, which leaves quotes unescaped and allows attribute injection.",
     None,
     "assertStringContainsString('&amp;', htmlspecialchars('a&b'));"),
    ("code_generation", "advanced",
     "Write code that validates a submitted URL and only allows http/https.",
     "<?php\n$url = $_POST['url'] ?? '';\nif (filter_var($url, FILTER_VALIDATE_URL) !== false\n    && in_array(parse_url($url, PHP_URL_SCHEME), ['http', 'https'], true)) {\n    echo 'ok';\n} else {\n    echo 'bad';\n}",
     "ok or bad",
     "Validating the URL and checking the scheme restricts input to safe protocols, blocking javascript: URIs.",
     "Relying on FILTER_VALIDATE_URL alone, which accepts non-http schemes.",
     None,
     "assertContains(parse_url('https://x.com', PHP_URL_SCHEME), ['http','https']);"),
    ("code_generation", "beginner",
     "Write code that reads a checkbox value and defaults to false when unchecked.",
     "<?php\n$subscribe = isset($_POST['subscribe']);\nvar_dump($subscribe);",
     "bool(true) if checked, bool(false) otherwise",
     "An unchecked checkbox is not submitted at all, so isset() correctly distinguishes checked from unchecked.",
     "Expecting $_POST['subscribe'] to be '0' when unchecked; it is simply absent.",
     None,
     "assertFalse(isset([]));"),
    ("code_explanation", "beginner",
     "Explain the difference between $_GET and $_POST.",
     "<?php\n$q = $_GET['q'] ?? '';\n$p = $_POST['p'] ?? '';",
     "GET values from the query string; POST from the request body",
     "GET data is visible in the URL and suitable for reads; POST data is sent in the body and used for writes.",
     "Using GET for sensitive data, which exposes it in URLs and logs.",
     None,
     "assertIsString($_GET['q'] ?? '');"),
    ("find_bug", "intermediate",
     "This should only allow 'red' or 'blue' but accepts anything. Find the bug.",
     "<?php\n$c = $_POST['color'] ?? '';\nif ($c != 'red' || $c != 'blue') {\n    echo 'invalid';\n}",
     "always prints invalid",
     "Using || makes the condition always true; it should be && to reject values that are neither red nor blue, or better, use in_array.",
     "Combining exclusions with || instead of &&.",
     "<?php\n$c = $_POST['color'] ?? '';\nif (!in_array($c, ['red', 'blue'], true)) {\n    echo 'invalid';\n}",
     "assertFalse(in_array('green', ['red','blue'], true));"),
    ("code_generation", "intermediate",
     "Write code that sanitizes a filename from user input to prevent path traversal.",
     "<?php\n$name = basename($_POST['file'] ?? '');\n$name = preg_replace('/[^A-Za-z0-9._-]/', '', $name);\necho $name;",
     "a safe filename",
     "basename strips directory components and the regex removes unsafe characters, blocking traversal like ../../etc/passwd.",
     "Using the raw user filename in a filesystem path, enabling directory traversal.",
     None,
     "assertEquals('passwd', basename('../../etc/passwd'));"),
    ("code_generation", "beginner",
     "Write code that echoes a form value only after casting to string and escaping.",
     "<?php\n$v = (string) ($_POST['v'] ?? '');\necho htmlspecialchars($v, ENT_QUOTES, 'UTF-8');",
     "escaped value",
     "Casting to string and escaping with an explicit charset produces safe HTML output.",
     "Omitting the charset, which can lead to encoding-based bypasses.",
     None,
     "assertIsString(htmlspecialchars('x', ENT_QUOTES, 'UTF-8'));"),
    ("code_explanation", "intermediate",
     "Explain why register_globals-style direct use of request data is unsafe.",
     "<?php\n// anti-pattern: assuming $name came from the request\n$name = $_REQUEST['name'] ?? '';",
     "the value of name from any request method",
     "$_REQUEST merges GET, POST and COOKIE, so the source is ambiguous; prefer $_GET or $_POST explicitly.",
     "Using $_REQUEST, which can pick up values from unexpected sources like cookies.",
     None,
     "assertIsArray($_REQUEST ?? []);"),
    ("find_bug", "advanced",
     "This multi-step form loses data on the second step. Find the bug.",
     "<?php\nif ($_SERVER['REQUEST_METHOD'] === 'POST') {\n    $step = (int) ($_POST['step'] ?? 1);\n    if ($step === 1) {\n        echo 'step1';\n    } elseif ($step === 2) {\n        echo $_POST['name'];\n    }\n}",
     "step2 prints nothing if name not resubmitted",
     "Each POST only contains the fields of the current submission; earlier values must be carried forward in hidden fields or a session.",
     "Assuming form fields persist across separate POST requests without being resubmitted.",
     "<?php\n// carry state forward with a hidden field:\n// <input type=\"hidden\" name=\"name\" value=\"...\">",
     "assertEquals(2, 2);"),
    ("code_generation", "intermediate",
     "Write code that validates a CSRF token before processing a POST.",
     "<?php\nsession_start();\n$token = $_POST['csrf'] ?? '';\nif (!hash_equals($_SESSION['csrf'] ?? '', $token)) {\n    http_response_code(403);\n    exit('forbidden');\n}",
     "forbidden when the token does not match",
     "hash_equals performs a timing-safe comparison, and matching against the session token blocks cross-site submissions.",
     "Using === for token comparison, which is vulnerable to timing attacks.",
     None,
     "assertTrue(hash_equals('a', 'a'));"),
    ("code_generation", "beginner",
     "Write code that limits a text input length and reports an error if too long.",
     "<?php\n$comment = $_POST['comment'] ?? '';\nif (mb_strlen($comment) > 200) {\n    echo 'too long';\n} else {\n    echo 'ok';\n}",
     "too long or ok",
     "mb_strlen counts characters (not bytes), correctly measuring multi-byte input.",
     "Using strlen, which counts bytes and overcounts multi-byte characters.",
     None,
     "assertTrue(mb_strlen('مرحبا') === 5);"),
    ("code_explanation", "advanced",
     "Explain why htmlspecialchars is needed even for data from your own database.",
     "<?php\necho htmlspecialchars($storedValue, ENT_QUOTES);",
     "escaped output",
     "Stored data may contain HTML from earlier input; escaping at output time prevents stored XSS regardless of origin.",
     "Assuming data from the database is inherently safe to print.",
     None,
     "assertStringContainsString('&lt;', htmlspecialchars('<b>'));"),
    ("find_bug", "intermediate",
     "This upload check relies on the file extension only. Find the weakness.",
     "<?php\n$ext = pathinfo($_FILES['f']['name'], PATHINFO_EXTENSION);\nif ($ext === 'jpg') {\n    move_uploaded_file($_FILES['f']['tmp_name'], \"uploads/\" . $_FILES['f']['name']);\n}",
     "accepts a renamed PHP file",
     "Trusting the client-provided name and extension is unsafe; validate the MIME type and generate a safe server-side filename.",
     "Relying on the user-supplied filename and extension for upload validation.",
     "<?php\n$info = getimagesize($_FILES['f']['tmp_name']);\nif ($info === false) { exit('not an image'); }\n$dest = 'uploads/' . bin2hex(random_bytes(8)) . '.jpg';\nmove_uploaded_file($_FILES['f']['tmp_name'], $dest);",
     "assertFalse(@getimagesize('nope'));"),
    ("code_generation", "intermediate",
     "Write code that processes a multi-select form field into an array of allowed values.",
     "<?php\n$allowed = ['a', 'b', 'c'];\n$sel = array_intersect((array) ($_POST['opts'] ?? []), $allowed);\nprint_r($sel);",
     "only the submitted values that are in the allowed list",
     "Casting to array handles single or multiple submissions, and array_intersect enforces the allowlist.",
     "Assuming $_POST['opts'] is always an array; a single selection may be a scalar.",
     None,
     "assertEquals(['a'], array_intersect(['a','x'], ['a','b','c']));"),
    ("code_generation", "beginner",
     "Write code that displays an error message only when validation fails.",
     "<?php\n$errors = [];\nif (($_POST['email'] ?? '') === '') {\n    $errors[] = 'Email required';\n}\nif ($errors) {\n    echo implode(', ', $errors);\n}",
     "Email required",
     "Collecting errors in an array and printing them only when non-empty gives clean conditional feedback.",
     "Printing errors unconditionally, showing messages even on a valid submission.",
     None,
     "assertNotEmpty(['Email required']);"),
    ("code_explanation", "intermediate",
     "Explain the purpose of htmlspecialchars flags here.",
     "<?php\necho htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');",
     "escaped output with invalid sequences substituted",
     "ENT_QUOTES escapes both quote types and ENT_SUBSTITUTE replaces invalid encoding with a safe character instead of returning empty.",
     "Using default flags that do not escape single quotes, leaving attribute contexts unsafe.",
     None,
     "assertIsString(htmlspecialchars('x', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'));"),
    ("find_bug", "beginner",
     "This code should show the posted username but shows nothing. Find the bug.",
     "<?php\necho $_POST['username'];",
     "Warning and empty output when the key is missing",
     "Accessing a missing POST key raises a warning and outputs nothing; use the null coalescing operator for a default.",
     "Reading request data without checking whether the key exists.",
     "<?php\necho htmlspecialchars($_POST['username'] ?? '', ENT_QUOTES);",
     "assertEquals('', '');"),
    ("code_generation", "intermediate",
     "Write code that converts a submitted date string to a validated DateTime.",
     "<?php\n$d = DateTime::createFromFormat('Y-m-d', $_POST['date'] ?? '');\nif ($d === false) {\n    echo 'invalid date';\n} else {\n    echo $d->format('Y-m-d');\n}",
     "the normalized date or invalid date",
     "createFromFormat returns false for malformed input, validating the format strictly.",
     "Using new DateTime() which is lenient and may accept unexpected formats.",
     None,
     "assertNotFalse(DateTime::createFromFormat('Y-m-d', '2020-01-01'));"),
    ("code_generation", "advanced",
     "Write code that validates an array of submitted IDs as positive integers.",
     "<?php\n$ids = array_map('intval', (array) ($_POST['ids'] ?? []));\n$ids = array_filter($ids, fn($i) => $i > 0);\nprint_r(array_values($ids));",
     "only positive integers",
     "Casting each value to int and filtering out non-positive numbers enforces the expected domain.",
     "Trusting the array contents without validating each element's type or range.",
     None,
     "assertEquals([1,2], array_values(array_filter(array_map('intval', ['1','2']), fn($i)=>$i>0)));"),
    ("code_explanation", "beginner",
     "Explain why the request method check matters for a delete action.",
     "<?php\nif ($_SERVER['REQUEST_METHOD'] === 'POST') {\n    deleteItem((int) $_POST['id']);\n}",
     "deletes only on POST",
     "Restricting destructive actions to POST prevents accidental deletion via a GET link or prefetcher.",
     "Allowing state-changing actions over GET, which can be triggered by crawlers or links.",
     None,
     "assertTrue(true);"),
    ("find_bug", "advanced",
     "This login form leaks whether a username exists. Find the flaw.",
     "<?php\n$u = $_POST['user'] ?? '';\nif (!userExists($u)) {\n    echo 'No such user';\n} else {\n    echo 'Wrong password';\n}",
     "distinct messages reveal valid usernames",
     "Different messages for unknown users and wrong passwords enable username enumeration; return one generic error.",
     "Returning different error messages for unknown user versus wrong password.",
     "<?php\n$u = $_POST['user'] ?? '';\nif (!checkCredentials($u, $_POST['pass'] ?? '')) {\n    echo 'Invalid credentials';\n}",
     "assertEquals('Invalid credentials', 'Invalid credentials');"),
    ("code_generation", "intermediate",
     "Write code that collects submitted form data into an array with defaults.",
     "<?php\n$data = [\n    'name' => trim($_POST['name'] ?? ''),\n    'age' => filter_var($_POST['age'] ?? '', FILTER_VALIDATE_INT),\n];\nprint_r($data);",
     "an array with normalized values",
     "Building a normalized array centralizes input handling and defaults before validation.",
     "Spreading request access throughout the codebase instead of normalizing once.",
     None,
     "assertEquals('a', trim(' a '));"),
    ("code_explanation", "intermediate",
     "Explain what this whitelist validation does.",
     "<?php\n$sort = $_GET['sort'] ?? 'name';\n$sort = in_array($sort, ['name','date'], true) ? $sort : 'name';",
     "name or date",
     "Only values on the allowlist are accepted; anything else falls back to the default, preventing injection via the sort field.",
     "Using the raw sort parameter directly in a query or as an array key.",
     None,
     "assertEquals('name', in_array('x', ['name','date'], true) ? 'x' : 'name');"),
    ("code_generation", "beginner",
     "Write code that checks a required field and reports which one is missing.",
     "<?php\n$required = ['name', 'email'];\n$missing = [];\nforeach ($required as $f) {\n    if (empty($_POST[$f])) {\n        $missing[] = $f;\n    }\n}\necho implode(',', $missing);",
     "comma-separated list of missing fields",
     "Iterating the required list and collecting missing ones gives a clear, maintainable error report.",
     "Hard-coding a chain of if statements for each field.",
     None,
     "assertEquals('name,email', implode(',', ['name','email']));"),
    ("find_bug", "intermediate",
     "This code should reject an invalid age but accepts negative numbers. Find the bug.",
     "<?php\n$age = (int) ($_POST['age'] ?? 0);\nif ($age === 0) {\n    echo 'invalid';\n}",
     "accepts -5",
     "Checking only for 0 misses negative numbers; validate a positive range instead.",
     "Validating a single sentinel value instead of a proper range.",
     "<?php\n$age = filter_var($_POST['age'] ?? '', FILTER_VALIDATE_INT, ['options'=>['min_range'=>1]]);\nif ($age === false) { echo 'invalid'; }",
     "assertFalse(filter_var('-5', FILTER_VALIDATE_INT, ['options'=>['min_range'=>1]]));"),
    ("code_generation", "advanced",
     "Write code that validates a numeric form field is within a range using filter options.",
     "<?php\n$qty = filter_var($_POST['qty'] ?? '', FILTER_VALIDATE_INT, [\n    'options' => ['min_range' => 1, 'max_range' => 100],\n]);\nvar_dump($qty);",
     "int within range or false",
     "FILTER_VALIDATE_INT with min_range and max_range rejects values outside the allowed bounds.",
     "Checking the range separately with > and < after a loose cast, which accepts out-of-range first.",
     None,
     "assertFalse(filter_var('101', FILTER_VALIDATE_INT, ['options'=>['max_range'=>100]]));"),
    ("code_explanation", "beginner",
     "Explain why output encoding belongs at the point of output, not input.",
     "<?php\n// store raw, escape on output\necho htmlspecialchars($row['title'], ENT_QUOTES);",
     "escaped title",
     "Encoding at output keeps the stored data intact for other uses while preventing injection in the HTML context.",
     "Sanitizing on input, which corrupts data and may still be unsafe in other output contexts.",
     None,
     "assertStringContainsString('&lt;', htmlspecialchars('<'));"),
    ("code_generation", "intermediate",
     "Write code that reads a JSON body from a POST request and validates it.",
     "<?php\n$body = file_get_contents('php://input');\n$data = json_decode($body, true);\nif (!is_array($data) || !isset($data['name'])) {\n    http_response_code(400);\n    exit('bad request');\n}",
     "bad request when invalid",
     "Reading php://input gets the raw body, and json_decode with validation ensures the expected structure.",
     "Trusting json_decode output without checking for null or the expected keys.",
     None,
     "assertNull(json_decode('not json'));"),
]

FORMS_INPUT = FORMS_INPUT[:35]