# -*- coding: utf-8 -*-
"""Conditions (40)."""

CONDITIONS = [
    ("code_generation", "beginner",
     "Write an if/else that prints 'adult' when age is 18 or more, otherwise 'minor'.",
     "<?php\n$age = 20;\nif ($age >= 18) {\n    echo 'adult';\n} else {\n    echo 'minor';\n}",
     "adult",
     "The >= comparison passes for 18 and above; the else branch handles everything lower.",
     "Using > 18, which wrongly excludes exactly 18-year-olds.",
     None,
     "assertEquals('adult', $age >= 18 ? 'adult' : 'minor');"),
    ("explain_error", "beginner",
     "Explain why this if statement always runs the branch.",
     "<?php\n$x = 5;\nif ($x = 0) {\n    echo 'never';\n}",
     "nothing printed",
     "A single = is assignment: $x becomes 0 which is falsy, so the branch never runs; the comparison was never performed.",
     "Using = instead of == or === in a condition.",
     "<?php\n$x = 5;\nif ($x === 0) {\n    echo 'never';\n}",
     "assertEquals(5, $x);"),
    ("code_generation", "intermediate",
     "Write a switch that prints the weekday name for $day (1 to 7).",
     "<?php\n$day = 3;\nswitch ($day) {\n    case 1: echo 'Mon'; break;\n    case 2: echo 'Tue'; break;\n    case 3: echo 'Wed'; break;\n    default: echo 'Other';\n}",
     "Wed",
     "switch compares the expression with each case using loose comparison; break prevents fall-through.",
     "Forgetting break, which causes fall-through into the next case.",
     None,
     "assertEquals('Wed', 'Wed');"),
    ("predict_output", "intermediate",
     "What is printed? Note which branch runs first when two conditions are true.",
     "<?php\n$x = 10;\nif ($x > 5) {\n    echo 'a';\n} elseif ($x > 8) {\n    echo 'b';\n}",
     "a",
     "Only the first matching branch runs; because $x > 5 is true, the elseif is skipped even though it is also true.",
     "Expecting both branches to run when both conditions are true.",
     None,
     "assertEquals('a', $x > 5 ? 'a' : 'b');"),
    ("code_generation", "intermediate",
     "Write code using the match expression that returns a grade label from a numeric score.",
     "<?php\n$score = 85;\n$grade = match (true) {\n    $score >= 90 => 'A',\n    $score >= 80 => 'B',\n    $score >= 70 => 'C',\n    default => 'F',\n};\necho $grade;",
     "B",
     "match(true) lets you use comparison expressions as arms, evaluated top to bottom until one matches.",
     "Ordering the arms from lowest to highest so the first true arm always wins.",
     None,
     "assertEquals('B', $score >= 90 ? 'A' : ($score >= 80 ? 'B' : 'C'));"),
    ("find_bug", "intermediate",
     "This should print 'yes' when $a and $b are both positive but always prints 'no'. Find the bug.",
     "<?php\n$a = 1;\n$b = -1;\nif ($a > 0 || $b > 0) {\n    echo 'yes';\n} else {\n    echo 'no';\n}",
     "yes",
     "There is no bug in behavior; || is true when either is positive. The developer likely wanted 'both positive', which needs &&.",
     "Using || (or) when the requirement is that BOTH conditions hold, which needs &&.",
     "<?php\n$a = 1;\n$b = -1;\nif ($a > 0 && $b > 0) {\n    echo 'yes';\n} else {\n    echo 'no';\n}",
     "assertEquals('no', ($a > 0 && $b > 0) ? 'yes' : 'no');"),
    ("code_explanation", "beginner",
     "Explain short-circuit evaluation here.",
     "<?php\nfunction check() { echo 'called'; return true; }\n$ok = false && check();\nvar_dump($ok);",
     "bool(false)",
     "With &&, if the left operand is false PHP does not evaluate the right side, so check() is never called.",
     "Expecting check() to run regardless of the short-circuit behavior of &&.",
     None,
     "assertFalse(false && check());"),
    ("code_generation", "beginner",
     "Write code that uses the ternary operator to output 'even' or 'odd'.",
     "<?php\n$n = 7;\necho $n % 2 === 0 ? 'even' : 'odd';",
     "odd",
     "The ternary evaluates the condition and returns the appropriate branch.",
     "Forgetting that the ternary needs both branches or nesting unnecessarily.",
     None,
     "assertEquals('odd', 7 % 2 === 0 ? 'even' : 'odd');"),
    ("predict_output", "advanced",
     "What does this print? Decide whether the string zero is truthy.",
     "<?php\n$x = '0';\nif ($x) {\n    echo 'truthy';\n} else {\n    echo 'falsy';\n}",
     "falsy",
     "The string '0' is one of the few strings treated as falsy in PHP.",
     "Assuming any non-empty string is truthy; '0' is the exception.",
     None,
     "assertEquals('falsy', '0' ? 'truthy' : 'falsy');"),
    ("code_review", "intermediate",
     "Review this nested if for readability and suggest simplification.",
     "<?php\nif ($active) {\n    if ($verified) {\n        echo 'ok';\n    }\n}",
     "ok",
     "Combine the nested conditions with && to reduce nesting and improve readability.",
     "Deeply nesting single-condition ifs that could be one combined condition.",
     "<?php\nif ($active && $verified) {\n    echo 'ok';\n}",
     "assertEquals('ok', ($active && $verified) ? 'ok' : '');"),
    ("code_generation", "intermediate",
     "Write code that uses the spaceship operator inside usort to sort descending.",
     "<?php\n$nums = [3, 1, 2];\nusort($nums, fn($a, $b) => $b <=> $a);\nprint_r($nums);",
     "[3,2,1]",
     "Swapping the operands in $b <=> $a reverses the order, producing a descending sort.",
     "Using $a <=> $b for descending, which sorts ascending instead.",
     None,
     "assertEquals([3,2,1], $nums);"),
    ("code_generation", "beginner",
     "Write a switch using the alternative syntax with endswitch.",
     "<?php\n$c = 'b';\nswitch ($c):\n    case 'a': echo 1; break;\n    case 'b': echo 2; break;\nendswitch;",
     "2",
     "The alternative syntax switch/endswitch is equivalent to braces and is often used in templates.",
     "Mixing brace syntax with endswitch, which is a parse error.",
     None,
     "assertEquals(2, $c === 'b' ? 2 : 0);"),
    ("explain_error", "intermediate",
     "Explain the UnhandledMatchError in this code.",
     "<?php\n$n = 5;\n$r = match ($n) {\n    1 => 'one',\n    2 => 'two',\n};\necho $r;",
     "Fatal error: UnhandledMatchError: Unhandled match case 5",
     "match throws UnhandledMatchError when no arm matches and there is no default arm.",
     "Assuming match silently returns null like switch falls through to nothing.",
     "<?php\n$n = 5;\n$r = match ($n) {\n    1 => 'one',\n    2 => 'two',\n    default => 'other',\n};\necho $r;",
     "assertEquals('other', $r);"),
    ("code_generation", "intermediate",
     "Write code that checks if a value is between 1 and 10 inclusive, using a single expression.",
     "<?php\n$v = 7;\necho ($v >= 1 && $v <= 10) ? 'in range' : 'out';",
     "in range",
     "Chaining two comparisons with && checks both bounds; PHP does not support Python-style chained comparison syntax.",
     "Writing 1 <= $v <= 10, which parses as (1 <= $v) <= 10 and is always true for 1 or 0.",
     None,
     "assertEquals('in range', ($v = 7) >= 1 && $v <= 10 ? 'in range' : 'out');"),
    ("predict_output", "beginner",
     "What is printed? Consider strict comparison between an int and a string.",
     "<?php\n$a = 2;\n$b = '2';\nif ($a === $b) {\n    echo 'same';\n} else {\n    echo 'different';\n}",
     "different",
     "=== requires identical types; $a is int 2 while $b is string '2', so the comparison is false.",
     "Expecting the strict comparison to treat '2' and 2 as equal because they look the same.",
     None,
     "assertEquals('different', (2 === '2') ? 'same' : 'different');"),
    ("code_generation", "advanced",
     "Write code using a guard clause pattern to avoid deep nesting.",
     "<?php\nfunction process(?string $name): string {\n    if ($name === null || $name === '') {\n        return 'guest';\n    }\n    return \"Hello, $name\";\n}\necho process('');",
     "guest",
     "Guard clauses return early for invalid input, keeping the happy path unindented and readable.",
     "Deeply nesting the success logic inside else blocks instead of returning early.",
     None,
     "assertEquals('guest', process(''));"),
    ("code_review", "intermediate",
     "Review this condition for a common Yoda-condition style issue.",
     "<?php\nif (5 = $count) {\n    echo 'five';\n}",
     "parse error",
     "Assigning to a literal is a fatal parse error; comparisons should use == or ===.",
     "Writing an assignment where a comparison was intended.",
     "<?php\nif (5 === $count) {\n    echo 'five';\n}",
     "assertEquals(5, $count = 5);"),
    ("code_generation", "beginner",
     "Write code that uses the ternary's shorthand elvis operator to default an empty string.",
     "<?php\n$name = '';\necho $name ?: 'Anonymous';",
     "Anonymous",
     "The elvis operator ?: returns the right side when the left is falsy, including an empty string.",
     "Using ?? which only replaces null/undefined, not an empty string.",
     None,
     "assertEquals('Anonymous', '' ?: 'Anonymous');"),
    ("explain_error", "advanced",
     "Explain why this comparison gives an unexpected result.",
     "<?php\nvar_dump(null == '');",
     "bool(true)",
     "null loosely equals '' because both coerce to a comparable empty value under PHP's == rules.",
     "Assuming == between null and '' is false; it is true, so use === for a strict check.",
     None,
     "assertTrue(null == '');"),
    ("code_generation", "intermediate",
     "Write code that combines several conditions with parentheses to control precedence.",
     "<?php\n$a = true; $b = false; $c = true;\necho ($a || $b) && $c ? 'go' : 'stop';",
     "go",
     "Parentheses make the grouping explicit: (true||false)=true, and true && true is true.",
     "Relying on default precedence where && binds tighter than ||, which changes the result.",
     None,
     "assertEquals('go', ($a || $b) && $c ? 'go' : 'stop');"),
    ("find_bug", "beginner",
     "This should print 'b' but prints 'a'. Find the bug.",
     "<?php\n$x = 3;\nif ($x < 5) {\n    echo 'a';\n} elseif ($x < 10) {\n    echo 'b';\n}",
     "a",
     "Because 3 < 5 is true, the first branch runs; the elseif is only evaluated when the first condition is false.",
     "Expecting the more specific condition to be checked regardless of the first branch.",
     "<?php\n$x = 3;\nif ($x >= 5 && $x < 10) {\n    echo 'b';\n} elseif ($x < 5) {\n    echo 'a';\n}",
     "assertEquals('a', $x < 5 ? 'a' : 'b');"),
    ("code_generation", "advanced",
     "Write code using an enum with a match to convert a status to a message.",
     "<?php\nenum S { case Open; case Closed; }\n$s = S::Closed;\necho match($s) {\n    S::Open => 'still working',\n    S::Closed => 'done',\n};",
     "done",
     "match compares enum cases by identity, giving exhaustive, type-safe branching.",
     "Comparing enum cases with == to a string, which does not match.",
     None,
     "assertEquals('done', match(S::Closed) { S::Open => 'still working', S::Closed => 'done' });"),
    ("predict_output", "intermediate",
     "What is printed? Explain both the truthiness of zero and comparing it to a non-numeric string.",
     "<?php\n$x = 0;\nif ($x) { echo 't'; } else { echo 'f'; }\necho $x == 'foo' ? 'eq' : 'ne';",
     "fne",
     "The integer 0 is falsy so 'f'; comparing 0 == 'foo' is false in PHP 8 so 'ne'.",
     "Expecting 0 == 'foo' to be true from PHP 7 behavior where the string was coerced to 0.",
     None,
     "assertEquals('fne', (0 ? 't' : 'f') . (0 == 'foo' ? 'eq' : 'ne'));"),
    ("code_generation", "beginner",
     "Write code that uses a boolean variable directly in an if condition.",
     "<?php\n$loggedIn = true;\nif ($loggedIn) {\n    echo 'welcome';\n}",
     "welcome",
     "A boolean can be used directly without comparing it to true, which is cleaner.",
     "Writing if ($loggedIn == true), which is redundant.",
     None,
     "assertEquals('welcome', $loggedIn ? 'welcome' : '');"),
    ("code_explanation", "intermediate",
     "Explain the difference between the two conditions.",
     "<?php\n$a = [];\nvar_dump(empty($a));\nvar_dump($a == false);",
     "bool(true)\nbool(true)",
     "empty([]) is true, and an empty array loosely equals false, though an empty array is truthy in a boolean context.",
     "Confusing empty(), loose equality, and direct boolean casting for arrays.",
     None,
     "assertTrue(empty([]));"),
    ("code_review", "advanced",
     "Review this condition that mixes assignment and comparison.",
     "<?php\nif ($row = fetch() && $row['id']) {\n    echo 'found';\n}",
     "found or nothing; precedence is wrong",
     "Due to precedence, && is evaluated before the assignment, so $row receives the boolean result rather than the row.",
     "Writing assignment inside a condition mixed with && without parentheses.",
     "<?php\nif (($row = fetch()) && $row['id']) {\n    echo 'found';\n}",
     "assertEquals(true, true);"),
    ("code_generation", "intermediate",
     "Write a switch with intentional fall-through that groups cases.",
     "<?php\n$c = 'b';\nswitch ($c) {\n    case 'a':\n    case 'b':\n        echo 'letter'; break;\n    default: echo 'other';\n}",
     "letter",
     "Stacking case labels lets both 'a' and 'b' share the same block.",
     "Adding break after the first grouped case, which prevents the intended sharing.",
     None,
     "assertEquals('letter', 'letter');"),
    ("code_generation", "beginner",
     "Write code that uses the null coalescing operator to pick a default title.",
     "<?php\n$post = [];\necho $post['title'] ?? 'Untitled';",
     "Untitled",
     "?? returns the default when the key is missing or null, without an undefined-key warning.",
     "Using the key directly, which raises a warning when it is absent.",
     None,
     "assertEquals('Untitled', $post['title'] ?? 'Untitled');"),
    ("find_bug", "intermediate",
     "This should classify a number but misclassifies negatives. Find the bug.",
     "<?php\n$n = -5;\nif ($n > 0) {\n    echo 'positive';\n} else {\n    echo 'non-positive';\n}",
     "non-positive",
     "No bug: -5 is non-positive, so the output is correct. The subtle issue would be if zero should be 'positive', which it is not.",
     "Assuming > 0 classifies zero as positive; it does not.",
     None,
     "assertEquals('non-positive', $n > 0 ? 'positive' : 'non-positive');"),
    ("code_generation", "advanced",
     "Write code that validates an email shape with a condition and filter_var.",
     "<?php\n$email = 'a@b.com';\nif (filter_var($email, FILTER_VALIDATE_EMAIL) !== false) {\n    echo 'valid';\n} else {\n    echo 'invalid';\n}",
     "valid",
     "filter_var with FILTER_VALIDATE_EMAIL returns the email or false; comparing !== false distinguishes validity.",
     "Checking the result with a plain truthiness check, which can misbehave for the string '0'.",
     None,
     "assertNotFalse(filter_var('a@b.com', FILTER_VALIDATE_EMAIL));"),
    ("predict_output", "advanced",
     "What does this print? Pay attention to the precedence of 'and'.",
     "<?php\n$a = true and false;\nvar_dump($a);",
     "bool(true)",
     "The assignment = binds tighter than the word 'and', so $a gets true first and then the and-expression evaluates and is discarded.",
     "Assuming 'and' has the same precedence as '&&'.",
     None,
     "assertTrue(($a = true) and false);"),
    ("code_explanation", "beginner",
     "Explain how the ternary handles a null condition.",
     "<?php\n$v = null;\necho $v ? 'yes' : 'no';",
     "no",
     "null is falsy, so the ternary selects the else branch and prints 'no'.",
     "Expecting null to be truthy.",
     None,
     "assertEquals('no', null ? 'yes' : 'no');"),
    ("code_generation", "intermediate",
     "Write code that uses a nested match to map a category and subcategory.",
     "<?php\n$type = 'fruit'; $name = 'apple';\n$msg = match($type) {\n    'fruit' => match($name) {\n        'apple' => 'a fruit',\n        default => 'some fruit',\n    },\n    default => 'unknown',\n};\necho $msg;",
     "a fruit",
     "match expressions can be nested, so an inner match refines the result based on a second value.",
     "Forgetting the inner default, which throws when the inner value is unmatched.",
     None,
     "assertEquals('a fruit', $msg);"),
    ("code_review", "beginner",
     "Review this verbose comparison and suggest a cleaner form.",
     "<?php\nif ($isReady == true) {\n    echo 'ready';\n}",
     "ready",
     "Comparing a boolean to true with == is redundant; use the boolean directly.",
     "Writing == true or == false instead of relying on truthiness.",
     "<?php\nif ($isReady) {\n    echo 'ready';\n}",
     "assertEquals('ready', $isReady ? 'ready' : '');"),
    ("code_generation", "beginner",
     "Write code that prints a message only when a variable is set and non-empty.",
     "<?php\n$comment = 'hi';\nif (!empty($comment)) {\n    echo 'posted';\n}",
     "posted",
     "empty() returns true for '' and null, so negating it checks for a meaningful value.",
     "Using isset() alone, which is true for an empty string as well.",
     None,
     "assertEquals('posted', !empty($comment) ? 'posted' : '');"),
    ("explain_error", "intermediate",
     "Explain why this elseif never executes.",
     "<?php\n$x = 10;\nif ($x >= 0) {\n    echo 'ge';\n} elseif ($x === 10) {\n    echo 'ten';\n}",
     "ge",
     "The first condition is already true for 10, so the elseif is not evaluated; order the conditions from most specific to least.",
     "Placing a specific condition after a broader one that already matches.",
     "<?php\n$x = 10;\nif ($x === 10) {\n    echo 'ten';\n} elseif ($x >= 0) {\n    echo 'ge';\n}",
     "assertEquals('ten', $x === 10 ? 'ten' : 'ge');"),
    ("code_generation", "advanced",
     "Write code that uses the nullsafe operator and a default in a condition.",
     "<?php\nclass Cfg { public ?string $env = null; }\n$c = new Cfg();\nif (($c->env ?? 'prod') === 'prod') {\n    echo 'production';\n}",
     "production",
     "The nullsafe/coalescing result is compared to 'prod'; the default applies because env is null.",
     "Forgetting the default and comparing null directly.",
     None,
     "assertEquals('production', ($c->env ?? 'prod') === 'prod' ? 'production' : '');"),
    ("predict_output", "intermediate",
     "What is printed by this is_numeric check?",
     "<?php\n$x = 'abc';\nif (is_numeric($x)) { echo 'num'; } else { echo 'not num'; }",
     "not num",
     "is_numeric() returns false for 'abc', so the else branch runs.",
     "Confusing is_numeric() with a simple numeric-string cast, which would coerce 'abc' to 0.",
     None,
     "assertEquals('not num', is_numeric('abc') ? 'num' : 'not num');"),
    ("code_generation", "intermediate",
     "Write code that uses the ternary to select between two arrays and prints the first element.",
     "<?php\n$use = true;\n$data = $use ? ['a','b'] : ['c','d'];\necho $data[0];",
     "a",
     "The ternary selects the array and then it is indexed; the whole expression yields the chosen value first.",
     "Trying to index inside the ternary without parentheses and getting a parse error.",
     None,
     "assertEquals('a', ($use ? ['a','b'] : ['c','d'])[0]);"),
    ("code_review", "intermediate",
     "Review this use of switch with loose comparison and suggest a match.",
     "<?php\nswitch ($status) {\n    case 1: echo 'one'; break;\n    case '1': echo 'also one'; break;\n    default: echo 'other';\n}",
     "one",
     "switch uses loose comparison, so both 1 and '1' match the first case, making the second dead code; match uses strict comparison and avoids this.",
     "Relying on switch loose comparison producing ambiguous matches.",
     "<?php\necho match (true) {\n    $status === 1 => 'one',\n    $status === '1' => 'also one',\n    default => 'other',\n};",
     "assertEquals(1, $status = 1);"),
    ("code_generation", "beginner",
     "Write code that uses a one-line if without braces and explain whether it is recommended.",
     "<?php\nif ($ok) echo 'ok';",
     "ok",
     "A single-statement if may omit braces, but adding braces is safer because it prevents mistakes when the body grows.",
     "Omitting braces, then adding a second statement that unexpectedly runs unconditionally.",
     "<?php\nif ($ok) {\n    echo 'ok';\n}",
     "assertEquals('ok', 'ok');"),
    ("explain_error", "advanced",
     "Explain why this comparison warning appears.",
     "<?php\nvar_dump('1e2' == 100);",
     "bool(true)",
     "Scientific-notation numeric strings like '1e2' are numeric, so they compare equal to 100 as numbers.",
     "Assuming strings with an exponent are treated as non-numeric text.",
     None,
     "assertTrue('1e2' == 100);"),
    ("code_generation", "intermediate",
     "Write code that combines match with a throw expression for the default arm.",
     "<?php\n$v = 2;\necho match($v) {\n    1 => 'a',\n    2 => 'b',\n    default => throw new InvalidArgumentException('bad'),\n};",
     "b",
     "A match arm can be a throw expression, making the default arm fail loudly instead of returning a sentinel.",
     "Returning a 'default' string that callers forget to check.",
     None,
     "assertEquals('b', $v === 2 ? 'b' : 'x');"),
]

CONDITIONS = CONDITIONS[:40]