# -*- coding: utf-8 -*-
"""OOP (45)."""

OOP = [
    ("code_generation", "beginner",
     "Write a class with a constructor and a method that returns a greeting.",
     "<?php\nclass User {\n    public function __construct(private string $name) {}\n    public function greet(): string {\n        return \"Hi, {$this->name}\";\n    }\n}\necho (new User('Ada'))->greet();",
     "Hi, Ada",
     "Constructor property promotion declares and assigns the property in one place; $this refers to the instance.",
     "Forgetting $this when accessing instance properties inside methods.",
     None,
     "assertEquals('Hi, Ada', (new User('Ada'))->greet());"),
    ("code_explanation", "beginner",
     "Explain the difference between public, private and protected.",
     "<?php\nclass A {\n    public $p = 1;\n    protected $r = 2;\n    private $v = 3;\n}",
     "public accessible everywhere, protected in class/subclass, private only in the class",
     "Access modifiers control visibility; private members are not accessible in subclasses while protected ones are.",
     "Assuming protected and private are interchangeable for subclass access.",
     None,
     "assertTrue(true);"),
    ("code_generation", "intermediate",
     "Write a subclass that overrides a parent method and calls the parent implementation.",
     "<?php\nclass Animal {\n    public function speak(): string { return '...'; }\n}\nclass Dog extends Animal {\n    public function speak(): string { return 'woof ' . parent::speak(); }\n}\necho (new Dog())->speak();",
     "woof ...",
     "Overriding replaces the parent method; parent::speak() calls the original implementation explicitly.",
     "Calling $this->speak() inside the override, which recurses infinitely.",
     None,
     "assertEquals('woof ...', (new Dog())->speak());"),
    ("code_generation", "intermediate",
     "Write an abstract class with an abstract method and a concrete subclass.",
     "<?php\nabstract class Shape {\n    abstract public function area(): float;\n}\nclass Square extends Shape {\n    public function __construct(private float $s) {}\n    public function area(): float { return $this->s ** 2; }\n}\necho (new Square(3))->area();",
     "9",
     "An abstract class cannot be instantiated and forces subclasses to implement its abstract methods.",
     "Trying to instantiate the abstract class directly, which is a fatal error.",
     None,
     "assertEquals(9.0, (new Square(3))->area());"),
    ("code_generation", "intermediate",
     "Write an interface and a class that implements it.",
     "<?php\ninterface Logger { public function log(string $m): void; }\nclass EchoLogger implements Logger {\n    public function log(string $m): void { echo $m; }\n}\n(new EchoLogger())->log('hi');",
     "hi",
     "An interface defines a contract of method signatures that implementing classes must fulfill.",
     "Leaving out a method required by the interface, which is a fatal error.",
     None,
     "assertEquals('hi', $out);"),
    ("predict_output", "intermediate",
     "What is printed?",
     "<?php\nclass C {\n    public static $n = 0;\n    public static function inc() { self::$n++; }\n}\nC::inc();\necho C::$n;",
     "2",
     "Static properties and methods belong to the class, not an instance, and are accessed with ::.",
     "Using $this inside a static method, which is a fatal error.",
     None,
     "assertEquals(2, C::$n);"),
    ("code_explanation", "intermediate",
     "Explain what these magic methods do.",
     "<?php\nclass M {\n    public function __get($n) { return \"get:$n\"; }\n    public function __set($n, $v) {}\n}",
     "accessing an undefined property returns get:<name>",
     "__get is invoked when reading an inaccessible property and __set when writing one.",
     "Writing __get but forgetting __set, so writes behave differently than reads.",
     None,
     "assertEquals('get:x', (new M())->x);"),
    ("code_generation", "advanced",
     "Write a class implementing __toString for string casting.",
     "<?php\nclass Money {\n    public function __construct(private int $cents) {}\n    public function __toString(): string { return number_format($this->cents / 100, 2); }\n}\necho (string) new Money(1234);",
     "12.34",
     "__toString is called when the object is cast to or used as a string.",
     "Forgetting __toString and getting a 'recoverable fatal error: object could not be converted to string'.",
     None,
     "assertEquals('12.34', (string) new Money(1234));"),
    ("find_bug", "intermediate",
     "This code should use the parent constructor but ignores it. Find the bug.",
     "<?php\nclass A { public function __construct(public int $x) {} }\nclass B extends A {\n    public function __construct(int $x, public int $y) {\n        $this->y = $y;\n    }\n}\n$b = new B(1, 2);\necho $b->x;",
     "undefined property access / Error",
     "The child constructor sets $y but never calls parent::__construct, so $x is never initialized.",
     "Omitting parent::__construct in a child constructor when the parent requires initialization.",
     "<?php\nclass A { public function __construct(public int $x) {} }\nclass B extends A {\n    public function __construct(int $x, public int $y) {\n        parent::__construct($x);\n        $this->y = $y;\n    }\n}",
     "assertEquals(1, (new B(1,2))->x);"),
    ("code_generation", "advanced",
     "Write a trait and use it in two classes.",
     "<?php\ntrait Greet {\n    public function hi(): string { return 'hi'; }\n}\nclass A { use Greet; }\nclass B { use Greet; }\necho (new A())->hi() . (new B())->hi();",
     "hihi",
     "A trait provides methods that can be composed into multiple classes, avoiding duplication.",
     "Using a trait as a class type or trying to instantiate it.",
     None,
     "assertEquals('hihi', (new A())->hi() . (new B())->hi());"),
    ("code_explanation", "advanced",
     "Explain method resolution when a class uses a trait and defines the same method.",
     "<?php\ntrait T { public function f() { return 'trait'; } }\nclass C { use T; public function f() { return 'class'; } }\necho (new C())->f();",
     "class",
     "A method defined in the class overrides the trait method of the same name.",
     "Expecting the trait method to win because it is listed in the use statement.",
     None,
     "assertEquals('class', (new C())->f());"),
    ("code_generation", "intermediate",
     "Write a class with a readonly property and show it cannot be changed.",
     "<?php\nclass Id {\n    public function __construct(public readonly string $value) {}\n}\n$id = new Id('x');\necho $id->value;",
     "x",
     "A readonly property can be written once (usually in the constructor) and never again.",
     "Attempting to modify a readonly property after construction, which throws an Error.",
     None,
     "assertEquals('x', (new Id('x'))->value);"),
    ("code_generation", "advanced",
     "Write an enum with a method and use it.",
     "<?php\nenum Suit: string {\n    case Hearts = 'H';\n    case Spades = 'S';\n    public function label(): string { return $this->name; }\n}\necho Suit::Hearts->label();",
     "Hearts",
     "Enums can define methods that operate on the case, accessing $this->name and $this->value.",
     "Trying to add state to an enum case; enums are immutable singletons.",
     None,
     "assertEquals('Hearts', Suit::Hearts->label());"),
    ("predict_output", "advanced",
     "What does this print? Explain the late static binding involved.",
     "<?php\nclass A { public function f() { return static::g(); } public function g() { return 'A'; } }\nclass B extends A { public function g() { return 'B'; } }\necho (new B())->f();",
     "B",
     "static::g() uses late static binding, resolving to the runtime class B's method.",
     "Using self::g() which would bind to class A and print 'A'.",
     None,
     "assertEquals('B', (new B())->f());"),
    ("find_bug", "beginner",
     "This object property is undefined. Find the bug.",
     "<?php\nclass C { public $x; }\n$c = new C();\necho $c->y;",
     "Warning: Undefined property C::$y",
     "The class defines $x but the code reads $y, which does not exist; use a defined property or declare it.",
     "Reading a property that was never declared on the class.",
     "<?php\nclass C { public $y = 0; }\n$c = new C();\necho $c->y;",
     "assertEquals(0, (new C())->y);"),
    ("code_generation", "intermediate",
     "Write a class that implements the Countable interface.",
     "<?php\nclass Bag implements Countable {\n    private array $items = [1,2,3];\n    public function count(): int { return count($this->items); }\n}\necho count(new Bag());",
     "3",
     "Implementing Countable lets the object be passed to count().",
     "Naming the method countAll instead of count, so count() fails.",
     None,
     "assertEquals(3, count(new Bag()));"),
    ("code_generation", "advanced",
     "Write a class implementing IteratorAggregate to make it foreach-able.",
     "<?php\nclass L implements IteratorAggregate {\n    public function __construct(private array $d) {}\n    public function getIterator(): Iterator { return new ArrayIterator($this->d); }\n}\nforeach (new L(['a','b']) as $v) { echo $v; }",
     "ab",
     "Implementing IteratorAggregate with a getIterator() return makes the object iterable with foreach.",
     "Returning a plain array from getIterator, which is not an Iterator.",
     None,
     "assertEquals('ab', $out);"),
    ("code_explanation", "intermediate",
     "Explain constructor property promotion.",
     "<?php\nclass P {\n    public function __construct(public int $x, private int $y = 0) {}\n}",
     "declares and assigns $x (public int) and $y (private int)",
     "Promoted constructor parameters declare class properties and assign them in one concise signature.",
     "Also declaring the properties separately, which duplicates them.",
     None,
     "assertEquals(1, (new P(1))->x);"),
    ("code_generation", "intermediate",
     "Write a class with a static factory method.",
     "<?php\nclass Color {\n    private function __construct(public string $hex) {}\n    public static function fromHex(string $h): self { return new self($h); }\n}\necho Color::fromHex('#fff')->hex;",
     "#fff",
     "A static factory method centralizes construction and can hide the constructor to enforce invariants.",
     "Making the constructor public while also relying on the factory, defeating the encapsulation.",
     None,
     "assertEquals('#fff', Color::fromHex('#fff')->hex);"),
    ("find_bug", "advanced",
     "This code should call the overridden method but prints the parent result. Find the bug.",
     "<?php\nclass A { public function f() { return self::g(); } public function g() { return 'A'; } }\nclass B extends A { public function g() { return 'B'; } }\necho (new B())->f();",
     "A",
     "self::g() binds to class A at compile time; use static::g() for late static binding to get 'B'.",
     "Using self:: instead of static:: when late static binding is intended.",
     "<?php\nclass A { public function f() { return static::g(); } public function g() { return 'A'; } }\nclass B extends A { public function g() { return 'B'; } }\necho (new B())->f();",
     "assertEquals('B', (new B())->f());"),
    ("code_generation", "advanced",
     "Write a class that uses a private constructor and a static counter to enforce a single instance.",
     "<?php\nclass Registry {\n    private static ?Registry $inst = null;\n    private function __construct() {}\n    public static function get(): self {\n        return self::$inst ??= new self();\n    }\n}\nvar_dump(Registry::get() === Registry::get());",
     "bool(true)",
     "A private constructor plus a static accessor ensures only one instance is ever created.",
     "Making the constructor public, which allows additional instances to bypass the singleton.",
     None,
     "assertTrue(Registry::get() === Registry::get());"),
    ("code_explanation", "advanced",
     "Explain the difference between abstract classes and interfaces here.",
     "<?php\ninterface Readable { public function read(): string; }\nabstract class Base implements Readable { public function log() {} }",
     "interface is a pure contract; abstract class can carry implementation and state",
     "Interfaces declare only signatures (until PHP 8 default methods are not allowed) while abstract classes can implement behavior and hold properties.",
     "Expecting an interface to hold method bodies or properties.",
     None,
     "assertTrue(interface_exists('Readable'));"),
    ("code_generation", "intermediate",
     "Write code that uses instanceof to branch on object type.",
     "<?php\nclass Cat {}\nclass Dog {}\nfunction sound(object $a): string {\n    return $a instanceof Cat ? 'meow' : 'woof';\n}\necho sound(new Cat());",
     "meow",
     "instanceof checks the runtime class or interface of an object.",
     "Using gettype or type juggling instead of instanceof for object checks.",
     None,
     "assertEquals('meow', sound(new Cat()));"),
    ("code_generation", "advanced",
     "Write code that uses an anonymous class.",
     "<?php\n$obj = new class {\n    public function hi(): string { return 'anon'; }\n};\necho $obj->hi();",
     "anon",
     "An anonymous class creates an object without naming the class, useful for one-off implementations.",
     "Trying to reference the anonymous class by name later.",
     None,
     "assertEquals('anon', $obj->hi());"),
    ("find_bug", "intermediate",
     "This clone shares state with the original. Find the bug.",
     "<?php\nclass Box { public function __construct(public array $items) {} }\n$a = new Box([1]);\n$b = clone $a;\n$b->items[] = 2;\nprint_r($a->items);",
     "Array ( [0] => 1 [1] => 2 )",
     "clone is shallow, so the array property is shared by reference; implement __clone to deep-copy mutable objects/arrays.",
     "Assuming clone performs a deep copy of nested arrays or objects.",
     "<?php\nclass Box {\n    public function __construct(public array $items) {}\n    public function __clone() { $this->items = array_values($this->items); }\n}",
     "assertEquals([1], (function($a){ $b = clone $a; $b->items = [...$b->items, 2]; return $a->items; })(new Box([1])));"),
    ("code_explanation", "intermediate",
     "Explain object comparison with == and ===.",
     "<?php\nclass P { public function __construct(public int $x) {} }\n$a = new P(1); $b = new P(1);\nvar_dump($a == $b);\nvar_dump($a === $b);",
     "bool(true)\nbool(false)",
     "== compares objects of the same class with equal properties; === requires they be the same instance.",
     "Assuming == on objects means identity like ===.",
     None,
     "assertTrue(new P(1) == new P(1));"),
    ("code_generation", "intermediate",
     "Write a class with a final method to prevent overriding.",
     "<?php\nclass A {\n    final public function id(): string { return 'fixed'; }\n}\nclass B extends A {}\necho (new B())->id();",
     "fixed",
     "A final method cannot be overridden by subclasses, preserving its behavior.",
     "Trying to override a final method, which is a fatal error.",
     None,
     "assertEquals('fixed', (new B())->id());"),
    ("code_generation", "advanced",
     "Write code that uses an interface default via a shared trait method.",
     "<?php\ninterface Named { public function name(): string; }\ntrait HasName { public function name(): string { return 'default'; } }\nclass E implements Named { use HasName; }\necho (new E())->name();",
     "default",
     "A trait can supply a concrete implementation of an interface method, reducing boilerplate across classes.",
     "Defining the method in the interface body, which is not allowed.",
     None,
     "assertEquals('default', (new E())->name());"),
    ("predict_output", "advanced",
     "What is printed by these static and instance calls?",
     "<?php\nclass C {\n    public function who() { return 'instance'; }\n    public static function s() { return 'static'; }\n}\n$c = new C();\necho $c->who() . C::s();",
     "instancestatic",
     "Instance methods are called on an object, static methods on the class name.",
     "Calling an instance method statically, which is deprecated/error.",
     None,
     "assertEquals('instancestatic', (new C)->who() . C::s());"),
    ("find_bug", "advanced",
     "This dependency is hard-coded, making testing hard. Find the design flaw.",
     "<?php\nclass Mailer {\n    public function send() { return (new Smtp())->transmit(); }\n}",
     "tight coupling to Smtp",
     "Instantiating the dependency inside the class prevents substituting a test double; inject an interface instead.",
     "Hard-coding a concrete collaborator instead of injecting an abstraction.",
     "<?php\nclass Mailer {\n    public function __construct(private Transporter $t) {}\n    public function send() { return $this->t->transmit(); }\n}",
     "assertTrue(true);"),
    ("code_explanation", "beginner",
     "Explain what $this refers to inside a method.",
     "<?php\nclass C {\n    public int $v = 5;\n    public function get(): int { return $this->v; }\n}",
     "5",
     "$this is the current object instance on which the method was called.",
     "Using $this in a static method, where there is no instance.",
     None,
     "assertEquals(5, (new C())->get());"),
    ("code_generation", "intermediate",
     "Write a class that validates its constructor argument and throws on invalid input.",
     "<?php\nclass Email {\n    public function __construct(public string $value) {\n        if (filter_var($value, FILTER_VALIDATE_EMAIL) === false) {\n            throw new InvalidArgumentException('bad email');\n        }\n    }\n}\necho (new Email('a@b.com'))->value;",
     "a@b.com",
     "Validating in the constructor keeps the object always in a valid state (a value object).",
     "Allowing invalid construction and expecting callers to validate later.",
     None,
     "assertEquals('a@b.com', (new Email('a@b.com'))->value);"),
    ("code_generation", "advanced",
     "Write code that uses first-class enum with a match over cases.",
     "<?php\nenum Status { case Open; case Closed; }\nfunction label(Status $s): string {\n    return match($s) {\n        Status::Open => 'open',\n        Status::Closed => 'closed',\n    };\n}\necho label(Status::Open);",
     "open",
     "Pure enums have no backing value but can be matched exhaustively by case.",
     "Trying to read ->value on a pure (non-backed) enum, which is an error.",
     None,
     "assertEquals('open', label(Status::Open));"),
    ("code_review", "intermediate",
     "Review this class for a violated encapsulation principle.",
     "<?php\nclass Account {\n    public float $balance = 0;\n}",
     "public mutable balance",
     "A public property lets any code set balance arbitrarily; make it private and expose controlled deposit/withdraw methods.",
     "Exposing mutable state publicly instead of through methods that enforce rules.",
     "<?php\nclass Account {\n    private float $balance = 0;\n    public function deposit(float $a): void { $this->balance += $a; }\n    public function balance(): float { return $this->balance; }\n}",
     "assertEquals(0.0, (new Account())->balance());"),
    ("code_generation", "intermediate",
     "Write code that uses a nullable object property and checks before use.",
     "<?php\nclass Node { public ?Node $next = null; }\n$n = new Node();\necho $n->next === null ? 'end' : 'more';",
     "end",
     "A nullable typed property can hold null; checking before dereferencing avoids errors.",
     "Dereferencing a null property without a check, causing an error.",
     None,
     "assertEquals('end', (new Node())->next === null ? 'end' : 'more');"),
    ("code_explanation", "advanced",
     "Explain how method visibility affects inheritance here.",
     "<?php\nclass A { protected function f() { return 'x'; } }\nclass B extends A { public function g() { return $this->f(); } }\necho (new B())->g();",
     "x",
     "A protected method is accessible within subclasses, so B can call the inherited f().",
     "Trying to call the protected method from outside, which is a fatal error.",
     None,
     "assertEquals('x', (new B())->g());"),
    ("code_generation", "advanced",
     "Write a class hierarchy that uses an interface for payment and two implementations.",
     "<?php\ninterface Payment { public function pay(int $c): string; }\nclass Cash implements Payment { public function pay(int $c): string { return 'cash'; } }\nclass Card implements Payment { public function pay(int $c): string { return 'card'; } }\necho (new Card())->pay(100);",
     "card",
     "Programming to an interface lets callers use any implementation interchangeably (polymorphism).",
     "Depending on concrete class names instead of the interface, reducing flexibility.",
     None,
     "assertEquals('card', (new Card())->pay(100));"),
    ("find_bug", "intermediate",
     "This static property is reset between objects unexpectedly. Find the cause.",
     "<?php\nclass C {\n    public static int $count = 0;\n    public function __construct() { self::$count++; }\n}\nnew C(); new C();\necho C::$count;",
     "2",
     "There is no bug; the static counter increments per construction and reads 2 across all instances.",
     "Expecting a static property to be per-instance; it is shared across all instances of the class.",
     None,
     "assertEquals(2, C::$count);"),
    ("code_review", "advanced",
     "Review this deeply nested inheritance hierarchy.",
     "<?php\nclass A {}\nclass B extends A {}\nclass C extends B {}\nclass D extends C {}",
     "deep inheritance chain",
     "Deep hierarchies are brittle; prefer composition and interfaces over many levels of inheritance.",
     "Favoring inheritance depth over composition, which couples subclasses tightly.",
     None,
     "assertTrue(true);"),
    ("code_generation", "intermediate",
     "Write code that uses the spaceship operator inside a class comparator.",
     "<?php\nclass Version {\n    public function __construct(public int $major) {}\n}\n$a = new Version(1);\n$b = new Version(2);\nvar_dump($a->major <=> $b->major);",
     "int(-1)",
     "Comparing the relevant field with <=> gives the ordering for sorting.",
     "Comparing whole objects, which is not meaningful for ordering.",
     None,
     "assertEquals(-1, 1 <=> 2);"),
    ("code_explanation", "intermediate",
     "Explain what the __invoke magic method enables.",
     "<?php\nclass Adder {\n    public function __invoke(int $a, int $b): int { return $a + $b; }\n}\n$add = new Adder();\necho $add(2, 3);",
     "5",
     "__invoke makes an object callable as if it were a function.",
     "Trying to call an object without __invoke, which is a fatal error.",
     None,
     "assertEquals(5, (new Adder())(2, 3));"),
    ("code_generation", "advanced",
     "Write a class that implements __get and __isset for virtual properties.",
     "<?php\nclass Config {\n    private array $d = ['a' => 1];\n    public function __get($n) { return $this->d[$n]; }\n    public function __isset($n) { return isset($this->d[$n]); }\n}\n$c = new Config();\nvar_dump(isset($c->a), isset($c->b));",
     "bool(true)\nbool(false)",
     "__isset lets isset() work with virtual properties backed by an internal array.",
     "Defining __get without __isset, so isset() on virtual properties always returns false.",
     None,
     "assertTrue(isset($c->a));"),
    ("code_review", "beginner",
     "Review this class naming and suggest a convention.",
     "<?php\nclass user_manager { public function GetUser() {} }",
     "non-standard names",
     "PHP convention uses PascalCase for classes and camelCase for methods; userManager should be UserManager.",
     "Using snake_case or hostile casing that breaks autoloading conventions.",
     "<?php\nclass UserManager { public function getUser() {} }",
     "assertTrue(true);"),
    ("code_generation", "intermediate",
     "Write a class with a constant and access it.",
     "<?php\nclass Circle {\n    public const PI = 3.14159;\n    public function __construct(private float $r) {}\n    public function area(): float { return self::PI * $this->r ** 2; }\n}\necho round((new Circle(1))->area(), 2);",
     "3.14",
     "Class constants are accessed with self:: inside the class and Class::CONST outside.",
     "Using $this->PI for a constant, which is invalid.",
     None,
     "assertEquals(3.14, round(Circle::PI, 2));"),
    ("code_explanation", "advanced",
     "Explain what declare(strict_types=1) changes for methods.",
     "<?php\ndeclare(strict_types=1);\nclass C {\n    public function f(int $x): int { return $x; }\n}\n// (new C())->f('1') would throw",
     "TypeError for string to int",
     "Under strict types, passing a string to an int parameter of a method throws instead of coercing.",
     "Expecting method calls to coerce types even under strict_types.",
     None,
     "assertEquals(1, (new C())->f(1));"),
]

OOP = OOP[:45]