# -*- coding: utf-8 -*-
"""Testing & Debugging (10)."""

TESTING = [
    ("write_test", "beginner",
     "Write a PHPUnit test asserting an add() function returns the correct sum.",
     "<?php\nuse PHPUnit\\Framework\\TestCase;\n\nclass AddTest extends TestCase\n{\n    public function testAdd(): void\n    {\n        $this->assertSame(5, add(2, 3));\n    }\n}",
     None,
     "assertSame checks both value and type, making it stricter than assertEquals for scalars.",
     "Using assertEquals on ints where a float result would still pass loosely.",
     None,
     "phpunit passes when add(2,3) returns int 5."),
    ("write_test", "intermediate",
     "Write a PHPUnit test that expects an exception to be thrown.",
     "<?php\nuse PHPUnit\\Framework\\TestCase;\n\nclass DivTest extends TestCase\n{\n    public function testZero(): void\n    {\n        $this->expectException(DivisionByZeroError::class);\n        intdiv(1, 0);\n    }\n}",
     None,
     "expectException declares the exception type the test expects; if it is not thrown, the test fails.",
     "Calling the code before expectException, so the exception escapes the test.",
     None,
     "phpunit passes because intdiv(1,0) throws DivisionByZeroError."),
    ("write_test", "intermediate",
     "Write a test using a data provider for a classify() function.",
     "<?php\nuse PHPUnit\\Framework\\TestCase;\n\nclass ClassifyTest extends TestCase\n{\n    /** @dataProvider cases */\n    public function testClassify(int $n, string $e): void\n    {\n        $this->assertSame($e, classify($n));\n    }\n    public static function cases(): array\n    {\n        return [[-1, 'neg'], [0, 'zero'], [1, 'pos']];\n    }\n}",
     None,
     "The data provider feeds multiple input/expected pairs into one test method.",
     "Forgetting the @dataProvider annotation, so the provider is never used.",
     None,
     "phpunit runs testClassify three times."),
    ("code_explanation", "beginner",
     "Explain what a failing assertion message tells you.",
     "<?php\n$this->assertSame(4, add(2, 3));",
     "Failed asserting that 5 is identical to 4.",
     "The message shows the expected versus actual value, pointing directly at the mismatch.",
     "Ignoring the message and guessing at the cause.",
     None,
     "assertTrue(true);"),
    ("write_test", "advanced",
     "Write a test that uses a mock to verify a method is called.",
     "<?php\nuse PHPUnit\\Framework\\TestCase;\n\nclass NotifyTest extends TestCase\n{\n    public function testNotifies(): void\n    {\n        $mailer = $this->createMock(Mailer::class);\n        $mailer->expects($this->once())->method('send');\n        (new Service($mailer))->run();\n    }\n}",
     None,
     "A mock stands in for a collaborator and expects a specific call, isolating the unit under test.",
     "Testing the real collaborator, which makes the test slow and flaky.",
     None,
     "phpunit passes when Service::run calls Mailer::send exactly once."),
    ("code_explanation", "intermediate",
     "Explain how to debug an unexpected value with var_dump and die.",
     "<?php\nvar_dump($data);\ndie();",
     "dumps the variable then stops execution",
     "var_dump shows type and structure; die() stops the script so you can inspect the dump without further output.",
     "Leaving debugging dumps in production code.",
     None,
     "assertTrue(true);"),
    ("find_bug", "intermediate",
     "This test passes even when the code is wrong. Find the bug.",
     "<?php\npublic function testSomething(): void\n{\n    $r = doThing();\n    $this->assertTrue(true);\n}",
     "always passes",
     "The assertion checks a literal true instead of the result $r, so the test never fails.",
     "Asserting a constant instead of the actual result.",
     "<?php\npublic function testSomething(): void\n{\n    $this->assertSame('expected', doThing());\n}",
     "assertTrue(true);"),
    ("write_test", "advanced",
     "Write a test that asserts a JSON response structure with a partial match.",
     "<?php\nuse PHPUnit\\Framework\\TestCase;\n\nclass ApiTest extends TestCase\n{\n    public function testPayload(): void\n    {\n        $data = json_decode('{\"id\":1,\"name\":\"Ada\"}', true);\n        $this->assertArrayHasKey('id', $data);\n        $this->assertSame(1, $data['id']);\n    }\n}",
     None,
     "Combining assertArrayHasKey with a value assertion checks both shape and content of the payload.",
     "Comparing the whole decoded array, which is brittle to extra fields.",
     None,
     "phpunit passes for the given payload."),
    ("code_explanation", "advanced",
     "Explain the difference between unit and integration tests.",
     "<?php\n// unit: test one function in isolation\n// integration: test several parts together (e.g. with a real DB)\n",
     "unit isolates; integration combines",
     "Unit tests are fast and isolated; integration tests verify that components work together, often with real infrastructure.",
     "Writing only integration tests, which are slow and harder to pinpoint failures.",
     None,
     "assertTrue(true);"),
    ("write_test", "beginner",
     "Write a test that checks a value is within a range using assertGreaterThanOrEqual.",
     "<?php\nuse PHPUnit\\Framework\\TestCase;\n\nclass RangeTest extends TestCase\n{\n    public function testRange(): void\n    {\n        $v = rand(1, 10);\n        $this->assertGreaterThanOrEqual(1, $v);\n        $this->assertLessThanOrEqual(10, $v);\n    }\n}",
     None,
     "Two boundary assertions verify the value lies within the inclusive range.",
     "Asserting only the lower bound and forgetting the upper bound.",
     None,
     "phpunit passes because the value is always between 1 and 10."),
]

TESTING = TESTING[:10]