# -*- coding: utf-8 -*-
"""Files & JSON (25)."""

FILES_JSON = [
    ("code_generation", "beginner",
     "Write code that writes a string to a file and reads it back.",
     "<?php\nfile_put_contents('/tmp/d.txt', 'hello');\necho file_get_contents('/tmp/d.txt');",
     "hello",
     "file_put_contents writes (creating or truncating the file) and file_get_contents reads the whole file into a string.",
     "Forgetting that file_put_contents overwrites by default unless FILE_APPEND is used.",
     None,
     "assertEquals('hello', file_get_contents('php://memory') === '' ? 'hello' : 'x');"),
    ("code_generation", "intermediate",
     "Write code that appends a line to a file using FILE_APPEND.",
     "<?php\nfile_put_contents('/tmp/log.txt', \"line\\n\", FILE_APPEND);\necho 'ok';",
     "ok",
     "The FILE_APPEND flag adds to the end of the file instead of truncating it.",
     "Appending without a newline, so records run together.",
     None,
     "assertEquals('ok', $out);"),
    ("code_explanation", "beginner",
     "Explain the return value of file_get_contents on failure.",
     "<?php\n$c = file_get_contents('/no/such');\nvar_dump($c);",
     "bool(false) with a warning",
     "On failure file_get_contents returns false and emits a warning; check for false before using the result.",
     "Assuming it throws an exception; it returns false.",
     None,
     "assertFalse(@file_get_contents('/no/such'));"),
    ("code_generation", "intermediate",
     "Write code that reads a file line by line without loading it all into memory.",
     "<?php\n$fh = fopen('/tmp/d.txt', 'r');\nwhile (($line = fgets($fh)) !== false) {\n    echo $line;\n}\nfclose($fh);",
     "each line",
     "fgets reads one line at a time, keeping memory use low for large files.",
     "Forgetting to fclose the handle, which can leak file descriptors.",
     None,
     "assertIsResource(fopen('php://memory', 'r'));"),
    ("code_generation", "advanced",
     "Write code that reads a large file with a generator to yield lines.",
     "<?php\nfunction lines(string $p): Generator {\n    $fh = fopen($p, 'r');\n    try {\n        while (($l = fgets($fh)) !== false) {\n            yield $l;\n        }\n    } finally {\n        fclose($fh);\n    }\n}",
     "lines yielded lazily",
     "A generator reads lazily and the finally block guarantees the handle closes even if the consumer stops early.",
     "Reading the whole file with file() for a large file, which uses a lot of memory.",
     None,
     "assertIsCallable('lines');"),
    ("code_generation", "intermediate",
     "Write code that encodes an array to JSON and decodes it back.",
     "<?php\n$json = json_encode(['a' => 1]);\n$arr = json_decode($json, true);\necho $arr['a'];",
     "1",
     "json_encode produces a JSON string; json_decode with true returns an associative array.",
     "Calling json_decode without true, which returns stdClass objects instead of arrays.",
     None,
     "assertEquals(1, json_decode('{\"a\":1}', true)['a']);"),
    ("find_bug", "intermediate",
     "This JSON handling silently produces null. Find the bug.",
     "<?php\n$data = json_decode('{invalid}');\nvar_dump($data);",
     "NULL",
     "Invalid JSON makes json_decode return null; check json_last_error() or use the JSON_THROW_ON_ERROR flag.",
     "Ignoring the return value and the error state after json_decode.",
     "<?php\n$data = json_decode('{invalid}', true, 512, JSON_THROW_ON_ERROR);",
     "assertEquals(JSON_ERROR_SYNTAX, json_last_error());"),
    ("code_generation", "advanced",
     "Write code that decodes JSON and throws on error using JSON_THROW_ON_ERROR.",
     "<?php\ntry {\n    $d = json_decode('{\"a\":1}', true, 512, JSON_THROW_ON_ERROR);\n    echo $d['a'];\n} catch (JsonException $e) {\n    echo 'bad json';\n}",
     "1",
     "The JSON_THROW_ON_ERROR flag makes json_decode throw JsonException instead of returning null.",
     "Mixing JSON_THROW_ON_ERROR with manual json_last_error checks, which is redundant.",
     None,
     "assertEquals(1, json_decode('{\"a\":1}', true, 512, JSON_THROW_ON_ERROR)['a']);"),
    ("code_explanation", "intermediate",
     "Explain what json_encode options do here.",
     "<?php\necho json_encode(['x' => 1], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);",
     "a pretty-printed JSON object",
     "JSON_PRETTY_PRINT adds whitespace for readability and JSON_UNESCAPED_SLASHES keeps forward slashes unescaped.",
     "Using JSON_PRETTY_PRINT for API responses, which wastes bandwidth.",
     None,
     "assertStringContainsString('\"x\"', json_encode(['x'=>1]));"),
    ("code_generation", "intermediate",
     "Write code that reads a JSON file into an array with error handling.",
     "<?php\n$raw = @file_get_contents('c.json');\nif ($raw === false) {\n    echo 'missing';\n} else {\n    $cfg = json_decode($raw, true) ?? [];\n    echo count($cfg);\n}",
     "missing or the number of keys",
     "Check the read result before decoding, and default the decoded value to an empty array on failure.",
     "Decoding without checking whether the file read succeeded.",
     None,
     "assertEquals(0, count(json_decode('null', true) ?? []));"),
    ("code_generation", "beginner",
     "Write code that checks whether a file exists before reading it.",
     "<?php\n$p = '/tmp/x';\nif (is_file($p)) {\n    echo file_get_contents($p);\n} else {\n    echo 'no file';\n}",
     "no file (when absent)",
     "is_file returns true only for regular files, avoiding warnings from a direct read.",
     "Using file_exists which is also true for directories.",
     None,
     "assertIsBool(is_file('/tmp'));"),
    ("code_generation", "advanced",
     "Write code that writes atomically using a temporary file and rename.",
     "<?php\n$tmp = tempnam(sys_get_temp_dir(), 'w');\nfile_put_contents($tmp, 'data');\nrename($tmp, '/tmp/final.txt');",
     "the file is written atomically",
     "Writing to a temp file and renaming avoids readers seeing a partially written file.",
     "Writing directly to the destination, which can be read mid-write by other processes.",
     None,
     "assertNotFalse(tempnam(sys_get_temp_dir(), 'w'));"),
    ("find_bug", "advanced",
     "This file path allows directory traversal. Find the vulnerability.",
     "<?php\n$name = $_GET['file'];\nreadfile('uploads/' . $name);",
     "allows reading arbitrary files",
     "Using user input in a path allows '../' traversal; validate with basename and an allowlist.",
     "Concatenating user input into a filesystem path without sanitization.",
     "<?php\n$name = basename($_GET['file'] ?? '');\nif (!preg_match('/^[\\w.-]+$/', $name)) { exit('bad'); }\nreadfile('uploads/' . $name);",
     "assertEquals('passwd', basename('../../etc/passwd'));"),
    ("code_explanation", "advanced",
     "Explain the security of unserialize versus json_decode.",
     "<?php\n$obj = json_decode($json, true);",
     "returns an array; safer than unserialize",
     "unserialize can instantiate arbitrary classes and trigger magic methods, so JSON is preferred for untrusted data.",
     "Using unserialize on user-supplied data, which enables object injection attacks.",
     None,
     "assertIsArray(json_decode('[]', true));"),
    ("code_generation", "intermediate",
     "Write code that lists all .txt files in a directory.",
     "<?php\nforeach (glob('/tmp/*.txt') as $f) {\n    echo basename($f), \"\\n\";\n}",
     "each txt filename",
     "glob returns the paths matching the pattern; basename strips the directory.",
     "Using opendir/readdir and forgetting to skip '.' and '..'.",
     None,
     "assertIsArray(glob('/tmp/*.txt'));"),
    ("code_generation", "advanced",
     "Write code that streams a large file to the client in chunks.",
     "<?php\n$fh = fopen('big.bin', 'rb');\nwhile (!feof($fh)) {\n    echo fread($fh, 8192);\n    flush();\n}\nfclose($fh);",
     "the file streamed in chunks",
     "Reading and echoing fixed-size chunks keeps memory bounded for large downloads.",
     "Reading the whole file into memory with file_get_contents for a large download.",
     None,
     "assertIsResource(fopen('php://memory', 'rb'));"),
    ("code_generation", "intermediate",
     "Write code that reads a CSV file into arrays.",
     "<?php\n$fh = fopen('d.csv', 'r');\nwhile (($row = fgetcsv($fh)) !== false) {\n    print_r($row);\n}\nfclose($fh);",
     "each CSV row as an array",
     "fgetcsv parses a line into fields, handling quoted values and delimiters.",
     "Using explode(',') on each line, which breaks on quoted commas.",
     None,
     "assertIsArray(str_getcsv('a,b'));"),
    ("find_bug", "intermediate",
     "This JSON output has unescaped unicode causing issues. Find the fix.",
     "<?php\necho json_encode(['emoji' => '\\u{1F600}']);",
     "{\"emoji\":\"\\ud83d\\ude00\"}",
     "By default json_encode escapes non-ASCII to \\u sequences; add JSON_UNESCAPED_UNICODE to keep them readable.",
     "Expecting json_encode to output raw UTF-8 without the flag.",
     "<?php\necho json_encode(['emoji' => '\\u{1F600}'], JSON_UNESCAPED_UNICODE);",
     "assertStringContainsString('emoji', json_encode(['emoji'=>'x']));"),
    ("code_explanation", "beginner",
     "Explain the modes 'r', 'w' and 'a' in fopen.",
     "<?php\n$fh = fopen('d.txt', 'a');",
     "opens for appending",
     "r reads from the start, w truncates or creates for writing, and a appends without truncating.",
     "Using 'w' when appending is intended, which erases existing content.",
     None,
     "assertIsResource(fopen('php://memory', 'a'));"),
    ("code_generation", "advanced",
     "Write code that writes JSON to a file with a lock to avoid concurrent corruption.",
     "<?php\nfile_put_contents('s.json', json_encode(['n' => 1]), LOCK_EX);",
     "writes with an exclusive lock",
     "The LOCK_EX flag takes an exclusive lock during the write, preventing concurrent writers from interleaving.",
     "Writing without a lock, allowing partial or corrupted output under concurrency.",
     None,
     "assertNotFalse(json_encode(['n'=>1]));"),
    ("code_generation", "intermediate",
     "Write code that copies a file and reports success.",
     "<?php\necho copy('src.txt', 'dst.txt') ? 'copied' : 'failed';",
     "copied or failed",
     "copy returns a boolean indicating whether the copy succeeded.",
     "Assuming copy throws on failure; it returns false with a warning.",
     None,
     "assertIsBool(copy('php://memory', 'php://memory'));"),
    ("code_generation", "beginner",
     "Write code that gets the size of a file.",
     "<?php\necho filesize('/tmp/d.txt');",
     "the size in bytes",
     "filesize returns the file size in bytes.",
     "Caching the size when the file changes, which gives stale results.",
     None,
     "assertIsInt(@filesize('php://memory') ?: 0);"),
    ("find_bug", "advanced",
     "This concurrent counter loses updates. Find the bug.",
     "<?php\n$n = (int) file_get_contents('count.txt');\nfile_put_contents('count.txt', $n + 1);",
     "lost updates under concurrency",
     "Read-modify-write without locking races; use flock around the whole operation.",
     "Performing an unsynchronized read-modify-write on a shared file.",
     "<?php\n$fh = fopen('count.txt', 'c+');\nflock($fh, LOCK_EX);\n$n = (int) stream_get_contents($fh);\nftruncate($fh, 0);\nrewind($fh);\nfwrite($fh, (string)($n + 1));\nflock($fh, LOCK_UN);\nfclose($fh);",
     "assertIsBool(true);"),
    ("code_explanation", "intermediate",
     "Explain why we use stream_get_contents after rewind.",
     "<?php\n$fh = fopen('d.txt', 'r');\nrewind($fh);\necho stream_get_contents($fh);",
     "the file contents",
     "rewind moves the pointer back to the start so stream_get_contents reads from the beginning.",
     "Reading without rewinding after earlier reads, which yields an empty string.",
     None,
     "assertIsResource(fopen('php://memory', 'r'));"),
    ("code_generation", "intermediate",
     "Write code that deletes a file if it exists.",
     "<?php\nif (is_file('old.txt')) {\n    unlink('old.txt');\n}\necho 'done';",
     "done",
     "unlink removes a file; guarding with is_file avoids a warning when it is missing.",
     "Calling unlink unconditionally, which warns when the file is absent.",
     None,
     "assertEquals('done', 'done');"),
    ("code_generation", "advanced",
     "Write code that validates and safely writes uploaded file contents to a fixed name.",
     "<?php\n$data = file_get_contents($_FILES['f']['tmp_name']);\nif (strlen($data) > 1024 * 1024) { exit('too big'); }\nfile_put_contents('uploads/safe.bin', $data);",
     "writes to a fixed safe name",
     "Reading the temp file and writing to a server-chosen name avoids trusting the client filename and path.",
     "Using the client-supplied filename directly, enabling path traversal or overwriting.",
     None,
     "assertIsString('safe.bin');"),
]

FILES_JSON = FILES_JSON[:25]