# -*- coding: utf-8 -*-
"""REST APIs (15)."""

REST_API = [
    ("code_generation", "intermediate",
     "Write code that returns a JSON response with the correct header and status.",
     "<?php\nhttp_response_code(200);\nheader('Content-Type: application/json');\necho json_encode(['ok' => true]);",
     "{\"ok\":true}",
     "Setting the status code and Content-Type header before echoing the JSON body produces a correct API response.",
     "Forgetting the Content-Type header, so clients treat the body as plain text.",
     None,
     "assertStringContainsString('application/json', 'Content-Type: application/json');"),
    ("code_generation", "intermediate",
     "Write code that reads the HTTP method and routes to a handler.",
     "<?php\n$method = $_SERVER['REQUEST_METHOD'];\nswitch ($method) {\n    case 'GET': echo 'list'; break;\n    case 'POST': echo 'create'; break;\n    default: http_response_code(405); echo 'method not allowed';\n}",
     "list, create or method not allowed",
     "Branching on REQUEST_METHOD implements basic routing; 405 signals an unsupported method.",
     "Ignoring the method and treating every request the same.",
     None,
     "assertTrue(true);"),
    ("code_explanation", "intermediate",
     "Explain what a REST resource URL and method pair represent.",
     "<?php\n// GET /users      -> list\n// POST /users     -> create\n// GET /users/1    -> read one\n",
     "CRUD mapping to methods on a resource",
     "REST maps HTTP methods to operations on a resource identified by the URL path.",
     "Putting verbs like /getUser in the path instead of using HTTP methods.",
     None,
     "assertTrue(true);"),
    ("code_generation", "advanced",
     "Write code that parses a JSON request body and validates required fields.",
     "<?php\n$in = json_decode(file_get_contents('php://input'), true) ?? [];\nif (!isset($in['email'])) {\n    http_response_code(422);\n    echo json_encode(['error' => 'email required']);\n    exit;\n}",
     "422 with an error object when email is missing",
     "Reading php://input gets the raw body; validating required fields returns a 422 Unprocessable Entity on failure.",
     "Using $_POST to read a JSON body, which is empty for application/json requests.",
     None,
     "assertEquals(422, 422);"),
    ("find_bug", "intermediate",
     "This endpoint returns HTML on error instead of JSON. Find the bug.",
     "<?php\nif (!$user) {\n    die('User not found');\n}",
     "plain text/HTML error",
     "Using die() with a string breaks the JSON contract; return a JSON error with the proper status code.",
     "Returning free-form text from a JSON API endpoint.",
     "<?php\nif (!$user) {\n    http_response_code(404);\n    echo json_encode(['error' => 'not found']);\n    exit;\n}",
     "assertEquals(404, 404);"),
    ("code_generation", "intermediate",
     "Write code that sets a Location header for a created resource and returns 201.",
     "<?php\nhttp_response_code(201);\nheader('Location: /users/42');\necho json_encode(['id' => 42]);",
     "201 with a Location header",
     "201 Created with a Location header is the conventional response after creating a resource.",
     "Returning 200 for a creation instead of 201.",
     None,
     "assertEquals(201, 201);"),
    ("code_explanation", "advanced",
     "Explain the role of the Accept and Content-Type headers.",
     "<?php\n$accept = $_SERVER['HTTP_ACCEPT'] ?? '*/*';\n$ctype = $_SERVER['CONTENT_TYPE'] ?? '';",
     "content negotiation and request format",
     "Accept tells the server the desired response format; Content-Type tells it the format of the request body.",
     "Ignoring these headers and assuming JSON in and out.",
     None,
     "assertTrue(true);"),
    ("code_generation", "advanced",
     "Write code that returns a paginated JSON list with metadata.",
     "<?php\n$page = max(1, (int) ($_GET['page'] ?? 1));\n$per = 20;\n$rows = []; // from PDO with LIMIT/OFFSET\nheader('Content-Type: application/json');\necho json_encode(['page' => $page, 'per_page' => $per, 'data' => $rows]);",
     "a JSON object with page, per_page and data",
     "Wrapping the list with pagination metadata helps clients navigate large collections.",
     "Returning a bare array without pagination context, making it hard to page.",
     None,
     "assertStringContainsString('per_page', 'per_page');"),
    ("find_bug", "advanced",
     "This API leaks internal error details. Find the bug.",
     "<?php\ntry {\n    doWork();\n} catch (Throwable $e) {\n    echo json_encode(['error' => $e->getMessage(), 'trace' => $e->getTraceAsString()]);\n}",
     "leaks stack traces",
     "Exposing the message and trace reveals internals; log them and return a generic error with a correlation id.",
     "Including exception messages and stack traces in API responses.",
     "<?php\ntry {\n    doWork();\n} catch (Throwable $e) {\n    error_log((string) $e);\n    http_response_code(500);\n    echo json_encode(['error' => 'internal error']);\n}",
     "assertEquals(500, 500);"),
    ("code_generation", "intermediate",
     "Write code that returns 204 No Content for a successful delete.",
     "<?php\nhttp_response_code(204);\n// no body",
     "204 with an empty body",
     "204 signals success with no response body, appropriate for deletes.",
     "Returning a 200 with a body for a delete, which is not wrong but less conventional.",
     None,
     "assertEquals(204, 204);"),
    ("code_explanation", "intermediate",
     "Explain the meaning of common REST status codes here.",
     "<?php\n// 200 OK, 201 Created, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 500 Server Error",
     "standard HTTP status semantics",
     "Each status communicates a specific outcome: 4xx for client errors and 5xx for server errors.",
     "Using 200 for every response regardless of the actual outcome.",
     None,
     "assertEquals(404, 404);"),
    ("code_generation", "advanced",
     "Write code that implements a simple token check for an API request.",
     "<?php\n$auth = $_SERVER['HTTP_AUTHORIZATION'] ?? '';\nif (!str_starts_with($auth, 'Bearer ')) {\n    http_response_code(401);\n    exit;\n}\n$token = substr($auth, 7);",
     "401 when the Bearer token is missing",
     "Reading the Authorization header and checking the Bearer scheme is a common API authentication pattern.",
     "Accepting tokens from a query string, which leaks them into logs and referrers.",
     None,
     "assertTrue(str_starts_with('Bearer x', 'Bearer '));"),
    ("code_generation", "intermediate",
     "Write code that returns a 405 with an Allow header for an unsupported method.",
     "<?php\nheader('Allow: GET, POST');\nhttp_response_code(405);\necho json_encode(['error' => 'method not allowed']);",
     "405 with an Allow header",
     "The Allow header lists the methods the resource supports, complementing the 405 status.",
     "Returning 404 for an unsupported method when the resource exists.",
     None,
     "assertStringContainsString('GET', 'Allow: GET, POST');"),
    ("find_bug", "intermediate",
     "This endpoint does not set a status code for not found. Find the bug.",
     "<?php\nif (!$row) {\n    echo json_encode(['error' => 'not found']);\n}",
     "200 with an error body",
     "Without setting the status code, the response is 200 even though the resource was not found; set 404.",
     "Relying on the response body alone to signal errors instead of the HTTP status.",
     "<?php\nif (!$row) {\n    http_response_code(404);\n    echo json_encode(['error' => 'not found']);\n}",
     "assertEquals(404, 404);"),
    ("code_explanation", "advanced",
     "Explain why APIs should be stateless.",
     "<?php\n// each request carries its own auth token; no server session state\n",
     "statelessness improves scalability",
     "Stateless APIs do not rely on server-side session state, so any server can handle any request and scaling is simpler.",
     "Storing per-client state in server memory, which breaks behind a load balancer.",
     None,
     "assertTrue(true);"),
]

REST_API = REST_API[:15]