# -*- coding: utf-8 -*-
"""Security & Secure Coding (10)."""

SECURITY = [
    ("security_improvement", "intermediate",
     "Improve this code to prevent SQL injection.",
     "<?php\n$pdo->query(\"SELECT * FROM users WHERE email = '\" . $_POST['email'] . \"'\");",
     "a parameterized query",
     "Binding the value as a parameter separates data from SQL, eliminating injection.",
     "Escaping quotes manually instead of using prepared statements.",
     "<?php\n$stmt = $pdo->prepare('SELECT * FROM users WHERE email = :email');\n$stmt->execute([':email' => $_POST['email']]);",
     "assertStringContainsString(':email', 'SELECT * FROM users WHERE email = :email');"),
    ("security_improvement", "intermediate",
     "Improve this output to prevent XSS.",
     "<?php\necho '<p>' . $_GET['name'] . '</p>';",
     "escaped output",
     "Escaping with htmlspecialchars before echoing prevents injected scripts from executing.",
     "Relying on strip_tags which is not sufficient for all contexts.",
     "<?php\necho '<p>' . htmlspecialchars($_GET['name'] ?? '', ENT_QUOTES, 'UTF-8') . '</p>';",
     "assertStringContainsString('&lt;', htmlspecialchars('<'));"),
    ("code_explanation", "advanced",
     "Explain why hashing passwords with md5 is unsafe.",
     "<?php\n$hash = md5($password);",
     "fast, unsalted, collision-prone",
     "md5 is fast and unsalted, making it trivial to brute-force with rainbow tables; use password_hash with a strong algorithm.",
     "Believing adding a static salt to md5 makes it secure.",
     "<?php\n$hash = password_hash($password, PASSWORD_DEFAULT);",
     "assertNotEquals(md5('x'), password_hash('x', PASSWORD_DEFAULT));"),
    ("security_improvement", "advanced",
     "Improve this password verification to be timing-safe and future-proof.",
     "<?php\nif (md5($input) == $storedHash) {\n    login();\n}",
     "use password_verify",
     "password_verify uses the algorithm embedded in the hash and compares safely; md5 comparison is insecure and loose.",
     "Comparing hashes with == and using a weak algorithm.",
     "<?php\nif (password_verify($input, $storedHash)) {\n    login();\n}",
     "assertTrue(password_verify('x', password_hash('x', PASSWORD_DEFAULT)));"),
    ("security_improvement", "advanced",
     "Improve this file include to prevent local file inclusion.",
     "<?php\ninclude $_GET['page'] . '.php';",
     "allowlist the page",
     "User-controlled include paths enable LFI/RFI; map input to a fixed allowlist of known pages.",
     "Concatenating user input into an include path.",
     "<?php\n$pages = ['home', 'about'];\n$page = in_array($_GET['page'] ?? '', $pages, true) ? $_GET['page'] : 'home';\ninclude $page . '.php';",
     "assertTrue(in_array('home', ['home','about'], true));"),
    ("code_explanation", "advanced",
     "Explain why trusting the X-Forwarded-For header blindly is risky.",
     "<?php\n$ip = $_SERVER['HTTP_X_FORWARDED_FOR'] ?? $_SERVER['REMOTE_ADDR'];",
     "clients can spoof the header",
     "X-Forwarded-For is client-controllable unless set by a trusted proxy; use it only when a known proxy rewrites it.",
     "Using a spoofable header for access control or rate limiting.",
     None,
     "assertTrue(isset($_SERVER['REMOTE_ADDR']) || true);"),
    ("security_improvement", "intermediate",
     "Improve this code to protect against CSRF.",
     "<?php\nif ($_POST['amount']) {\n    transfer($_POST['amount']);\n}",
     "add a CSRF token check",
     "A per-session token compared with hash_equals blocks cross-site forged submissions.",
     "Relying only on the request method without a token.",
     "<?php\nsession_start();\nif (!hash_equals($_SESSION['csrf'] ?? '', $_POST['csrf'] ?? '')) {\n    http_response_code(403);\n    exit;\n}\ntransfer((float) $_POST['amount']);",
     "assertTrue(hash_equals('t', 't'));"),
    ("security_improvement", "advanced",
     "Improve this upload handling to prevent executing uploaded code.",
     "<?php\nmove_uploaded_file($_FILES['f']['tmp_name'], 'uploads/' . $_FILES['f']['name']);",
     "validate type and rename",
     "Validate the real image type and store under a server-generated name outside the web root or with execution disabled.",
     "Trusting the client filename and extension for uploads.",
     "<?php\nif (getimagesize($_FILES['f']['tmp_name']) === false) { exit('not an image'); }\n$dest = 'uploads/' . bin2hex(random_bytes(8)) . '.jpg';\nmove_uploaded_file($_FILES['f']['tmp_name'], $dest);",
     "assertFalse(@getimagesize('nope'));"),
    ("code_explanation", "advanced",
     "Explain why disabling dangerous functions helps defense in depth.",
     "<?php\n// php.ini: disable_functions = exec,passthru,shell_exec,system",
     "reduces the impact of a compromise",
     "Disabling functions that execute shell commands limits what an attacker can do if code execution is achieved.",
     "Relying on disable_functions as the only protection against command injection.",
     None,
     "assertTrue(true);"),
    ("security_improvement", "intermediate",
     "Improve this code that stores a secret in the source.",
     "<?php\n$apiKey = 'sk_live_1234567890';",
     "load the secret from the environment",
     "Hard-coded secrets leak through version control; read them from environment variables or a secret store.",
     "Committing API keys and passwords into the repository.",
     "<?php\n$apiKey = getenv('API_KEY');\nif ($apiKey === false) { throw new RuntimeException('API_KEY missing'); }",
     "assertEquals('false', getenv('MISSING_X') ?: 'false');"),
]

SECURITY = SECURITY[:10]