# -*- coding: utf-8 -*-
"""Functions (40)."""

FUNCTIONS = [
    ("code_generation", "beginner",
     "Write a function that returns the sum of two integers with type declarations.",
     "<?php\nfunction add(int $a, int $b): int {\n    return $a + $b;\n}\necho add(2, 3);",
     "5",
     "Parameter and return type declarations document the contract and enforce it at call time.",
     "Omitting the return type and letting PHP infer, which hides intent.",
     None,
     "assertEquals(5, add(2, 3));"),
    ("code_generation", "beginner",
     "Write a function with a default parameter value.",
     "<?php\nfunction greet(string $name = 'world'): string {\n    return \"Hello, $name\";\n}\necho greet();",
     "Hello, world",
     "A default value is used when the caller omits the argument.",
     "Placing a parameter with a default before a required parameter, which is deprecated.",
     None,
     "assertEquals('Hello, world', greet());"),
    ("code_explanation", "intermediate",
     "Explain the difference between passing by value and by reference.",
     "<?php\nfunction byVal($n) { $n++; }\nfunction byRef(&$n) { $n++; }\n$x = 1;\nbyVal($x);\nbyRef($x);\necho $x;",
     "2",
     "byVal works on a copy so $x is unchanged; byRef modifies the caller's variable through the reference.",
     "Forgetting the & and expecting the caller's variable to change.",
     None,
     "assertEquals(2, $x);"),
    ("code_generation", "intermediate",
     "Write a variadic function that returns the count of its arguments.",
     "<?php\nfunction howMany(...$args): int {\n    return count($args);\n}\necho howMany(1, 2, 3);",
     "3",
     "The variadic ...$args collects all passed arguments into an array.",
     "Using func_get_args() when a variadic parameter is clearer and typed.",
     None,
     "assertEquals(3, howMany(1,2,3));"),
    ("predict_output", "intermediate",
     "What is printed by this nested function call?",
     "<?php\nfunction f($x) {\n    return $x * 2;\n}\necho f(f(2));",
     "8",
     "The inner call f(2) returns 4, and the outer call doubles that to 8.",
     "Evaluating the outer call before the inner, which would give the wrong result.",
     None,
     "assertEquals(8, f(f(2)));"),
    ("find_bug", "intermediate",
     "This function should return a value but returns null. Find the bug.",
     "<?php\nfunction double($n) {\n    $n * 2;\n}\nvar_dump(double(3));",
     "NULL",
     "The function computes $n * 2 but never returns it, so the implicit return value is null.",
     "Forgetting the return keyword and expecting the last expression to be returned.",
     "<?php\nfunction double($n) {\n    return $n * 2;\n}\nvar_dump(double(3));",
     "assertEquals(6, double(3));"),
    ("code_generation", "intermediate",
     "Write an arrow function that squares its argument.",
     "<?php\n$square = fn($n) => $n * $n;\necho $square(4);",
     "16",
     "An arrow function is a concise anonymous function that automatically captures outer variables by value.",
     "Writing a block body in an arrow function, which is not allowed; it must be a single expression.",
     None,
     "assertEquals(16, $square(4));"),
    ("code_explanation", "advanced",
     "Explain what static variables do inside a function.",
     "<?php\nfunction counter() {\n    static $n = 0;\n    return ++$n;\n}\necho counter(), counter(), counter();",
     "123",
     "A static variable keeps its value between calls, so the counter increments across invocations.",
     "Expecting the static variable to reset to 0 on every call.",
     None,
     "assertEquals('123', counter() . counter() . counter());"),
    ("code_generation", "beginner",
     "Write a function that has no return value and just echoes.",
     "<?php\nfunction sayHi(): void {\n    echo 'hi';\n}\nsayHi();",
     "hi",
     "A void return type documents that the function performs a side effect and returns nothing.",
     "Trying to use the result of a void function as a value.",
     None,
     "assertEquals('hi', $out);"),
    ("code_generation", "intermediate",
     "Write a recursive function that computes the factorial of n.",
     "<?php\nfunction fact(int $n): int {\n    return $n <= 1 ? 1 : $n * fact($n - 1);\n}\necho fact(5);",
     "120",
     "The base case returns 1 for n<=1; otherwise it multiplies n by the factorial of n-1.",
     "Omitting the base case, which causes infinite recursion and a stack overflow.",
     None,
     "assertEquals(120, fact(5));"),
    ("predict_output", "advanced",
     "What is printed when a middle default argument is overridden?",
     "<?php\nfunction add($a, $b = 1, $c = 2) {\n    return $a + $b + $c;\n}\necho add(1, 5);",
     "8",
     "Only $b is overridden; $c keeps its default 2, so 1+5+2 equals 8.",
     "Assuming that passing a later argument also requires passing earlier defaults.",
     None,
     "assertEquals(8, add(1, 5));"),
    ("code_generation", "advanced",
     "Write a function that returns multiple values via an array.",
     "<?php\nfunction minMax(array $n): array {\n    return [min($n), max($n)];\n}\n[$lo, $hi] = minMax([3, 1, 2]);\necho \"$lo-$hi\";",
     "1-3",
     "PHP functions return one value; returning an array lets the caller destructure several results.",
     "Trying to return two values with a comma, which is a syntax error.",
     None,
     "assertEquals('1-3', $out);"),
    ("code_explanation", "intermediate",
     "Explain how callable parameters work here.",
     "<?php\nfunction apply(callable $fn, $x) {\n    return $fn($x);\n}\necho apply('strtoupper', 'hi');",
     "HI",
     "A callable type accepts a function name, closure, or array callable and invokes it inside the function.",
     "Passing a plain string that is not a valid function name, which fails at call time.",
     None,
     "assertEquals('HI', apply('strtoupper', 'hi'));"),
    ("code_generation", "intermediate",
     "Write a function that uses a closure with the use keyword to capture a variable.",
     "<?php\n$prefix = 'ID-';\n$make = function($n) use ($prefix) {\n    return $prefix . $n;\n};\necho $make(7);",
     "ID-7",
     "The use clause imports the outer variable into the closure's scope by value.",
     "Forgetting use, so $prefix is undefined inside the closure.",
     None,
     "assertEquals('ID-7', $make(7));"),
    ("code_generation", "advanced",
     "Write a closure that captures a variable by reference so later changes are visible.",
     "<?php\n$count = 0;\n$inc = function() use (&$count) {\n    $count++;\n};\n$inc(); $inc();\necho $count;",
     "2",
     "Capturing by reference with use (&$count) lets the closure modify the outer variable.",
     "Capturing by value, which copies the variable and leaves the outer one unchanged.",
     None,
     "assertEquals(2, $count);"),
    ("find_bug", "beginner",
     "This function should greet by name but prints an empty name. Find the bug.",
     "<?php\nfunction greet($name) {\n    echo \"Hi, $name\";\n}\ngreet();",
     "Warning and 'Hi, '",
     "greet() is called without the required argument, so $name is undefined; pass the argument or provide a default.",
     "Calling a function without a required argument.",
     "<?php\nfunction greet($name = 'guest') {\n    echo \"Hi, $name\";\n}\ngreet();",
     "assertEquals('Hi, guest', $out);"),
    ("code_generation", "intermediate",
     "Write a function that filters an array using a callback passed in.",
     "<?php\nfunction keep(array $items, callable $test): array {\n    return array_values(array_filter($items, $test));\n}\nprint_r(keep([1,2,3,4], fn($n) => $n % 2 === 0));",
     "[2,4]",
     "The function delegates the decision to the callback and reindexes the filtered result.",
     "Returning array_filter directly, which preserves the original keys.",
     None,
     "assertEquals([2,4], keep([1,2,3,4], fn($n)=>$n%2===0));"),
    ("predict_output", "beginner",
     "What is printed when a numeric string is passed to a typed parameter?",
     "<?php\nfunction f(int $x): int { return $x + 1; }\necho f('5');",
     "6",
     "Without strict_types the string '5' is coerced to int 5, then incremented to 6.",
     "Expecting a TypeError; coercion happens unless strict_types=1 is declared.",
     None,
     "assertEquals(6, f('5'));"),
    ("code_generation", "advanced",
     "Write a function with a nullable return type and a guard clause.",
     "<?php\nfunction findUser(array $users, int $id): ?array {\n    foreach ($users as $u) {\n        if ($u['id'] === $id) {\n            return $u;\n        }\n    }\n    return null;\n}\nvar_dump(findUser([], 1));",
     "NULL",
     "The ?array return type allows null; the guard returns null when no match is found.",
     "Returning false for a not-found case while the declared type is ?array, causing a TypeError.",
     None,
     "assertNull(findUser([], 1));"),
    ("code_explanation", "beginner",
     "Explain the difference between a function and a method.",
     "<?php\nfunction fn1() { return 1; }\nclass C { public function fn2() { return 2; } }\necho fn1() + (new C())->fn2();",
     "3",
     "A function is standalone; a method belongs to a class and is called on an instance or statically.",
     "Calling a method without an object or class context.",
     None,
     "assertEquals(3, fn1() + (new C())->fn2());"),
    ("code_generation", "intermediate",
     "Write a function that returns a closure capturing its argument.",
     "<?php\nfunction multiplier(int $factor): callable {\n    return fn($n) => $n * $factor;\n}\n$double = multiplier(2);\necho $double(5);",
     "10",
     "The outer function returns a closure that captures $factor, forming a simple factory.",
     "Using a plain function name instead of returning a closure.",
     None,
     "assertEquals(10, multiplier(2)(5));"),
    ("code_generation", "beginner",
     "Write a function that returns a boolean based on a numeric check.",
     "<?php\nfunction isAdult(int $age): bool {\n    return $age >= 18;\n}\nvar_dump(isAdult(20));",
     "bool(true)",
     "The comparison already yields a boolean, which the return type enforces.",
     "Wrapping the comparison in an if/else and returning true/false explicitly, which is verbose.",
     None,
     "assertTrue(isAdult(20));"),
    ("predict_output", "advanced",
     "What is printed by this function that returns early?",
     "<?php\nfunction f($n) {\n    if ($n < 0) {\n        return 'neg';\n    }\n    return 'non-neg';\n}\necho f(-1), f(1);",
     "negnon-neg",
     "The guard returns 'neg' for -1 and execution of the rest is skipped; otherwise 'non-neg' is returned.",
     "Expecting the function to run both return statements.",
     None,
     "assertEquals('negnon-neg', f(-1) . f(1));"),
    ("find_bug", "advanced",
     "This function should modify the array but the caller sees no change. Find the bug.",
     "<?php\nfunction addItem(array $items) {\n    $items[] = 'new';\n}\n$list = [];\naddItem($list);\nprint_r($list);",
     "Array ( )",
     "Arrays are passed by value, so appending inside the function does not affect the caller; pass by reference or return the new array.",
     "Expecting a function to mutate an array passed by value.",
     "<?php\nfunction addItem(array &$items) {\n    $items[] = 'new';\n}\n$list = [];\naddItem($list);\nprint_r($list);",
     "assertEquals(['new'], $list);"),
    ("code_generation", "advanced",
     "Write a function that uses a generator to yield an infinite sequence, then take three values.",
     "<?php\nfunction nums() {\n    $i = 0;\n    while (true) {\n        yield $i++;\n    }\n}\n$out = [];\nforeach (nums() as $n) {\n    if ($n > 2) break;\n    $out[] = $n;\n}\nprint_r($out);",
     "[0,1,2]",
     "The generator can be infinite; the consumer breaks out after collecting three values.",
     "Trying to materialize an infinite generator into an array, which exhausts memory.",
     None,
     "assertEquals([0,1,2], $out);"),
    ("code_explanation", "intermediate",
     "Explain strict_types effect on this function call.",
     "<?php\ndeclare(strict_types=1);\nfunction add(int $a, int $b): int { return $a + $b; }\nadd('1', 2);",
     "TypeError: Argument #1 must be of type int, string given",
     "With strict_types=1 the string '1' is not coerced to int, so a TypeError is thrown.",
     "Expecting coercion even under strict types; it applies to internal and user functions alike.",
     "<?php\ndeclare(strict_types=1);\nfunction add(int $a, int $b): int { return $a + $b; }\nadd(1, 2);",
     "assertEquals(3, add(1, 2));"),
    ("code_generation", "intermediate",
     "Write a function that accepts an array and returns it sorted without modifying the input.",
     "<?php\nfunction sorted(array $a): array {\n    sort($a);\n    return $a;\n}\n$orig = [3,1,2];\nprint_r(sorted($orig));\nprint_r($orig);",
     "[1,2,3] then [3,1,2]",
     "Because the array parameter is a copy, sorting inside the function does not affect the caller's array.",
     "Believing sort() inside the function also sorts the caller's array.",
     None,
     "assertEquals([1,2,3], sorted([3,1,2]));"),
    ("predict_output", "intermediate",
     "What is printed by composing two functions?",
     "<?php\nfunction g($x) { return $x; }\nfunction h($x) { return g($x) + 1; }\necho h(g(1));",
     "2",
     "g(1) returns 1; h receives 1 and returns g(1)+1 which is 1+1 equals 2.",
     "Double-counting the nested call and getting 3.",
     None,
     "assertEquals(2, h(g(1)));"),
    ("code_review", "intermediate",
     "Review this function that does too many things.",
     "<?php\nfunction process($data) {\n    $data = trim($data);\n    $data = strtoupper($data);\n    saveToDb($data);\n    sendEmail($data);\n    return $data;\n}",
     "processes, saves and emails",
     "A function with several side effects is hard to test and reuse; split into a transformation and separate side-effect calls.",
     "Mixing pure transformation with side effects in one function.",
     "<?php\nfunction normalize($data) { return strtoupper(trim($data)); }\n// then call saveToDb and sendEmail separately",
     "assertEquals('HI', normalize(' hi '));"),
    ("code_generation", "beginner",
     "Write a function that uses a named argument at the call site.",
     "<?php\nfunction box(int $w, int $h): string {\n    return \"{$w}x{$h}\";\n}\necho box(h: 2, w: 4);",
     "4x2",
     "Named arguments let the caller pass values in any order by parameter name.",
     "Using named arguments before a positional one, which is not allowed after a named argument.",
     None,
     "assertEquals('4x2', box(h: 2, w: 4));"),
    ("code_explanation", "advanced",
     "Explain first-class callable syntax here.",
     "<?php\n$up = strtoupper(...);\necho $up('abc');",
     "ABC",
     "strtoupper(...) creates a Closure for the function, which can be stored and called later.",
     "Writing a wrapping closure when the first-class callable syntax suffices.",
     None,
     "assertEquals('ABC', $up('abc'));"),
    ("find_bug", "intermediate",
     "This recursive function never stops. Find the bug.",
     "<?php\nfunction down($n) {\n    echo $n;\n    if ($n == 0) return;\n    down($n);\n}",
     "infinite output",
     "The recursive call passes $n unchanged instead of $n - 1, so the base case is never reached.",
     "Recursing with the same argument, which prevents progress toward the base case.",
     "<?php\nfunction down($n) {\n    echo $n;\n    if ($n == 0) return;\n    down($n - 1);\n}",
     "assertEquals('210', down(2));"),
    ("code_generation", "advanced",
     "Write a function that memoizes results using a static cache.",
     "<?php\nfunction fib(int $n): int {\n    static $cache = [];\n    if (isset($cache[$n])) return $cache[$n];\n    return $cache[$n] = $n < 2 ? $n : fib($n-1) + fib($n-2);\n}\necho fib(10);",
     "55",
     "The static cache stores computed values so repeated calls avoid recomputation.",
     "Storing the cache outside the function without keying by argument, causing incorrect reuse.",
     None,
     "assertEquals(55, fib(10));"),
    ("predict_output", "beginner",
     "What is printed when a function's return value is used in an expression?",
     "<?php\nfunction f() { return 1; }\n$r = f();\necho $r + 1;",
     "2",
     "The function returns 1, stored in $r, then incremented by 1 to print 2.",
     "Confusing the returned value with the function name.",
     None,
     "assertEquals(2, f() + 1);"),
    ("code_generation", "intermediate",
     "Write a function that returns a string with a default for a missing key.",
     "<?php\nfunction field(array $row, string $key, string $default = ''): string {\n    return $row[$key] ?? $default;\n}\necho field([], 'name', 'n/a');",
     "n/a",
     "The null coalescing operator supplies the default when the key is missing.",
     "Using isset with a ternary, which is more verbose than ??.",
     None,
     "assertEquals('n/a', field([], 'name', 'n/a'));"),
    ("code_explanation", "beginner",
     "Explain the scope of variables inside a function.",
     "<?php\n$x = 10;\nfunction show() {\n    echo $x ?? 'undefined';\n}\nshow();",
     "undefined",
     "Function bodies have their own scope; the global $x is not visible unless imported with global or passed in.",
     "Expecting a function to read global variables automatically.",
     None,
     "assertEquals('undefined', $out);"),
    ("code_generation", "beginner",
     "Write a function that returns the larger of two numbers.",
     "<?php\nfunction max2(int $a, int $b): int {\n    return $a > $b ? $a : $b;\n}\necho max2(3, 9);",
     "9",
     "The ternary returns the greater of the two operands.",
     "Using >= which returns $a on ties, usually harmless but note the tie behavior.",
     None,
     "assertEquals(9, max2(3, 9));"),
    ("code_review", "advanced",
     "Review this function for a hidden side effect in a default argument.",
     "<?php\nfunction now(string $t = null): string {\n    return $t ?? date('Y-m-d');\n}",
     "today's date",
     "Using date() inside the function is fine, but a mutable default evaluated at call time can hide behavior; document it or accept an injected value for testability.",
     "Relying on an implicit 'current time' default that makes tests non-deterministic.",
     "<?php\nfunction now(string $t): string {\n    return $t;\n}\n// pass date('Y-m-d') explicitly for testability",
     "assertEquals('2020-01-01', now('2020-01-01'));"),
    ("code_generation", "intermediate",
     "Write a function that uses union return types to return an int or a string.",
     "<?php\nfunction id(int|string $v): int|string {\n    return is_int($v) ? $v : strtoupper($v);\n}\necho id('a'), id(2);",
     "A2",
     "A union return type int|string allows either type, and the body branches on the actual input type.",
     "Returning an undeclared type from a union-typed function, which throws a TypeError.",
     None,
     "assertEquals('A2', id('a') . id(2));"),
    ("code_explanation", "advanced",
     "Explain the order in which PHP resolves a callable passed as a string.",
     "<?php\nfunction run(string $fn, int $n) {\n    return $fn($n);\n}\necho run('abs', -3);",
     "3",
     "The string 'abs' is a valid callable and is invoked with the argument, returning the absolute value.",
     "Assuming a string callable works even when the function does not exist, which throws a TypeError.",
     None,
     "assertEquals(3, run('abs', -3));"),
]

FUNCTIONS = FUNCTIONS[:40]