# -*- coding: utf-8 -*-
"""Error Handling & Exceptions (30)."""

EXCEPTIONS = [
    ("code_generation", "beginner",
     "Write a try/catch that catches a division-by-zero error from intdiv.",
     "<?php\ntry {\n    echo intdiv(10, 0);\n} catch (DivisionByZeroError $e) {\n    echo 'cannot divide by zero';\n}",
     "cannot divide by zero",
     "intdiv throws DivisionByZeroError for a zero divisor, which the catch block handles.",
     "Using / which triggers a warning and returns INF instead of throwing.",
     None,
     "assertEquals('cannot divide by zero', $out);"),
    ("code_explanation", "intermediate",
     "Explain the difference between Exception and Error.",
     "<?php\ntry {\n    throw new TypeError('bad type');\n} catch (Throwable $t) {\n    echo get_class($t);\n}",
     "TypeError",
     "Both Exception and Error implement Throwable; catching Throwable covers both, while catch(Exception) misses Errors.",
     "Catching only Exception and missing Error subclasses like TypeError.",
     None,
     "assertEquals('TypeError', get_class(new TypeError('x')));"),
    ("code_generation", "intermediate",
     "Write code that throws a custom exception with a message and catches it.",
     "<?php\nclass ValidationException extends RuntimeException {}\ntry {\n    throw new ValidationException('invalid input');\n} catch (ValidationException $e) {\n    echo $e->getMessage();\n}",
     "invalid input",
     "A custom exception extends a base exception, letting callers catch a specific domain error.",
     "Extending nothing and throwing a plain string, which is a fatal error.",
     None,
     "assertEquals('invalid input', (new ValidationException('invalid input'))->getMessage());"),
    ("find_bug", "intermediate",
     "This catch block never runs. Find the bug.",
     "<?php\ntry {\n    throw new RuntimeException('x');\n} catch (InvalidArgumentException $e) {\n    echo 'caught';\n}",
     "uncaught RuntimeException",
     "The thrown type RuntimeException is not a subclass of InvalidArgumentException, so the catch does not match.",
     "Catching a specific type that is unrelated to the thrown exception.",
     "<?php\ntry {\n    throw new RuntimeException('x');\n} catch (RuntimeException $e) {\n    echo 'caught';\n}",
     "assertEquals('caught', $out);"),
    ("code_generation", "advanced",
     "Write a try/catch/finally that always runs cleanup.",
     "<?php\ntry {\n    throw new Exception('boom');\n} catch (Exception $e) {\n    echo 'caught';\n} finally {\n    echo 'cleanup';\n}",
     "caughtcleanup",
     "The finally block runs regardless of whether an exception was thrown or caught.",
     "Putting cleanup only after the try, which is skipped when an exception propagates.",
     None,
     "assertEquals('caughtcleanup', $out);"),
    ("code_explanation", "beginner",
     "Explain what this code does when no exception is thrown.",
     "<?php\ntry {\n    $x = 1 + 1;\n} catch (Exception $e) {\n    echo 'error';\n}\necho $x;",
     "2",
     "With no exception, the catch is skipped and execution continues normally, printing 2.",
     "Expecting the catch to run unconditionally.",
     None,
     "assertEquals(2, $x);"),
    ("code_generation", "intermediate",
     "Write code that rethrows an exception after logging it.",
     "<?php\ntry {\n    throw new RuntimeException('db fail');\n} catch (RuntimeException $e) {\n    error_log($e->getMessage());\n    throw $e;\n}",
     "the exception is logged then rethrown",
     "Rethrowing with throw $e preserves the original exception after handling (e.g. logging).",
     "Throwing a new exception without the original as previous, losing the cause chain.",
     None,
     "assertEquals('db fail', (new RuntimeException('db fail'))->getMessage());"),
    ("code_generation", "advanced",
     "Write code that chains exceptions using the previous parameter.",
     "<?php\ntry {\n    try {\n        throw new RuntimeException('low-level');\n    } catch (RuntimeException $e) {\n        throw new DomainException('high-level', 0, $e);\n    }\n} catch (DomainException $e) {\n    echo $e->getPrevious()->getMessage();\n}",
     "low-level",
     "Passing the caught exception as the third argument to the new exception links them via getPrevious().",
     "Discarding the original exception, which hides the root cause.",
     None,
     "assertEquals('low-level', (new DomainException('h', 0, new RuntimeException('low-level')))->getPrevious()->getMessage());"),
    ("find_bug", "advanced",
     "This error handler swallows errors silently. Find the problem.",
     "<?php\nset_error_handler(function($no, $str) {\n    return true;\n});\ntrigger_error('lost', E_USER_WARNING);",
     "the warning is suppressed",
     "Returning true from the handler tells PHP the error is handled, so it is discarded; log or throw instead.",
     "Returning true to suppress errors without recording them.",
     "<?php\nset_error_handler(function($no, $str) {\n    error_log($str);\n    return true;\n});",
     "assertTrue(true);"),
    ("code_generation", "intermediate",
     "Write code that converts a warning into an exception.",
     "<?php\nset_error_handler(function($no, $str) {\n    throw new ErrorException($str, 0, $no);\n});\ntry {\n    $x = 1 / 0;\n} catch (ErrorException $e) {\n    echo 'converted';\n}",
     "converted",
     "The custom error handler throws an ErrorException for warnings, turning them into catchable exceptions.",
     "Forgetting that this affects all errors, including notices, unless filtered by severity.",
     None,
     "assertEquals('converted', $out);"),
    ("code_explanation", "intermediate",
     "Explain what getMessage and getCode return here.",
     "<?php\n$e = new Exception('oops', 42);\necho $e->getMessage(), '/', $e->getCode();",
     "oops/42",
     "The first constructor argument is the message and the second is the numeric code.",
     "Passing the code first and the message second, reversing the constructor arguments.",
     None,
     "assertEquals('oops/42', (new Exception('oops', 42))->getMessage() . '/' . (new Exception('oops', 42))->getCode());"),
    ("code_generation", "beginner",
     "Write code that uses a default catch for any Throwable.",
     "<?php\ntry {\n    throw new TypeError('bad');\n} catch (Throwable $t) {\n    echo 'handled';\n}",
     "handled",
     "Catching Throwable covers both Error and Exception hierarchies.",
     "Catching Exception only, which misses TypeError and other Errors.",
     None,
     "assertEquals('handled', $out);"),
    ("find_bug", "intermediate",
     "This function should return a default on failure but crashes. Find the bug.",
     "<?php\nfunction load($path) {\n    return file_get_contents($path);\n}\n$c = load('/no/such/file');",
     "Warning and false returned",
     "file_get_contents emits a warning and returns false; check the result and handle it, or use try/catch with a wrapper.",
     "Assuming file_get_contents throws instead of returning false with a warning.",
     "<?php\nfunction load($path) {\n    $c = @file_get_contents($path);\n    if ($c === false) {\n        throw new RuntimeException(\"cannot read $path\");\n    }\n    return $c;\n}",
     "assertFalse(@file_get_contents('/no/such/file'));"),
    ("code_generation", "advanced",
     "Write code that uses a multi-catch for two exception types.",
     "<?php\ntry {\n    throw new InvalidArgumentException('x');\n} catch (InvalidArgumentException | DomainException $e) {\n    echo 'either';\n}",
     "either",
     "A multi-catch with | handles several exception types in one block.",
     "Listing types separated by commas, which is a syntax error.",
     None,
     "assertEquals('either', $out);"),
    ("code_explanation", "advanced",
     "Explain the difference between throw expression and throw statement.",
     "<?php\n$v = $x ?? throw new RuntimeException('missing');",
     "throws when $x is null",
     "In PHP 8 throw is an expression, so it can appear in contexts like the right side of ?? or an arrow function.",
     "Assuming throw can only be used as a standalone statement.",
     None,
     "assertEquals(1, 1 ?? throw new RuntimeException('x'));"),
    ("code_generation", "intermediate",
     "Write code that validates input and throws a specific exception for each failure.",
     "<?php\nfunction check($n) {\n    if (!is_int($n)) {\n        throw new InvalidArgumentException('not int');\n    }\n    if ($n < 0) {\n        throw new DomainException('negative');\n    }\n    return $n;\n}\ntry {\n    check(-1);\n} catch (DomainException $e) {\n    echo $e->getMessage();\n}",
     "negative",
     "Different exception types communicate different failure reasons to callers.",
     "Throwing a generic Exception for every case, losing specificity.",
     None,
     "assertEquals('negative', $out);"),
    ("find_bug", "beginner",
     "This try/catch does not catch the error. Find the bug.",
     "<?php\ntry {\n    $r = 1 / 0;\n} catch (DivisionByZeroError $e) {\n    echo 'caught';\n}",
     "no output; 1/0 is a warning",
     "The / operator does not throw for zero division in PHP 8; it emits a warning and returns INF, so the catch never fires. Use intdiv or check the divisor.",
     "Assuming / throws DivisionByZeroError; only intdiv and % throw it.",
     "<?php\ntry {\n    $r = intdiv(1, 0);\n} catch (DivisionByZeroError $e) {\n    echo 'caught';\n}",
     "assertEquals('caught', $out);"),
    ("code_generation", "beginner",
     "Write code that sets a custom exception handler.",
     "<?php\nset_exception_handler(function(Throwable $e) {\n    echo 'Handled: ' . $e->getMessage();\n});\nthrow new RuntimeException('boom');",
     "Handled: boom",
     "set_exception_handler registers a callback for uncaught exceptions, preventing a raw fatal error output.",
     "Relying on the default handler, which prints a full stack trace to users.",
     None,
     "assertIsCallable(function(){});"),
    ("code_explanation", "intermediate",
     "Explain the finally block's behavior when returning.",
     "<?php\nfunction f() {\n    try {\n        return 1;\n    } finally {\n        echo 'cleanup';\n    }\n}\necho f();",
     "cleanup1",
     "The finally block runs before the function actually returns, so 'cleanup' prints before the return value 1.",
     "Expecting finally to be skipped when the try returns.",
     None,
     "assertEquals('cleanup1', $out);"),
    ("code_generation", "advanced",
     "Write code that uses assert to check a precondition in development.",
     "<?php\nini_set('zend.assertions', '1');\nassert(1 + 1 === 2, 'math broke');\necho 'ok';",
     "ok",
     "assert evaluates the condition and throws AssertionError when it fails and assertions are enabled.",
     "Using assert for input validation in production, where assertions are typically disabled.",
     None,
     "assertEquals('ok', $out);"),
    ("find_bug", "intermediate",
     "This code should report a friendly error but shows a stack trace. Find the bug.",
     "<?php\nfunction f() { throw new Exception('boom'); }\nf();",
     "uncaught exception fatal error",
     "The exception is never caught, so PHP's default handler prints an uncaught error; wrap the call in try/catch or set a handler.",
     "Throwing an exception without any catch or global handler.",
     "<?php\nfunction f() { throw new Exception('boom'); }\ntry {\n    f();\n} catch (Exception $e) {\n    echo $e->getMessage();\n}",
     "assertEquals('boom', (new Exception('boom'))->getMessage());"),
    ("code_generation", "intermediate",
     "Write code that retries an operation a few times before giving up.",
     "<?php\nfunction retry(callable $fn, int $times = 3) {\n    for ($i = 0; $i < $times; $i++) {\n        try {\n            return $fn();\n        } catch (Throwable $e) {\n            if ($i === $times - 1) {\n                throw $e;\n            }\n        }\n    }\n}\necho retry(fn() => 'ok');",
     "ok",
     "The loop retries on failure and rethrows only after the final attempt.",
     "Retrying forever without a maximum attempt limit.",
     None,
     "assertEquals('ok', $out);"),
    ("code_explanation", "beginner",
     "Explain what error_reporting does here.",
     "<?php\nerror_reporting(E_ALL);\nini_set('display_errors', '1');\n$a = $undefined;",
     "Warning about undefined variable, displayed",
     "error_reporting selects which error levels are reported and display_errors controls whether they are shown.",
     "Disabling error reporting entirely, which hides bugs during development.",
     None,
     "assertEquals(E_ALL, error_reporting(E_ALL));"),
    ("code_generation", "advanced",
     "Write code that logs an exception to a file and continues.",
     "<?php\ntry {\n    throw new RuntimeException('x');\n} catch (RuntimeException $e) {\n    error_log($e->getMessage() . \"\\n\", 3, 'app.log');\n}\necho 'continued';",
     "continued",
     "error_log with the message type 3 appends to the specified file, and execution continues after the catch.",
     "Using error_log without the file destination, which writes to the system log instead.",
     None,
     "assertEquals('continued', $out);"),
    ("find_bug", "advanced",
     "This validation throws but the message is lost. Find the bug.",
     "<?php\ntry {\n    throw new Exception('important');\n} catch (Exception $e) {\n    throw new Exception('generic');\n}",
     "generic (loses 'important')",
     "The original exception is discarded and replaced by a generic one; pass the original as previous or rethrow it.",
     "Replacing a specific exception with a generic one, losing the root cause.",
     "<?php\ntry {\n    throw new Exception('important');\n} catch (Exception $e) {\n    throw new Exception('generic', 0, $e);\n}",
     "assertEquals('important', (new Exception('g', 0, new Exception('important')))->getPrevious()->getMessage());"),
    ("code_generation", "intermediate",
     "Write code that uses a custom exception to carry extra context.",
     "<?php\nclass ApiException extends RuntimeException {\n    public function __construct(string $msg, public int $status = 500) {\n        parent::__construct($msg);\n    }\n}\ntry {\n    throw new ApiException('not found', 404);\n} catch (ApiException $e) {\n    echo $e->status;\n}",
     "404",
     "A promoted constructor property carries additional context (the status) alongside the message.",
     "Storing context in a global instead of on the exception itself.",
     None,
     "assertEquals(404, (new ApiException('x', 404))->status);"),
    ("code_explanation", "intermediate",
     "Explain why catching Throwable at the top level is common.",
     "<?php\ntry {\n    doWork();\n} catch (Throwable $e) {\n    error_log((string) $e);\n}",
     "logs any error or exception",
     "A top-level catch of Throwable acts as a safety net, logging any uncaught Error or Exception before the request ends.",
     "Using an empty catch block that hides all failures from operators.",
     None,
     "assertStringContainsString('Exception', (string) new Exception('x'));"),
    ("code_generation", "beginner",
     "Write code that throws and catches a ValueError from enum conversion.",
     "<?php\nenum E: int { case A = 1; }\ntry {\n    E::from(2);\n} catch (ValueError $e) {\n    echo 'invalid value';\n}",
     "invalid value",
     "Enum::from throws ValueError for a value that matches no case; tryFrom would return null instead.",
     "Using from() when an invalid value is expected, instead of the null-returning tryFrom().",
     None,
     "assertNull(E::tryFrom(2));"),
    ("find_bug", "intermediate",
     "This finally block overrides the return value unexpectedly. Find the bug.",
     "<?php\nfunction f() {\n    try {\n        return 1;\n    } finally {\n        return 2;\n    }\n}\necho f();",
     "2",
     "A return inside finally overrides the try's return value, silently changing behavior; avoid returning from finally.",
     "Returning from a finally block, which discards the original return value.",
     "<?php\nfunction f() {\n    try {\n        return 1;\n    } finally {\n        // no return here\n    }\n}\necho f();",
     "assertEquals(1, f());"),
    ("code_generation", "advanced",
     "Write code that wraps a legacy error-returning function into exceptions.",
     "<?php\nfunction must($result, string $ctx) {\n    if ($result === false) {\n        throw new RuntimeException(\"failed: $ctx\");\n    }\n    return $result;\n}\n$c = must('data', 'load');\necho $c;",
     "data",
     "The helper converts false-returning functions into exceptions, unifying error handling.",
     "Ignoring false returns from legacy functions and letting errors slip through.",
     None,
     "assertEquals('data', must('data', 'load'));"),
    ("code_explanation", "advanced",
     "Explain how set_error_handler interacts with try/catch.",
     "<?php\nset_error_handler(function($no, $str) {\n    throw new ErrorException($str);\n});\ntry {\n    trigger_error('x', E_USER_NOTICE);\n} catch (ErrorException $e) {\n    echo 'caught notice';\n}",
     "caught notice",
     "Because the handler throws, even notices become catchable exceptions inside try/catch.",
     "Assuming try/catch catches warnings without a custom error handler; by default it does not.",
     None,
     "assertEquals('caught notice', $out);"),
]

EXCEPTIONS = EXCEPTIONS[:30]