# -*- coding: utf-8 -*-
"""Sessions & Authentication Concepts (20)."""

SESSIONS_AUTH = [
    ("code_generation", "beginner",
     "Write code that starts a session and stores a value.",
     "<?php\nsession_start();\n$_SESSION['user'] = 'Ada';\necho $_SESSION['user'];",
     "Ada",
     "session_start must run before any output; it makes $_SESSION available across requests.",
     "Calling session_start after output has been sent, which raises a headers-already-sent warning.",
     None,
     "assertTrue(true);"),
    ("code_explanation", "beginner",
     "Explain what session_start does.",
     "<?php\nsession_start();",
     "initializes or resumes the session",
     "session_start either creates a new session or resumes an existing one based on the session cookie.",
     "Assuming sessions work without a cookie or session id being exchanged.",
     None,
     "assertTrue(function_exists('session_start'));"),
    ("code_generation", "intermediate",
     "Write code that logs a user out by clearing and destroying the session.",
     "<?php\nsession_start();\n$_SESSION = [];\nsession_destroy();\necho 'logged out';",
     "logged out",
     "Clearing $_SESSION and calling session_destroy removes server-side session data; the cookie should also be expired.",
     "Only unsetting one key, leaving the rest of the session intact.",
     None,
     "assertEquals('logged out', 'logged out');"),
    ("find_bug", "intermediate",
     "This login check trusts a client-supplied flag. Find the vulnerability.",
     "<?php\nif ($_COOKIE['is_admin'] === '1') {\n    grantAdmin();\n}",
     "anyone can set the cookie",
     "Cookies are client-controlled, so trusting is_admin enables privilege escalation; store the role server-side in the session.",
     "Using a client-side cookie value as an authorization decision.",
     "<?php\nsession_start();\nif (($_SESSION['role'] ?? '') === 'admin') {\n    grantAdmin();\n}",
     "assertTrue(true);"),
    ("code_generation", "intermediate",
     "Write code that regenerates the session id after login to prevent fixation.",
     "<?php\nsession_start();\nsession_regenerate_id(true);\n$_SESSION['user'] = $user;\n",
     "a new session id is issued",
     "session_regenerate_id(true) issues a fresh id and deletes the old session, mitigating session fixation.",
     "Keeping the same session id across privilege changes, which enables fixation attacks.",
     None,
     "assertTrue(function_exists('session_regenerate_id'));"),
    ("code_explanation", "intermediate",
     "Explain how password_hash stores a password securely.",
     "<?php\n$hash = password_hash('secret', PASSWORD_DEFAULT);\nvar_dump(strlen($hash) > 20);",
     "bool(true)",
     "password_hash produces a salted, slow hash including the algorithm and cost, suitable for storage.",
     "Using md5 or sha1 for passwords, which are fast and unsalted.",
     None,
     "assertTrue(strlen(password_hash('x', PASSWORD_DEFAULT)) > 20);"),
    ("code_generation", "intermediate",
     "Write code that verifies a password against a stored hash.",
     "<?php\n$ok = password_verify('secret', $storedHash);\nvar_dump($ok);",
     "bool(true) when the password matches",
     "password_verify recomputes the hash with the stored salt and compares it safely.",
     "Comparing hashes with == instead of using password_verify.",
     None,
     "assertTrue(password_verify('secret', password_hash('secret', PASSWORD_DEFAULT)));"),
    ("code_generation", "advanced",
     "Write code that rehashes a password when the algorithm or cost changes.",
     "<?php\nif (password_needs_rehash($hash, PASSWORD_DEFAULT)) {\n    $hash = password_hash($plain, PASSWORD_DEFAULT);\n}\n",
     "rehashes when needed",
     "password_needs_rehash detects outdated parameters and lets you upgrade hashes transparently on login.",
     "Assuming old hashes remain valid forever without rehashing.",
     None,
     "assertIsBool(password_needs_rehash(password_hash('x', PASSWORD_DEFAULT), PASSWORD_DEFAULT));"),
    ("find_bug", "advanced",
     "This authentication is vulnerable to timing attacks. Find the flaw.",
     "<?php\nif ($token === $_SESSION['token']) {\n    proceed();\n}",
     "string comparison may leak timing",
     "Use hash_equals for a constant-time comparison of secrets to avoid timing side channels.",
     "Comparing secret tokens with ===, which short-circuits and can leak timing information.",
     "<?php\nif (hash_equals($_SESSION['token'] ?? '', $token)) {\n    proceed();\n}",
     "assertTrue(hash_equals('a', 'a'));"),
    ("code_explanation", "intermediate",
     "Explain session fixation and how regeneration prevents it.",
     "<?php\nsession_start();\nsession_regenerate_id(true);\n",
     "new id after login",
     "An attacker who knows the pre-login session id could reuse it; regenerating on privilege change invalidates the old id.",
     "Assuming the session id is inherently private and never leaked.",
     None,
     "assertTrue(function_exists('session_regenerate_id'));"),
    ("code_generation", "intermediate",
     "Write code that sets secure session cookie parameters.",
     "<?php\nsession_set_cookie_params([\n    'httponly' => true,\n    'secure' => true,\n    'samesite' => 'Strict',\n]);\nsession_start();",
     "a hardened session cookie",
     "HttpOnly blocks JavaScript access, Secure requires HTTPS, and SameSite mitigates CSRF.",
     "Leaving defaults, which may allow JavaScript access to the session cookie.",
     None,
     "assertTrue(function_exists('session_set_cookie_params'));"),
    ("code_generation", "beginner",
     "Write code that checks whether a user is logged in.",
     "<?php\nsession_start();\nif (!isset($_SESSION['user'])) {\n    echo 'guest';\n} else {\n    echo $_SESSION['user'];\n}",
     "guest or the username",
     "The presence of a session user key indicates an authenticated session.",
     "Checking a client cookie instead of server-side session state.",
     None,
     "assertEquals('guest', !isset($_SESSION['user']) ? 'guest' : $_SESSION['user']);"),
    ("code_generation", "advanced",
     "Write code that implements a simple remember-me token safely.",
     "<?php\n$selector = bin2hex(random_bytes(8));\n$validator = bin2hex(random_bytes(32));\n$hash = hash('sha256', $validator);\n// store $selector and $hash in the DB",
     "a selector and hashed validator",
     "Storing a random selector with a hashed validator lets the server validate the token without storing the secret verbatim.",
     "Storing the raw remember-me token in the database, which leaks if the DB is compromised.",
     None,
     "assertIsString(hash('sha256', 'x'));"),
    ("code_explanation", "advanced",
     "Explain why sessions must be validated against a user fingerprint carefully.",
     "<?php\n$fp = hash('sha256', $_SERVER['HTTP_USER_AGENT'] ?? '');\n",
     "a fingerprint hash",
     "Binding sessions to a fingerprint can help but is weak because the user agent can change or be spoofed; use it only as a soft signal.",
     "Relying solely on a user-agent fingerprint for session security.",
     None,
     "assertIsString(hash('sha256', 'x'));"),
    ("find_bug", "intermediate",
     "This logout does not fully end the session. Find the bug.",
     "<?php\nsession_start();\nunset($_SESSION['user']);\necho 'out';\n",
     "other session data remains",
     "Unsetting one key leaves the rest of the session intact; clear $_SESSION entirely and destroy the session.",
     "Removing only a single session key instead of clearing the whole session.",
     "<?php\nsession_start();\n$_SESSION = [];\nsession_destroy();\necho 'out';",
     "assertTrue(true);"),
    ("code_generation", "intermediate",
     "Write code that stores a flash message in the session and reads it once.",
     "<?php\nsession_start();\n$msg = $_SESSION['flash'] ?? null;\nunset($_SESSION['flash']);\necho $msg ?? 'none';",
     "the message once, then none",
     "Reading then unsetting the key makes the message visible only on the next request.",
     "Leaving the flash key in place, so it reappears on every request.",
     None,
     "assertNull($_SESSION['flash'] ?? null);"),
    ("code_explanation", "intermediate",
     "Explain the difference between authentication and authorization.",
     "<?php\n// authentication: who are you\n// authorization: what may you do\n",
     "two distinct concerns",
     "Authentication verifies identity (login) while authorization decides permissions (role checks).",
     "Conflating the two and assuming a logged-in user is allowed to do everything.",
     None,
     "assertTrue(true);"),
    ("code_generation", "advanced",
     "Write code that rate-limits login attempts using the session.",
     "<?php\nsession_start();\n$_SESSION['tries'] = ($_SESSION['tries'] ?? 0) + 1;\nif ($_SESSION['tries'] > 5) {\n    echo 'too many';\n}\n",
     "too many after 5 tries",
     "Counting attempts in the session provides a simple throttle to slow brute-force attempts.",
     "Relying on session-based limits alone for a real attacker who clears cookies; also track by IP or account.",
     None,
     "assertTrue(true);"),
    ("code_generation", "intermediate",
     "Write code that stores the user id in the session after successful login.",
     "<?php\nsession_start();\nif (password_verify($plain, $row['hash'])) {\n    session_regenerate_id(true);\n    $_SESSION['uid'] = $row['id'];\n}\n",
     "uid stored in the session",
     "After verifying the password, store a minimal identifier server-side and regenerate the id.",
     "Storing the whole user row including the password hash in the session.",
     None,
     "assertTrue(true);"),
    ("find_bug", "advanced",
     "This session check is bypassable via an empty value. Find the bug.",
     "<?php\nsession_start();\nif ($_SESSION['role'] == 'admin' && $_SESSION['role'] !== '') {\n    allow();\n}",
     "logic is muddled",
     "The check is convoluted; a clear strict comparison to 'admin' with isset is safer and avoids loose-comparison surprises.",
     "Relying on loose comparison and manual empty checks instead of a single strict check.",
     "<?php\nsession_start();\nif (($_SESSION['role'] ?? '') === 'admin') {\n    allow();\n}",
     "assertTrue(true);"),
    ("code_explanation", "beginner",
     "Explain why session data lives on the server.",
     "<?php\n$_SESSION['cart'] = [1,2,3];\n",
     "cart stored server-side",
     "The session id is sent to the client via a cookie, but the actual data is stored on the server, so clients cannot read or tamper with it.",
     "Believing session contents are stored in the cookie and visible to the user.",
     None,
     "assertTrue(true);"),
]

SESSIONS_AUTH = SESSIONS_AUTH[:20]