# -*- coding: utf-8 -*-
"""Hand-authored records: PHP Basics (60). Tuple order:
(task_type, difficulty, prompt, code, expected_output, explanation,
 common_mistake, corrected_code, test_case)"""

BASICS = [
    ("code_generation", "beginner",
     "Write a PHP script that prints the word PHP on one line and the number 8 on the next line.",
     '<?php\necho "PHP" . PHP_EOL;\necho 8 . PHP_EOL;',
     "PHP\n8",
     "echo outputs strings and numbers; PHP_EOL inserts a platform-independent newline.",
     "Beginners write '\\n' in single quotes, which prints a literal backslash-n instead of a newline.",
     '<?php\necho "PHP\\n";\necho 8, "\\n";',
     "Run `php script.php` and check stdout is exactly PHP then 8 on the next line."),
    ("code_explanation", "beginner",
     "Explain what the following PHP code does.",
     '<?php\ndeclare(strict_types=1);\n$a = 5;\n$b = 3;\nprintf("%d + %d = %d\\n", $a, $b, $a + $b);',
     "5 + 3 = 8",
     "declare(strict_types=1) enables strict type checking for function calls in this file; printf substitutes each %d with the matching argument.",
     "Assuming strict_types changes all variable coercion; it only enforces types at function boundaries, not for normal assignments.",
     None,
     "Change $b to the string '3' and confirm arithmetic still works (variables are not affected by strict_types)."),
    ("predict_output", "intermediate",
     "What does this code print?",
     '<?php\necho 1 + "2apples";\necho " ";\necho "5" . 5;',
     "3 55",
     "Leading numeric strings are cast to their numeric value in arithmetic ('2apples' becomes 2), while the dot operator concatenates without casting.",
     "Expecting an error because '2apples' is not numeric; PHP 8 still parses the leading integer part.",
     None,
     "Assert the output equals '3 55' by capturing it with output buffering."),
    ("code_generation", "beginner",
     "Write a PHP script that defines a constant PI with the value 3.14159 and prints it.",
     '<?php\ndefine("PI", 3.14159);\necho PI;',
     "3.14159",
     "define() creates a runtime constant that is globally accessible and cannot be changed.",
     "Using $PI to read a constant; constants are referenced without the dollar sign.",
     '<?php\nconst PI = 3.14159;\necho PI;',
     "var_dump(defined('PI')); // bool(true)"),
    ("explain_error", "intermediate",
     "A beginner wrote this and gets 'Warning: Undefined variable $name'. Explain the error.",
     '<?php\necho "Hello, $name";',
     "Warning: Undefined variable $name (and Hello, ).",
     "The variable $name was never assigned before use; in PHP 8 using an undefined variable emits a warning and evaluates to an empty string.",
     "Thinking the message is a fatal error; it is only a warning, execution continues.",
     '<?php\n$name = "World";\necho "Hello, $name";',
     "Set error_reporting(E_ALL) during development to always surface this warning."),
    ("code_generation", "intermediate",
     "Write code that swaps the values of two variables without a temporary variable, then prints them.",
     '<?php\n$a = 1;\n$b = 2;\n[$a, $b] = [$b, $a];\necho "$a $b";',
     "2 1",
     "Array destructuring assigns the swapped values in one expression without an explicit temporary variable.",
     "Writing list($a,$b)=array($b,$a) is correct but the short [] syntax is clearer.",
     None,
     "assertEquals('2 1', trim(shell_exec('php swap.php')));"),
    ("code_explanation", "intermediate",
     "Explain the difference between echo and print in this snippet.",
     '<?php\necho "a", "b", "c";\n$ok = print "x";',
     "abcx",
     "echo accepts multiple comma-separated arguments and returns nothing; print accepts one argument and returns 1, so it can be used in expressions.",
     "Trying to use echo inside an expression such as $x = echo 'a'; which is a parse error.",
     None,
     "assertEquals(1, ($ok = print 'x'));"),
    ("predict_output", "beginner",
     "What is printed by this code?",
     '<?php\n$x = "5";\n$y = 5;\nvar_dump($x == $y);\nvar_dump($x === $y);',
     "bool(true)\nbool(false)",
     "== compares after type juggling so '5' equals 5; === requires the same type and value, and string vs int fails.",
     "Believing == and === behave the same for scalar values.",
     None,
     "assertEquals(false, ('5' === 5));"),
    ("code_generation", "beginner",
     "Write a script that prints today's date in the format YYYY-MM-DD using the date() function.",
     '<?php\necho date("Y-m-d");',
     "e.g. 2024-01-15",
     "date() formats the current timestamp using format characters; Y is the 4-digit year, m the month and d the day.",
     "Using the lowercase m for minutes instead of months in a date context.",
     None,
     "assertEquals(date('Y-m-d'), trim(shell_exec('php date.php')));"),
    ("code_completion", "beginner",
     "Complete the code so it prints the sum of $a and $b on a single line.",
     '<?php\n$a = 10;\n$b = 25;\n// TODO: print the sum',
     "35",
     "The missing line echoes the arithmetic result; echo $a + $b; does the job.",
     "Concatenating with a dot and forgetting parentheses changes the meaning of the expression.",
     '<?php\n$a = 10;\n$b = 25;\necho $a + $b;',
     "assertSame('35', trim(shell_exec('php sum.php')));"),
    ("code_review", "intermediate",
     "Review this snippet and point out the problem.",
     "<?php\n$name = 'World';\necho 'Hello, ${name}!';",
     "Hello, ${name}!",
     "Inside single quotes PHP does not expand variables, so ${name} is literal text and is not interpolated.",
     "Believing variable interpolation works in single-quoted strings.",
     '<?php\n$name = \'World\';\necho "Hello, {$name}!";',
     "assertEquals('Hello, World!', trim(shell_exec('php greet.php')));"),
    ("code_generation", "intermediate",
     "Write code using a heredoc string that prints a two-line message including a variable.",
     '<?php\n$user = "Sara";\necho <<<TEXT\nHello $user\nWelcome back!\nTEXT;',
     "Hello Sara\nWelcome back!",
     "Heredoc behaves like a double-quoted string: variables are interpolated and newlines are preserved.",
     "Indenting the closing identifier incorrectly on PHP < 7.3 (fails); on 8.x flexible indentation is allowed but strip rules apply.",
     None,
     "assertStringContainsString('Sara', $out);"),
    ("predict_output", "intermediate",
     "What does this print? Give the exact output of the modulo operations.",
     '<?php\necho 10 % 3;\necho ":";\necho -10 % 3;',
     "1:-1",
     "The modulo operator returns the remainder with the sign of the dividend; -10 % 3 is -1 in PHP.",
     "Assuming modulo always returns a positive number.",
     None,
     "assertEquals('1:-1', trim(shell_exec('php mod.php')));"),
    ("code_generation", "intermediate",
     "Write a PHP script that reads the host value from $_SERVER with a fallback of localhost.",
     "<?php\n$host = $_SERVER['HTTP_HOST'] ?? 'localhost';\necho $host;",
     "localhost (when no HTTP_HOST is set)",
     "The null coalescing operator returns the right operand when the left is null or undefined, avoiding an undefined-index warning.",
     "Using $_SERVER['HTTP_HOST'] directly, which triggers a warning when the key is absent (e.g. CLI).",
     "<?php\n$host = $_SERVER['HTTP_HOST'] ?? $_SERVER['SERVER_NAME'] ?? 'localhost';\necho $host;",
     "Run with `php script.php`; output should be localhost."),
    ("explain_error", "beginner",
     "Explain this parse error.",
     '<?php\necho "Hello"\necho "World";',
     "PHP Parse error: syntax error, unexpected 'echo' ...",
     "The first statement is missing its terminating semicolon, so the parser sees two echo keywords in a row.",
     "Forgetting the semicolon at the end of a statement.",
     '<?php\necho "Hello";\necho "World";',
     "`php -l script.php` reports the syntax error location."),
    ("refactoring", "intermediate",
     "Refactor these repeated concatenations to use a single echo with multiple arguments.",
     '<?php\necho "Name: ";\necho $name;\necho " - Age: ";\necho $age;',
     "Name: Ahmed - Age: 30",
     "echo accepts multiple comma-separated arguments, so the repeated statements collapse into one call.",
     "Switching to concatenation with dots but still forgetting the spaces between words.",
     '<?php\necho "Name: ", $name, " - Age: ", $age;',
     "assertEquals('Name: Ahmed - Age: 30', $out);"),
    ("code_generation", "beginner",
     "Write a one-line PHP program that prints the result of 2 to the power of 10.",
     '<?php\necho 2 ** 10;',
     "1024",
     "The ** operator raises a number to a power.",
     "Using ^ for exponentiation; in PHP ^ is the bitwise XOR operator.",
     None,
     "assertEquals(1024, 2 ** 10);"),
    ("predict_output", "beginner",
     "What is printed after the post- and pre-increment of $a?",
     '<?php\n$a = 7;\n$a++;\n++$a;\necho $a;',
     "9",
     "Both post- and pre-increment increase the value by one; only the returned value differs, which is not used here.",
     "Thinking $a++ and ++$a produce different results when the return value is ignored.",
     None,
     "assertEquals(9, $a);"),
    ("code_explanation", "advanced",
     "Explain the behavior of the spaceship operator in this comparison.",
     '<?php\nvar_dump(1 <=> 2);\nvar_dump(2 <=> 2);\nvar_dump(3 <=> 2);',
     "int(-1) int(0) int(1)",
     "The spaceship operator returns -1, 0 or 1 when the left operand is respectively less than, equal to or greater than the right.",
     "Expecting a boolean from <=>; it always returns an integer.",
     None,
     "assertEquals([-1,0,1], [1<=>2, 2<=>2, 3<=>2]);"),
    ("code_generation", "intermediate",
     "Write a script that throws and catches a simple exception to show control flow.",
     '<?php\ntry {\n    throw new RuntimeException("boom");\n} catch (RuntimeException $e) {\n    echo "Caught: " . $e->getMessage();\n}',
     "Caught: boom",
     "throw unwinds the stack until a matching catch block handles the exception; getMessage() returns the supplied text.",
     "Catching the generic Exception before the specific type, making the specific catch unreachable.",
     None,
     "assertEquals('Caught: boom', $out);"),
    ("write_test", "intermediate",
     "Write a PHPUnit test that checks a greet($name) function returns 'Hi, Bob'.",
     '<?php\nuse PHPUnit\\Framework\\TestCase;\n\nclass GreetTest extends TestCase\n{\n    public function testGreet(): void\n    {\n        $this->assertSame(\'Hi, Bob\', greet(\'Bob\'));\n    }\n}',
     None,
     "A single assertion with assertSame checks both the value and type of the returned greeting.",
     "Using assertEquals on strings, which allows subtle type differences; assertSame is stricter.",
     None,
     "phpunit --filter testGreet passes when greet('Bob') returns 'Hi, Bob'."),
    ("code_generation", "beginner",
     "Write code that prints a random integer between 1 and 6 using random_int().",
     '<?php\necho random_int(1, 6);',
     "a value from 1 to 6",
     "random_int() returns a uniform, cryptographically secure integer in the inclusive range.",
     "Using rand() or mt_rand(); random_int() is preferred for security-sensitive randomness.",
     None,
     "$v = random_int(1,6); assertTrue($v >= 1 && $v <= 6);"),
    ("find_bug", "intermediate",
     "Find the bug: this should print true but the developer claims it prints false.",
     '<?php\n$values = [1, 2, 3];\nif ($values) {\n    echo "true";\n} else {\n    echo "false";\n}',
     "It actually prints true",
     "A non-empty array is truthy, so the report is a false alarm. The real trap is that an EMPTY array is ALSO truthy in PHP, unlike in JavaScript.",
     "Assuming empty arrays are falsy as in JavaScript.",
     None,
     "var_dump((bool)[]); // bool(true)"),
    ("conversion", "intermediate",
     "Convert this JS-style snippet to idiomatic PHP using a strict empty check.",
     '<?php\n$x = "0";\nif ($x == false) { echo "empty"; } else { echo "set"; }',
     "set",
     "PHP loose comparison treats the string '0' as equal to false, which surprises developers coming from JavaScript.",
     "Porting JS truthiness rules directly to PHP.",
     '<?php\n$x = "0";\nif (trim($x) === \'\') { echo "empty"; } else { echo "set"; }',
     "assertEquals('set', $out);"),
    ("code_review", "beginner",
     "Review this output statement; is it the best choice for showing a debugging value?",
     '<?php\necho $user;',
     "the value of $user, or a warning if unset",
     "echo is fine for quick output, but for inspecting the real shape of a value var_dump() or print_r() is clearer because they reveal type and structure.",
     "Using echo on arrays, which raises 'Array to string conversion'.",
     '<?php\nvar_dump($user);',
     "echo []; // Warning: Array to string conversion"),
    ("code_generation", "intermediate",
     "Write a script using the match expression to map a status code to a label.",
     '<?php\n$code = 404;\n$label = match ($code) {\n    200, 201 => "OK",\n    404 => "Not Found",\n    500 => "Server Error",\n    default => "Unknown",\n};\necho $label;',
     "Not Found",
     "match is a strict-comparison expression that returns a value and supports multiple comma-separated conditions per arm.",
     "Forgetting the default arm, which throws UnhandledMatchError for unmatched values.",
     None,
     "assertEquals('Not Found', $label);"),
    ("predict_output", "intermediate",
     "What does this print? Report the type returned for the string-plus-int addition.",
     '<?php\n$s = "10";\n$n = $s + 5;\necho gettype($n);',
     "integer",
     "The string '10' is juggled to the integer 10 for the addition, so the result is an int.",
     "Expecting a float because one operand started as a string.",
     None,
     "assertEquals('integer', gettype('10' + 5));"),
    ("code_generation", "beginner",
     "Write a script that prints the current Unix timestamp.",
     '<?php\necho time();',
     "e.g. 1710000000",
     "time() returns the number of seconds since the Unix epoch as an integer.",
     "Using date() without a format when a raw timestamp is required.",
     None,
     "assertIsInt(time());"),
    ("code_explanation", "beginner",
     "Explain the four different ways to write comments shown here.",
     '<?php\n// single line\n# shell style\n/* block\n   comment */\n/** doc block */\necho "ok";',
     "ok",
     "// and # comment a single line, /* */ spans multiple lines, and /** */ is a documentation block used by tools like phpDocumentor.",
     "Nesting /* */ comments, which is not supported and breaks parsing.",
     None,
     "assertEquals('ok', $out);"),
    ("code_generation", "intermediate",
     "Write code that uses sprintf to build a zero-padded ID like INV-0042.",
     '<?php\n$id = 42;\necho sprintf("INV-%04d", $id);',
     "INV-0042",
     "The %04d placeholder pads the integer with leading zeros to a width of four digits.",
     "Using %d alone, which prints 42 without padding.",
     None,
     "assertEquals('INV-0042', sprintf('INV-%04d', 42));"),
    ("find_bug", "intermediate",
     "This should print 'Total: 3' but does not. Find the bug.",
     '<?php\necho "Total: " . 1 + 2;',
     "It prints 3 but with a deprecation, not 'Total: 3'",
     "The dot and plus precedence causes PHP to evaluate ('Total: ' . 1) + 2, coercing the string to a number, so the intent is broken.",
     "Mixing concatenation and arithmetic without parentheses.",
     '<?php\necho "Total: " . (1 + 2);',
     "assertEquals('Total: 3', trim(shell_exec('php t.php')));"),
    ("code_generation", "beginner",
     "Write a script that prints Even if the number $n is even, using the modulo operator.",
     '<?php\n$n = 4;\necho ($n % 2 === 0) ? "Even" : "Odd";',
     "Even",
     "Modulo by 2 yields 0 for even numbers; the ternary selects the label.",
     "Using = instead of === inside the condition.",
     None,
     "assertEquals('Even', $out);"),
    ("code_explanation", "intermediate",
     "Explain the purpose of these error-handling directives.",
     "<?php\nini_set('display_errors', '1');\nerror_reporting(E_ALL);\ntrigger_error('demo', E_USER_WARNING);",
     "Warning: demo in ...",
     "ini_set enables showing errors, error_reporting(E_ALL) selects which levels are reported, and trigger_error raises a user warning.",
     "Enabling display_errors in production, which leaks paths and internals to users.",
     "<?php\n// Development only:\nini_set('display_errors', '1');\nerror_reporting(E_ALL);",
     "In production set display_errors=Off and log_errors=On."),
    ("code_generation", "intermediate",
     "Write a script that prints the integer quotient and remainder of dividing 17 by 5.",
     '<?php\necho intdiv(17, 5), " remainder ", 17 % 5;',
     "3 remainder 2",
     "intdiv() performs integer division and % returns the remainder.",
     "Using / which returns a float (3.4) instead of an integer quotient.",
     None,
     "assertEquals('3 remainder 2', $out);"),
    ("predict_output", "advanced",
     "What does this code print and why?",
     '<?php\n$a = "abc";\n$b = &$a;\n$b .= "d";\necho $a;',
     "abcd",
     "Assigning by reference with & makes $b and $a point to the same value, so modifying $b also changes $a.",
     "Expecting the copy semantics of normal assignment when & (reference) is used.",
     None,
     "assertEquals('abcd', $a);"),
    ("code_generation", "beginner",
     "Write a script that quits early with a message and an exit code of 2.",
     '<?php\nfwrite(STDERR, "Invalid argument\\n");\nexit(2);',
     "stderr: Invalid argument ; exit code 2",
     "exit() terminates the script and returns the given status code to the shell; fwrite to STDERR keeps stdout clean.",
     "Using echo for error messages, polluting standard output that may be parsed.",
     None,
     "Run `php s.php; echo $?` and expect 2."),
    ("code_generation", "intermediate",
     "Write code that demonstrates named arguments.",
     '<?php\nfunction rect(int $w, int $h): int {\n    return $w * $h;\n}\necho rect(h: 4, w: 3);',
     "12",
     "Named arguments let callers pass values by parameter name regardless of order, improving readability.",
     "Mixing named and positional arguments in an invalid order.",
     None,
     "assertEquals(12, rect(h: 4, w: 3));"),
    ("code_review", "intermediate",
     "Review this snippet for readability and correctness.",
     '<?php\n$r = $a ? $b ? 1 : 2 : 3;',
     "the nested ternary result (discouraged)",
     "Nested ternaries without parentheses are ambiguous and error-prone; use explicit parentheses or split into if/else or match.",
     "Relying on PHP's associativity of chained ternaries.",
     '<?php\nif ($a) {\n    $r = $b ? 1 : 2;\n} else {\n    $r = 3;\n}',
     "Static analysis warns about the ambiguous nested ternary."),
    ("code_generation", "advanced",
     "Write a script that uses a generator to yield the first three square numbers.",
     '<?php\nfunction squares(): Generator {\n    for ($i = 1; $i <= 3; $i++) {\n        yield $i * $i;\n    }\n}\nforeach (squares() as $s) {\n    echo $s, " ";\n}',
     "1 4 9",
     "A generator yields values lazily one at a time, keeping memory usage low even for large sequences.",
     "Trying to return an array of values from a generator function; it must yield.",
     None,
     "assertEquals([1,4,9], iterator_to_array(squares()));"),
    ("predict_output", "advanced",
     "What is the output of this code?",
     '<?php\necho intval(true) + intval("3.9");',
     "4",
     "intval(true) is 1 and intval('3.9') truncates to 3, giving 4.",
     "Thinking intval('3.9') rounds to 4 before addition.",
     None,
     "assertEquals(4, intval(true) + intval('3.9'));"),
    ("explain_error", "intermediate",
     "Explain the deprecation notice in this script.",
     '<?php\n$x = null;\necho strlen($x);',
     "Deprecated: strlen(): Passing null to parameter #1 ...",
     "In PHP 8.1+, passing null to a non-nullable internal string parameter is deprecated; the value is coerced to an empty string.",
     "Ignoring deprecation notices that become fatal in future versions.",
     "<?php\n$x = null;\necho strlen($x ?? '');",
     "assertSame(0, strlen(null ?? ''));"),
    ("code_generation", "intermediate",
     "Write a script that computes the average of an array of numbers using array_sum and count.",
     '<?php\n$nums = [10, 20, 30, 40];\n$avg = array_sum($nums) / count($nums);\necho $avg;',
     "25",
     "array_sum() adds all elements and count() returns the number of elements; dividing gives the mean.",
     "Dividing by count() without guarding against an empty array (division by zero).",
     None,
     "assertEquals(25, array_sum([10,20,30,40]) / 4);"),
    ("code_generation", "beginner",
     "Write a script that prints Yes if the current year is even, otherwise No.",
     "<?php\n$year = (int) date('Y');\necho ($year % 2 === 0) ? 'Yes' : 'No';",
     "Yes or No depending on the year",
     "date('Y') returns a string, so it is cast to int before applying modulo.",
     "Forgetting to cast the string year to an integer before arithmetic.",
     None,
     "$y=(int)date('Y'); assertIsBool($y % 2 === 0);"),
    ("code_explanation", "beginner",
     "Explain the output of this code that mixes interpolation and concatenation.",
     '<?php\n$fruit = "apple";\necho "I like {$fruit}s and " . $fruit . "s";',
     "I like apples and apples",
     "Curly-brace interpolation lets you append a suffix to a variable inside a double-quoted string; concatenation achieves the same outside the quotes.",
     "Writing \"$fruits\" expecting interpolation of $fruit with a suffix, which looks for a variable named $fruits.",
     None,
     "assertEquals('I like apples and apples', $out);"),
    ("code_generation", "intermediate",
     "Write a script that uses the nullsafe operator to read a nested value safely.",
     "<?php\nclass Profile { public string $city = 'Cairo'; }\nclass User { public ?Profile $profile = null; }\n\n$user = new User();\necho $user->profile?->city ?? 'unknown';",
     "unknown",
     "The nullsafe operator ?-> short-circuits to null when the left side is null, and ?? then supplies the default.",
     "Using -> on a possibly-null object, causing 'Call to a member function on null'.",
     None,
     "assertEquals('unknown', $user->profile?->city ?? 'unknown');"),
    ("find_bug", "beginner",
     "This should print the product of $x and $y but does not. Find the bug.",
     '<?php\n$x = 5;\n$y = 2;\n$result = $x * $y;\necho $y;',
     "2",
     "The correct result is stored in $result but the script prints $y; the echoed variable is wrong.",
     "Echoing the wrong variable after computing the result correctly.",
     '<?php\n$x = 5;\n$y = 2;\n$result = $x * $y;\necho $result;',
     "assertEquals(10, $result);"),
    ("code_generation", "intermediate",
     "Write a script that reads command-line arguments from $argv and prints them, skipping the script name.",
     '<?php\nforeach (array_slice($argv, 1) as $arg) {\n    echo $arg, PHP_EOL;\n}',
     "each argument on its own line",
     "$argv[0] is the script name, so array_slice($argv, 1) returns only the user-supplied arguments.",
     "Including $argv[0] in the output, which prints the script path.",
     None,
     "Run `php script.php a b c` and expect a, b, c."),
    ("predict_output", "beginner",
     "What is printed by these two loose comparisons?",
     '<?php\necho 5 == "5";\necho PHP_EOL;\necho "5" . 1 == "51";',
     "1\n1",
     "The first comparison is true, printed as 1; the second evaluates ('5'.1) == '51' loosely, which is true, printed as 1.",
     "Confusing the printed 1 with the integer value instead of the boolean true representation.",
     None,
     "assertEquals(\"1\\n1\", $out);"),
    ("refactoring", "beginner",
     "Refactor this code to use the null coalescing operator instead of isset().",
     "<?php\n$name = isset($_GET['name']) ? $_GET['name'] : 'guest';\necho $name;",
     "the GET name or guest",
     "?? expresses the default-if-missing logic more concisely than a ternary with isset().",
     "Using ?: (elvis) which also replaces falsy values like '0' or '', changing behavior.",
     "<?php\n$name = $_GET['name'] ?? 'guest';\necho $name;",
     "With ?name=, output the name; without it, output guest."),
    ("code_generation", "beginner",
     "Write a script that prints a greeting using the ternary operator based on the hour of day.",
     "<?php\n$hour = (int) date('G');\necho $hour < 12 ? 'Good morning' : 'Good afternoon';",
     "Good morning (before noon)",
     "date('G') returns the hour in 24-hour format without leading zeros; the ternary picks the greeting.",
     "Using date('g') (12-hour) and misjudging morning vs afternoon.",
     None,
     "assertContains($out, $hour < 12 ? 'morning' : 'afternoon');"),
    ("code_generation", "intermediate",
     "Write a script that formats a float to two decimal places with number_format.",
     "<?php\n$price = 1234.5;\necho number_format($price, 2, '.', ',');",
     "1,234.50",
     "number_format() controls decimals, decimal separator and thousands separator for readable output.",
     "Forgetting the separators, which yields 1234.50 without grouping.",
     None,
     "assertEquals('1,234.50', number_format(1234.5, 2, '.', ','));"),
    ("code_explanation", "intermediate",
     "Explain what each line achieves.",
     '<?php\n$list = range(1, 5);\nshuffle($list);\nsort($list);',
     "a sorted array [1,2,3,4,5]",
     "range() builds an array; shuffle() randomizes order; sort() returns it to ascending order, effectively undoing the shuffle.",
     "Expecting shuffle to persist after calling sort immediately afterwards.",
     None,
     "assertEquals([1,2,3,4,5], $list);"),
    ("code_generation", "intermediate",
     "Write code that prints the ASCII code of a character using ord().",
     "<?php\necho ord('A');",
     "65",
     "ord() returns the integer ASCII/byte value of the first character of the string.",
     "Using chr() (the inverse) when the numeric code is needed.",
     None,
     "assertEquals(65, ord('A'));"),
    ("write_test", "beginner",
     "Write a PHPUnit data-provider test for an isEven() function.",
     '<?php\nuse PHPUnit\\Framework\\TestCase;\n\nclass EvenTest extends TestCase\n{\n    /** @dataProvider numbers */\n    public function testIsEven(int $n, bool $expected): void\n    {\n        $this->assertSame($expected, isEven($n));\n    }\n\n    public static function numbers(): array\n    {\n        return [[2, true], [3, false], [0, true], [-4, true]];\n    }\n}',
     None,
     "A data provider runs the same assertion with several input/output pairs, improving coverage and reducing duplication.",
     "Making the provider non-static; PHPUnit requires it to be static in modern versions.",
     None,
     "phpunit runs testIsEven four times, all passing."),
    ("code_generation", "advanced",
     "Write a script that demonstrates the spread operator for unpacking function arguments.",
     '<?php\nfunction sum(int ...$nums): int {\n    return array_sum($nums);\n}\n$args = [1, 2, 3, 4];\necho sum(...$args);',
     "10",
     "The ...$nums variadic parameter collects arguments into an array, and ...$args at the call site unpacks them.",
     "Forgetting that $nums inside the function is already an array when using variadics.",
     None,
     "assertEquals(10, sum(...[1,2,3,4]));"),
    ("code_review", "advanced",
     "Review this code for a subtle floating-point issue.",
     "<?php\n$total = 0.0;\n$total += 0.1;\n$total += 0.2;\nvar_dump($total === 0.3);",
     "bool(false)",
     "Binary floating point cannot represent 0.1 and 0.2 exactly, so the sum is 0.30000000000000004 and strict comparison fails.",
     "Comparing floats with === or ==; use an epsilon or round().",
     "<?php\n$total = 0.0;\n$total += 0.1;\n$total += 0.2;\nvar_dump(abs($total - 0.3) < 1e-9);",
     "assertTrue(abs($total - 0.3) < 1e-9);"),
    ("predict_output", "intermediate",
     "What does this print? Pay attention to array copy semantics.",
     "<?php\n$a = [1, 2, 3];\n$b = $a;\n$b[] = 4;\necho count($a), ',', count($b);",
     "3,4",
     "Assigning an array to another variable copies it (copy-on-write), so appending to $b does not affect $a.",
     "Expecting object-like reference behavior for arrays, which are value types in PHP.",
     None,
     "assertEquals('3,4', $out);"),
    ("code_generation", "beginner",
     "Write a script that uses the constant PHP_INT_MAX to show the largest integer value.",
     "<?php\necho PHP_INT_MAX;",
     "9223372036854775807 (on 64-bit)",
     "PHP_INT_MAX is a predefined constant holding the maximum integer for the platform.",
     "Assuming it is the same on 32-bit and 64-bit builds.",
     None,
     "assertIsInt(PHP_INT_MAX);"),
    ("explain_error", "advanced",
     "Explain why this code fails with 'Cannot use positional argument after named argument'.",
     "<?php\nfunction f(int $a, int $b): int { return $a + $b; }\necho f(a: 1, 2);",
     "Fatal error: Cannot use positional argument after named argument",
     "Once a named argument is used, all following arguments must also be named so the mapping is unambiguous.",
     "Mixing named and positional arguments in an invalid order.",
     "<?php\nfunction f(int $a, int $b): int { return $a + $b; }\necho f(a: 1, b: 2);",
     "assertEquals(3, f(a:1, b:2));"),
    ("code_generation", "intermediate",
     "Write a script that prints whether a string contains another string using str_contains.",
     '<?php\n$haystack = "Hello World";\necho str_contains($haystack, "World") ? "yes" : "no";',
     "yes",
     "str_contains() (PHP 8) returns a boolean indicating whether the needle appears in the haystack.",
     "Using strpos() and comparing === false incorrectly (0 is a valid position, so it must not be treated as not-found).",
     None,
     "assertTrue(str_contains('Hello World', 'World'));"),
    ("refactoring", "intermediate",
     "Refactor this if/else-if chain that returns values into a match expression.",
     "<?php\nfunction dayType(int $d): string {\n    if ($d === 6 || $d === 7) {\n        return 'weekend';\n    } elseif ($d >= 1 && $d <= 5) {\n        return 'weekday';\n    }\n    return 'invalid';\n}",
     "weekday / weekend / invalid",
     "match expresses the mapping more compactly and without fall-through; conditions become arms.",
     "Using match expecting range support; match only supports equality, so ranges become guard conditions with match(true).",
     "<?php\nfunction dayType(int $d): string {\n    return match (true) {\n        $d === 6, $d === 7 => 'weekend',\n        $d >= 1 && $d <= 5 => 'weekday',\n        default => 'invalid',\n    };\n}",
     "assertEquals('weekend', dayType(6));"),
    ("code_generation", "intermediate",
     "Write a script that uses associative array destructuring to read a config array.",
     "<?php\n$config = ['host' => 'localhost', 'port' => 3306];\n['host' => $host, 'port' => $port] = $config;\necho \"$host:$port\";",
     "localhost:3306",
     "Associative destructuring binds array values to variables by key.",
     "Using order-dependent destructuring when keys would make the intent clearer.",
     None,
     'assertEquals(\'localhost:3306\', "$host:$port");'),
    ("code_review", "beginner",
     "Review this script that mixes HTML and PHP; suggest a small improvement.",
     '<?php echo "<ul>"; foreach ($items as $i) { echo "<li>" . htmlspecialchars($i) . "</li>"; } echo "</ul>";',
     "<ul><li>item</li>...</ul>",
     "Mixing PHP and HTML on one line hurts readability; the alternative syntax keeps markup clean.",
     "Printing raw values into HTML without escaping, risking XSS.",
     '<ul>\n<?php foreach ($items as $i): ?>\n    <li><?= htmlspecialchars($i) ?></li>\n<?php endforeach; ?>\n</ul>',
     "Ensure every interpolated value passes through htmlspecialchars()."),
    ("code_generation", "advanced",
     "Write a script that declares a backed enum and prints its backing value.",
     "<?php\nenum Status: string {\n    case Active = 'active';\n    case Closed = 'closed';\n}\necho Status::Active->value;",
     "active",
     "A backed enum maps each case to a scalar value accessible through the read-only ->value property.",
     "Trying to assign to ->value; enum case values are immutable.",
     None,
     "assertEquals('active', Status::Active->value);"),
    ("predict_output", "beginner",
     "What does this output?",
     "<?php\n$name = \"Sam\";\necho \"Hi $name!\", PHP_EOL;\necho 'Hi $name!';",
     "Hi Sam!\nHi $name!",
     "Double quotes interpolate; single quotes print the literal characters including the dollar sign.",
     "Assuming single quotes interpolate variables like double quotes.",
     None,
     "assertEquals(\"Hi Sam!\\nHi $name!\", $out);"),
    ("code_completion", "intermediate",
     "Complete the script so it prints the maximum value of the array.",
     '<?php\n$scores = [88, 95, 72, 90];\n// TODO: print the maximum',
     "95",
     "max() returns the largest element of an array.",
     "Manually sorting and taking the last element when max() is simpler and faster.",
     '<?php\n$scores = [88, 95, 72, 90];\necho max($scores);',
     "assertEquals(95, max($scores));"),
    ("code_generation", "intermediate",
     "Write a script that checks the PHP version and prints a message accordingly.",
     "<?php\nif (version_compare(PHP_VERSION, '8.0.0', '>=')) {\n    echo \"PHP 8 or newer\";\n} else {\n    echo \"Older PHP\";\n}",
     "PHP 8 or newer",
     "version_compare() performs a correct semantic comparison of version strings.",
     "Comparing PHP_VERSION with a plain string comparison, which is unreliable for dotted versions.",
     None,
     "assertTrue(version_compare(PHP_VERSION, '8.0.0', '>='));"),
    ("code_explanation", "advanced",
     "Explain the difference between include and require shown here.",
     "<?php\ninclude 'optional.php';\nrequire 'essential.php';",
     "optional.php missing => warning; essential.php missing => fatal error",
     "include emits a warning and continues if the file is missing, while require emits a fatal error and stops execution.",
     "Using include for files the rest of the script depends on, leading to silent failures.",
     "<?php\ninclude_once 'optional.php';\nrequire_once 'essential.php';",
     "Missing essential.php with require stops execution."),
    ("predict_output", "advanced",
     "What does this print?",
     "<?php\n$a = 0;\n$b = '0';\nvar_dump(empty($a));\nvar_dump(empty($b));",
     "bool(true)\nbool(true)",
     "empty() considers 0, '0', '', null, false and [] to be empty.",
     "Expecting empty('0') to be false because the string is not zero-length.",
     None,
     "assertTrue(empty('0'));"),
]

# Keep exactly the first 60 curated records.
BASICS = BASICS[:60]
